### ISSUE TITLE
Rebooting workspaces locally crashes the PL server

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#10716]
I'll try to put together a better reproducible example and narrow down whether this is "just me" later today, but in case anybody else is noticing it already, hitting "Reboot" or "Reset" on a workspace in local testing is just crashing everything:

```
info: Workspace host ready
info: PrairieLearn server ready, press Control-C to quit
info: Go to http://localhost:3000
info: Launching workspace-1-1 (useInitialZip=true)
info: Not pulling docker image
```

(Then I do stuff in the workspace and click "Reboot":)

```
file:///PrairieLearn/apps/prairielearn/dist/server.js:265
                throw new error.HttpStatusError(404, 'Workspace is not running');
                      ^

HttpStatusError: Workspace is not running
    at router (file:///PrairieLearn/apps/prairielearn/dist/server.js:265:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.getTarget (/PrairieLearn/node_modules/http-proxy-middleware/dist/router.js:14:21)
    at async HttpProxyMiddleware.applyRouter (/PrairieLearn/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:110:29)
    at async HttpProxyMiddleware.prepareProxyRequest (/PrairieLearn/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:97:13)
    at async HttpProxyMiddleware.handleUpgrade (/PrairieLearn/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:62:44) {
  status: 404
}
```

There's probably just something weird with my setup that is causing it to not enumerate these properly. Creating a new variant and starting it up does work, though.

**Comment by nwalters512** [comment]
Is this actually a full-on crash (i.e. does the Node process stop) or is this just an error logged to the console?

**Comment by echuber2** [comment]
It's a full crash. The PL web server halts. However, the workspace host does not halt.

I can reproduce it with the latest PL Docker and this invocation:

```
sudo docker run -it --rm -p 3000:3000 -v /home/[user]/[other_subdirectories]/pl_ag_jobs:/jobs -e HOST_JOBS_DIR=/home/[user]/[other_subdirectories]/pl_ag_jobs -v /var/run/docker.sock:/var/run/docker.sock --add-host=host.docker.internal:172.17.0.1 prairielearn/prairielearn
```

Open the default Jupyter Workspace example question demo/workspace/jupyterlab, start the workspace, then click Reboot or Reset.

**Comment by echuber2** [comment]
I think I found one of the causes, but I'm not sure why this is a recent thing or what the root cause is. On this query where it fails:

https://github.com/PrairieLearn/PrairieLearn/blob/eeeca1dab9c0c23764a7e6868469e34a356c6efa/apps/prairielearn/src/server.js#L349

Locally, I do NOT have the state as "running" at this moment, but as "stopped" (during reboot) or "uninitialized" during reset. It looks like there are two possible ways to fix it, not sure which is better: either removing the lookup criterion that requires "running" during page navigation, or make sure to set the state as "running" upon reboot or reset. I've tried both of these locally (separately) and they seem to work. I guess I'll suggest a PR with both and maybe someone can comment about whether either, both, or neither is preferable.

**Comment by echuber2** [comment]
I mentioned it in a followup comment on the PR, but while the state query issue seems to be mitigated there for now, the root cause of the thrown error resulting in the crashing behavior might be related to https://github.com/chimurai/http-proxy-middleware/pull/823.

**Comment by nwalters512** [comment]
I am unable to reproduce a crash with the above instructions.

The current state transitions and checks are correct and are part of the state machine that workspaces go through as they are (re)started:

- We do not want to send requests to workspaces that aren't running, hence the `state = 'running'` condition in the hostname query.
- Workspaces are indeed "stopped" after they are rebooted, because there is not a running container until the workspace is successfully placed on a new host and the container subsequently completes its health check.
- Similarly, a workspace is indeed "uninitialized" after it is reset, because it very much needs to be reinitialized - after all, it was just reset!

Because of https://github.com/chimurai/http-proxy-middleware/pull/823, I very much believe that an error like what you're describing is possible, but I don't think we have a good way of fixing that beyond waiting for that PR to land or perhaps forking that package. Regardless, a fix almost certainly won't involve changing the workspaces state machine.

**Comment by echuber2** [comment]
Just to keep everything in one place, I have a separate example here that reproduces the issue more consistently by injecting a delay. (This assumes the fix is defeated/omitted first, but if the injected delay is long enough, even the fix becomes insufficient again.)

https://github.com/echuber2/PrairieLearn/blob/69e0b7199aff7928528b32ef971b042bd9fc9d8e/apps/prairielearn/src/pages/workspace/workspace.ts#L80-L87

**Comment by echuber2** [comment]
Exact steps to reproduce (thanks @tdy for suggestions):

```bash
#!/bin/bash

mkdir -p "$HOME/pl_ag_jobs"
mkdir -p "$HOME/pl_repro"
cd "$HOME/pl_repro"
if [ ! -e workspace_reboot ] ; then
    git clone https://github.com/echuber2/PrairieLearn.git workspace_reboot
fi
cd workspace_reboot
git checkout workspace-reboot-nav-fix-2-repro
sudo docker pull prairielearn/prairielearn
sudo docker pull prairielearn/workspace-jupyterlab-python
sudo docker run -it --rm -p 3000:3000 -v "$PWD/apps:/PrairieLearn/apps" -v "$HOME/pl_ag_jobs:/jobs" -e HOST_JOBS_DIR="$HOME/pl_ag_jobs" -v /var/run/docker.sock:/var/run/docker.sock --entrypoint /bin/bash --add-host=host.docker.internal:172.17.0.1 prairielearn/prairielearn
# Then, in the container terminal:
# NODEMON=true DEV=true /PrairieLearn/docker/init.sh
# Then go to the example course question demo/workspace/jupyterlab,
# start the workspace, and after it loads, click Reboot.
```
