### ISSUE TITLE
Programming solution submission during exam - doesn't auto refresh?

### ISSUE THREAD

**Issue by josh-byster** [PrairieLearn/PrairieLearn#1073]
Hi - this is a minor inconvenience but for the past two programming exams that I've taken, after uploading the files and hitting "grade", the page will say "graded" but will not show the results after running the grading. The feedback doesn't show up until we leave the page and come back to it to see the results. I'm not sure if this is intentional but it has happened on both exams but doesn't happen on multiple choice exams or for daily programming homework. Thank you!

**Comment by nwalters512** [comment]
Thanks for the report Josh! This is definitely not intentional - it should work the same as with your POTDs. Have you heard of this problem from other friends as well? Is this only occurring in the CBTF?

**Comment by josh-byster** [comment]
Hi Nathan - that's a yes to both of your questions. For POTDs, it's always good and consistent about refreshing the page with the results as soon as the problem is graded so we can see our feedback without needing to do anything. In the CBTF, for some reason, both times I've had it where it does not refresh any time I submitted. Note that I have only tried POTDs on High Sierra using Chrome, so it may be an issue with Firefox used by default in the CBTF. So to summarize: it always happened during CBTF programming exams specifically, and never during any other time. I asked a friend of mine and he said he had the exact same bug. Thanks for looking into this! :D

**Comment by mwest1066** [comment]
Huh, that is really weird. I just tried on Firefox locally (on MacOS) and it works fine, so I'm guessing there is something specific to the CBTF (or FF on Linux, but that seems unlikely). Maybe the CBTF firewall is doing something weird with websockets? I guess someone is going to need to go to the CBTF in person to debug this.

**Comment by nwalters512** [comment]
Not CBTF specific - I can reproduce by running CS 225 Programming Exam A linked list question in student mode. I grabbed the following log off of the prod box:

```
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: 2018-03-14T19:00:51.644Z - error:  Async Stacktrace:
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at module.exports.renderPanelsForSubmission (/PrairieLearn/lib/externalGradingSocket.js:50:17)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at question.renderPanelsForSubmission (/PrairieLearn/lib/externalGradingSocket.js:88:13)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at async.parallel (/PrairieLearn/lib/question.js:1430:21)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at ejs.renderFile (/PrairieLearn/lib/question.js:1384:29)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: ReferenceError: /PrairieLearn/pages/partials/questionScorePanel.ejs:45
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: 43|           <textarea class="form-control" rows="5" name="description" placeholder="Describe the issue"></textarea>
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: 44|         </div>
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: >> 45|         <input type="hidden" name="__variant_id" value="<%= variant.id %>">
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: 46|         <input type="hidden" name="__csrf_token" value="<%= __csrf_token %>">
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: 47|         <div class="form-group text-right">
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: 48|           <button class="btn btn-small btn-warning" name="__action" value="report_issue">Report issue
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: variant is not defined
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at eval (eval at compile (/PrairieLearn/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:44:26)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at returnedFn (/PrairieLearn/node_modules/ejs/lib/ejs.js:580:17)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at tryHandleCache (/PrairieLearn/node_modules/ejs/lib/ejs.js:223:34)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at Object.exports.renderFile (/PrairieLearn/node_modules/ejs/lib/ejs.js:437:10)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at async.parallel (/PrairieLearn/lib/question.js:1383:25)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at /PrairieLearn/node_modules/async/dist/async.js:3866:24
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at eachOfArrayLike (/PrairieLearn/node_modules/async/dist/async.js:1055:9)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at eachOf (/PrairieLearn/node_modules/async/dist/async.js:1103:5)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at _parallel (/PrairieLearn/node_modules/async/dist/async.js:3865:5)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at Object.parallelLimit [as parallel] (/PrairieLearn/node_modules/async/dist/async.js:3948:5)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at sqldb.queryOneRow (/PrairieLearn/lib/question.js:1335:19)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at /PrairieLearn/lib/sqldb.js:253:13
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at Query.<anonymous> (/PrairieLearn/lib/sqldb.js:237:21)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at Query.handleReadyForQuery (/PrairieLearn/node_modules/pg/lib/query.js:126:10)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at Connection.<anonymous> (/PrairieLearn/node_modules/pg/lib/client.js:163:19)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at emitOne (events.js:116:13)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at Connection.emit (events.js:211:7)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at Socket.<anonymous> (/PrairieLearn/node_modules/pg/lib/connection.js:118:12)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at emitOne (events.js:116:13)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at Socket.emit (events.js:211:7)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at addChunk (_stream_readable.js:263:12)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at readableAddChunk (_stream_readable.js:250:11)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at Socket.Readable.push (_stream_readable.js:208:10)
Mar 14 19:00:51 ip-10-0-0-204.us-east-2.compute.internal node[19289]: at TCP.onread (net.js:607:20)
```
Seems as though `variant` isn't defined when re-rendering panels to be sent to the client. Going to see if I can reproduce this locally as well - my hope is that I can :)

**Comment by nwalters512** [comment]
I can repro locally - going to dig into this a bit.

**Comment by nwalters512** [comment]
Well, this is embarrassing. This has been an issue since December, but we didn't catch it because we never tested real-time rerendering in student mode with an assessment with issue reporting enabled. #1077 should fix this, and we'll deploy that in the morning. Thanks so much for bringing this to our attention @josh-byster!

**Comment by josh-byster** [comment]
Thanks so much, Nathan, for looking into this and fixing it! We really appreciate it!

**Comment by nwalters512** [comment]
Thanks again for bringing it to our attention! I definitely want the autograder experience to be as smooth as possible 🙂
