### ISSUE TITLE
FlashMessages breaks error page in some contexts

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#10745]
See details about the issue in the comment here https://github.com/PrairieLearn/PrairieLearn/pull/10721#issuecomment-2381291663 (this is where I noticed the issue, although that PR has been summarily closed).

The FlashMessages function in Navbar.html.ts tries to call flash() in some contexts like this:

https://github.com/PrairieLearn/PrairieLearn/blob/337d56b0e285769c8634775f0b25494be251d892/apps/prairielearn/src/components/Navbar.html.ts#L267

where it seems these lines must have failed:

https://github.com/PrairieLearn/PrairieLearn/blob/337d56b0e285769c8634775f0b25494be251d892/packages/flash/src/index.ts#L7

https://github.com/PrairieLearn/PrairieLearn/blob/337d56b0e285769c8634775f0b25494be251d892/packages/flash/src/index.ts#L29-L32

**Comment by echuber2** [comment]
Steps to reproduce in Linux and WSL, using commit https://github.com/echuber2/PrairieLearn/commit/90cc2fcbe588afaa0ccc65601f20532403090cb1

```bash
#!/bin/bash

mkdir -p "$HOME/pl_ag_jobs"
mkdir -p "$HOME/pl_repro"
cd "$HOME/pl_repro"
if [ ! -e flash_bug ] ; then
    git clone https://github.com/echuber2/PrairieLearn.git flash_bug
fi
cd flash_bug
git checkout workspace-flash-bug-repro
sudo docker pull prairielearn/prairielearn
sudo docker pull prairielearn/workspace-jupyterlab-python
sudo docker run -it --rm -p 3000:3000 -v "$PWD/apps:/PrairieLearn/apps" -v "$HOME/pl_ag_jobs:/jobs" -e HOST_JOBS_DIR="$HOME/pl_ag_jobs" -v /var/run/docker.sock:/var/run/docker.sock --entrypoint /bin/bash --add-host=host.docker.internal:172.17.0.1 prairielearn/prairielearn

# Then, in the container terminal:
# NODEMON=true DEV=true /PrairieLearn/docker/init.sh

# Then go to the example course question demo/workspace/jupyterlab,
# start the workspace, and the error message should appear immediately.
```

Error seen in terminal:

```
error: Error page {"id":"K43A2VPF3QXT","msg":"flash bug","referrer":"http://localhost:3000/pl/workspace/1","stack":"Error: flash bug\n    at router (/PrairieLearn/apps/prairielearn/src/server.js:345:13)\n    at Object.getTarget (/PrairieLearn/node_modules/http-proxy-middleware/dist/router.js:14:27)\n    at HttpProxyMiddleware.applyRouter (/PrairieLearn/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:110:42)\n    at HttpProxyMiddleware.prepareProxyRequest (/PrairieLearn/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:97:24)\n    at HttpProxyMiddleware.middleware (/PrairieLearn/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:21:59)\n    at patched (/PrairieLearn/node_modules/@opentelemetry/instrumentation-express/src/instrumentation.ts:198:27)\n    at Layer.handle [as handle_request] (/PrairieLearn/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/PrairieLearn/node_modules/express/lib/router/index.js:328:13)\n    at /PrairieLearn/node_modules/express/lib/router/index.js:286:9\n    at param (/PrairieLearn/node_modules/express/lib/router/index.js:365:14)\n    at param (/PrairieLearn/node_modules/express/lib/router/index.js:376:14)\n    at Function.process_params (/PrairieLearn/node_modules/express/lib/router/index.js:421:3)\n    at next (/PrairieLearn/node_modules/express/lib/router/index.js:280:10)\n    at <anonymous> (/PrairieLearn/apps/prairielearn/src/server.js:415:7)\n    at patched (/PrairieLearn/node_modules/@opentelemetry/instrumentation-express/src/instrumentation.ts:198:27)\n    at Layer.handle [as handle_request] (/PrairieLearn/node_modules/express/lib/router/layer.js:95:5)","status":500}
Error: flash() must be called within a request
    at flash (/PrairieLearn/packages/flash/src/index.ts:31:11)
    at FlashMessages (/PrairieLearn/apps/prairielearn/src/components/Navbar.html.ts:267:9)
    at Navbar (/PrairieLearn/apps/prairielearn/src/components/Navbar.html.ts:101:64)
    at ErrorPage (/PrairieLearn/apps/prairielearn/src/pages/error/error.html.ts:52:11)
    at default (/PrairieLearn/apps/prairielearn/src/pages/error/error.ts:38:5)
    at Layer.handle_error (/PrairieLearn/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/PrairieLearn/node_modules/express/lib/router/index.js:326:13)
    at /PrairieLearn/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/PrairieLearn/node_modules/express/lib/router/index.js:346:12)
    at next (/PrairieLearn/node_modules/express/lib/router/index.js:280:10)
    at sentryErrorMiddleware (/PrairieLearn/node_modules/@sentry/node/src/integrations/tracing/express.ts:127:60)
    at Layer.handle_error (/PrairieLearn/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/PrairieLearn/node_modules/express/lib/router/index.js:326:13)
    at /PrairieLearn/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/PrairieLearn/node_modules/express/lib/router/index.js:346:12)
    at next (/PrairieLearn/node_modules/express/lib/router/index.js:280:10)
```

The second half, starting from "Error: flash() must be called within a request", also appears in the web view.

**Comment by nwalters512** [comment]
@echuber2 can you test the changes from #10745 and confirm if this fixes this issue for you?

**Comment by echuber2** [comment]
It looks like this does fix the flash issue in Linux and WSL. I can throw an error in the middleware and have it displayed as a normal error:

![Image](https://github.com/user-attachments/assets/232c0ae9-3b09-478f-b5ed-b665b90447e5)

I was hoping this would also help with https://github.com/PrairieLearn/PrairieLearn/issues/10716 since I first noticed the issue while debugging that, but it looks like it doesn't. (I.e., _some_ errors thrown in that middleware crash the whole server.) So, I guess they are truly separate issues.

**Comment by nwalters512** [comment]
Yeah, from what I can tell, the error in #10716 specifically happens during a websocket upgrade request. `router` errors for "normal" requests don't crash the server and render our usual error page, and rendering that error page is what #10745 fixes.
