### ISSUE TITLE
"Student View" access denied during local Docker-based question development

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#10762]
Steps to reproduce:

- Launch PL docker container. My command is:

```
docker run -it --rm --pull=always -p 3000:3000 \
    --platform linux/x86_64 \
    -v "/pl-ubc-cpsc210:/course" `# Replace the path with your course directory` \
    -v "$HOME/tmp/pl_ag_jobs:/jobs" `# Map jobs directory into /jobs` \
    -e HOST_JOBS_DIR="$HOME/tmp/pl_ag_jobs" \
    -v /var/run/docker.sock:/var/run/docker.sock `# Mount docker into itself so container can spawn others` \
    prairielearn/prairielearn
```

- Click "Load from Disk" to load course repos
- Click "Student View"
- Get error message:

```
Error: Access denied
    at default (file:///PrairieLearn/apps/prairielearn/dist/middlewares/authzHasCourseInstanceAccess.js:19:21)
    at patched (/PrairieLearn/node_modules/@opentelemetry/instrumentation-express/build/src/instrumentation.js:140:37)
    at Layer.handle [as handle_request] (/PrairieLearn/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/PrairieLearn/node_modules/express/lib/router/index.js:328:13)
    at /PrairieLearn/node_modules/express/lib/router/index.js:286:9
    at param (/PrairieLearn/node_modules/express/lib/router/index.js:365:14)
    at param (/PrairieLearn/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/PrairieLearn/node_modules/express/lib/router/index.js:421:3)
    at next (/PrairieLearn/node_modules/express/lib/router/index.js:280:10)
    at file:///PrairieLearn/apps/prairielearn/dist/server.js:549:13
    at patched (/PrairieLearn/node_modules/@opentelemetry/instrumentation-express/build/src/instrumentation.js:140:37)
    at Layer.handle [as handle_request] (/PrairieLearn/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/PrairieLearn/node_modules/express/lib/router/index.js:328:13)
    at /PrairieLearn/node_modules/express/lib/router/index.js:286:9
    at param (/PrairieLearn/node_modules/express/lib/router/index.js:365:14)
    at param (/PrairieLearn/node_modules/express/lib/router/index.js:376:14)
```

Gif that captures the problem:

![Image](https://github.com/user-attachments/assets/33716d60-22b6-4f64-9ceb-71cd3f6de550)

**Comment by nwalters512** [comment]
This is behaving exactly as it should. Your course instance is configured to filter access based on institution:

```json
    "allowAccess": [
      {
        "institution": "ubc.ca",
        "startDate": "2024-09-03T00:00:01",
        "endDate": "2024-12-21T21:00:00"
      }
    ],
``` 

That institution doesn't exist in local development, so it's impossible for any user to satisfy that requirement, and thus access is denied.

You have two options:

- Use the "student view without access restrictions". This is exactly what it's there for.
- Remove the institution restriction. Course instance access is by default limited to users that belong to the same institution as the course. Since this course belongs to the UBC institution in production environments, access is by default limited to UBC users, so the restriction in your JSON is strictly redundant.

Either way, this is not an issue with PrairieLearn, so I'm closing this issue.

**Comment by firasm** [comment]
Ahhh - got it! Thanks
