### ISSUE TITLE
Handle null bytes in grading results

### ISSUE THREAD

**Issue by nwalters512** [PrairieLearn/PrairieLearn#1270]
Seems like a reincarnation of #931. Stack trace:

```
Sep 20 18:36:12 ip-10-0-0-204.us-east-2.compute.internal node[951]: 2018-09-20T18:36:12.325Z - error: processGradingResult: error message=unsupported Unicode escape sequence, stack=Async Stacktrace:
Sep 20 18:36:12 ip-10-0-0-204.us-east-2.compute.internal node[951]: at async.series (/PrairieLearn/lib/assessment.js:357:17)
Sep 20 18:36:12 ip-10-0-0-204.us-east-2.compute.internal node[951]: at sqldb.call (/PrairieLearn/lib/assessment.js:352:25)
Sep 20 18:36:12 ip-10-0-0-204.us-east-2.compute.internal node[951]: at /PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:306:17
Sep 20 18:36:12 ip-10-0-0-204.us-east-2.compute.internal node[951]: at handleError (/PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:255:17)
Sep 20 18:36:12 ip-10-0-0-204.us-east-2.compute.internal node[951]: error: unsupported Unicode escape sequence
Sep 20 18:36:12 ip-10-0-0-204.us-east-2.compute.internal node[951]: at Connection.parseE (/PrairieLearn/node_modules/pg/lib/connection.js:553:11)
Sep 20 18:36:12 ip-10-0-0-204.us-east-2.compute.internal node[951]: at Connection.parseMessage (/PrairieLearn/node_modules/pg/lib/connection.js:378:19)
Sep 20 18:36:12 ip-10-0-0-204.us-east-2.compute.internal node[951]: at Socket.<anonymous> (/PrairieLearn/node_modules/pg/lib/connection.js:119:22)
Sep 20 18:36:12 ip-10-0-0-204.us-east-2.compute.internal node[951]: at Socket.emit (events.js:182:13)
Sep 20 18:36:12 ip-10-0-0-204.us-east-2.compute.internal node[951]: at Socket.EventEmitter.emit (domain.js:442:20)
Sep 20 18:36:12 ip-10-0-0-204.us-east-2.compute.internal node[951]: at addChunk (_stream_readable.js:283:12)
Sep 20 18:36:12 ip-10-0-0-204.us-east-2.compute.internal node[951]: at readableAddChunk (_stream_readable.js:264:11)
Sep 20 18:36:12 ip-10-0-0-204.us-east-2.compute.internal node[951]: at Socket.Readable.push (_stream_readable.js:219:10)
Sep 20 18:36:12 ip-10-0-0-204.us-east-2.compute.internal node[951]: at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17), data={"sqlError":{"name":"error","length":206,"severity":"ERROR","code":"22P05","detail":"\\u0000 cannot be converted to text.","where":"JSON data, line 1: ...\",\"diff\":\"1s\"},\"output\":[{\"type\":\"stdout\",\"data\":...","file":"json.c","line":"882","routine":"json_lex_string","message":"unsupported Unicode escape sequence"},"sql":"SELECT * FROM grading_jobs_process_external($1,$2,$3,$4,$5,$6)","sqlParams":[8315119,0,{"start_time":"2018-09-20T18:36:05.158Z","end_time":"2018-09-20T18:36:12.073Z","succeeded":true,"results":{"succeeded":true,"score":0,"timestamps":{"diff":"3ms","config":"7ms","copy":"10ms","total":"6s"},"configuration":{"name":"Quiz","version":"1.0.0","showStreams":false,"grading":{"timeout":"PT20S","run":"./gradlew grade -Pgrade.capture -Pgrade.secure --no-daemon --console=plain -q","ignoreOutput":["^java.security.policy: error parsing file.*","^Unable to initialize policy entry:.*","^.*?expected \\[\\;\\], found \\[priority\\]$","^WARNING: An illegal reflective access operation has occurred.*","^WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass.*","^WARNING: Please consider reporting this to the maintainers.*","^WARNING: Use --illegal-access=warn to enable warnings.*","^WARNING: All illegal access operations will be denied in a future release.*","^The TaskInternal.*","^Deprecated Gradle features were used in this build.*","^See https://docs.gradle.org.*"]},"scoring":{"min":0,"max":100,"selectors":["test"]},"files":["Question"],"secure":"config/security.policy","reporting":{"file":"/base/grade.json"},"checkstyle":{"files":["Question"],"stop":true},"testNG":[{"suite":"QuestionTest","points":100,"wrong":0}],"secureRun":true},"tests":[{"name":"checkstyle","max_points":0,"points":0,"message":"no checkstyle errors were found"},{"name":"QuestionTest","message":"QuestionTest caused an error","points":0,"max_points":100,"output":"java.lang.StringIndexOutOfBoundsException: String index out of range: 39\n\tat java.base/java.lang.StringLatin1.charAt(StringLatin1.java:44)\n\tat java.base/java.lang.String.charAt(String.java:692)\n\tat Question.reverseString(Question.java:11)\n\tat QuestionTest.testReverseString(QuestionTest.java:28)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:564)\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)\n\tat org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)\n\tat org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:844)"}],"testResults":{"times":{"start":"2018-09-20T18:36:10.589Z","end":"2018-09-20T18:36:11.710Z","diff":"1s"},"output":[{"type":"stdout","data":"\\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000","delta":"PT0.787S"},{"type":"stdout","data":"","delta":"PT1.121S"}],"timeout":false,"succeeded":false},"output":"\\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"},"job_id":8315119,"received_time":"2018-09-20T18:36:04.198Z"},"2018-09-20T18:36:04.198Z","2018-09-20T18:36:05.158Z","2018-09-20T18:36:12.073Z"]}
```

**Comment by mwest1066** [comment]
Another occurrence of this:
```
{"grading_job_id":17576947,"jobId":17576947,"event":"grading_result","data":{"start_time":"2019-09-26T20:09:03.076Z","end_time":"2019-09-26T20:09:03.543Z","succeeded":true,"results":{"tests":[{"name":"Test 0","max_points":100,"points":0,"output":"EXPECTED: Z Q O [ M J R K c e\nGOT: Z Q O [ M \\u0000 \u0000 \u0000 c e"}],"succeeded":true,"score":0},"job_id":17576947,"received_time":"2019-09-26T20:09:02.129Z"},"level":"verbose","message":"Processing external grading job result message","timestamp":"2019-09-26T20:09:03.792Z"}
{"message":"processGradingResult: errorunsupported Unicode escape sequence","stack":"Async Stacktrace:\n    at /PrairieLearn/lib/assessment.js:324:17\n    at /PrairieLearn/lib/assessment.js:309:25\n    at /PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:503:13\n    at handleError (/PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:412:13)\n\nerror: unsupported Unicode escape sequence\n    at Connection.parseE (/PrairieLearn/node_modules/@prairielearn/prairielib/node_modules/pg/lib/connection.js:604:11)\n    at Connection.parseMessage (/PrairieLearn/node_modules/@prairielearn/prairielib/node_modules/pg/lib/connection.js:401:19)\n    at Socket.<anonymous> (/PrairieLearn/node_modules/@prairielearn/prairielib/node_modules/pg/lib/connection.js:121:22)\n    at Socket.emit (events.js:203:13)\n    at Socket.EventEmitter.emit (domain.js:471:20)\n    at addChunk (_stream_readable.js:294:12)\n    at readableAddChunk (_stream_readable.js:275:11)\n    at Socket.Readable.push (_stream_readable.js:210:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)","data":"{\"sqlError\":{\"name\":\"error\",\"length\":206,\"severity\":\"ERROR\",\"code\":\"22P05\",\"detail\":\"\\\\u0000 cannot be converted to text.\",\"where\":\"JSON data, line 1: ...e\\\":\\\"Test 0\\\",\\\"max_points\\\":100,\\\"points\\\":0,\\\"output\\\":...\",\"file\":\"json.c\",\"line\":\"882\",\"routine\":\"json_lex_string\",\"message\":\"unsupported Unicode escape sequence\"},\"sql\":\"SELECT * FROM grading_jobs_process_external($1,$2,$3,$4,$5,$6)\",\"sqlParams\":[17576947,0,{\"start_time\":\"2019-09-26T20:09:03.076Z\",\"end_time\":\"2019-09-26T20:09:03.543Z\",\"succeeded\":true,\"results\":{\"tests\":[{\"name\":\"Test 0\",\"max_points\":100,\"points\":0,\"output\":\"EXPECTED: Z Q O [ M J R K c e\\nGOT: Z Q O [ M \\\\u0000 \\u0000 \\u0000 c e\"}],\"succeeded\":true,\"score\":0},\"job_id\":17576947,\"received_time\":\"2019-09-26T20:09:02.129Z\"},\"2019-09-26T20:09:02.129Z\",\"2019-09-26T20:09:03.076Z\",\"2019-09-26T20:09:03.543Z\"]}","level":"error","timestamp":"2019-09-26T20:09:03.800Z"}
```

This is causing us to occasionally drop a grading job.
