### ISSUE TITLE
Containerized PL with external grading cannot get git hash for exampleCourse

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#1339]
Steps to reproduce:

1. Run PL locally in a container, with external grading active. I run:
```
docker run -it --rm -p 3000:3000 -v /Users/mwest/pl_ag_jobs:/jobs -e HOST_JOBS_DIR=/Users/mwest/pl_ag_jobs -v /var/run/docker.sock:/var/run/docker.sock prairielearn/prairielearn
```

2. Click "Load from disk" inside PL, and go to the example course, then Questions, then `fibonacciEditor`.

3. Edit the code to replace `pass` with `return 1` and click "Grade".

4. Grading should occur correctly (giving 25% credit), but in the terminal window running docker we have:
```
2018-10-17T14:12:09.058Z - info: container> [run] autograder completed
2018-10-17T14:12:09.068Z - info: container> [run] copied results
2018-10-17T14:12:09.313Z - info: Constructing results object
2018-10-17T14:12:09.317Z - info: parsing!
2018-10-17T14:12:09.378Z - error:  message=Could not get git status; exited with code 128, stack=Async Stacktrace:
    at module.exports._getCacheKey (/PrairieLearn/question-servers/freeform.js:852:21)
    at courseUtil.getOrUpdateCourseCommitHash (/PrairieLearn/question-servers/freeform.js:752:17)
    at module.exports.updateCourseCommitHash (/PrairieLearn/lib/courseUtil.js:54:17)
    at getCommitHash (/PrairieLearn/lib/courseUtil.js:28:13)

Error: Could not get git status; exited with code 128
    at exec (/PrairieLearn/lib/courseUtil.js:14:22)
```

I don't understand why we execute https://github.com/PrairieLearn/PrairieLearn/blob/master/question-servers/freeform.js#L852. We should be detecting that `locals.devMode == true` at https://github.com/PrairieLearn/PrairieLearn/blob/master/question-servers/freeform.js#L843 and never calling `_getCacheKey()`. What am I missing here?

**Comment by mwest1066** [comment]
Just re-tested. Works now.
