### ISSUE TITLE
rotateObject example question is broken

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#1386]
```
Traceback (most recent call last):
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 158, in <module>
    worker_loop()
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 105, in worker_loop
    val = method(*args)
  File "<string>", line 34, in prepare
  File "/PrairieLearn/question-servers/freeformPythonLib/prairielearn.py", line 147, in check_attribs
    raise Exception('Required attribute "%s" missing' % name)
Exception: Required attribute "answer_name" missing
Traceback (most recent call last):
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 170, in <module>
    raise Exception('worker process exited unexpectedly with status %d' % status)
Exception: worker process exited unexpectedly with status 256
```

**Comment by coatless** [comment]
Also the case w.r.t `correct-answer` since in **server.py** only `data["correct_answers"][answers-name]` works.

**Comment by nwalters512** [comment]
There is no longer a `rotateObject` question in the example course - closing this!
