### ISSUE TITLE
Daily cron job timeout

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#1635]
We had a previous case of transaction timeouts in #1623, which we fixed in #1629 

Now we’ve still got transaction timeouts on the daily cron jobs, but only in production (not for `pl-dev`).

**Comment by mwest1066** [comment]
I didn’t expect to use the new UUID-tagging of cron jobs (from #1628) quite so soon, but I’m glad we had it. Here’s the offending cron job:

```
{"cronUuid":"860c50aa-559e-4d83-abb6-983e503d4cf1","level":"verbose","message":"cron: jobs starting","timestamp":"2019-08-08T08:00:00.000Z"}
{"cronUuid":"860c50aa-559e-4d83-abb6-983e503d4cf1","level":"verbose","message":"cron: sendExternalGraderStats acquired lock","timestamp":"2019-08-08T08:00:00.008Z"}{"cronUuid":"860c50aa-559e-4d83-abb6-983e503d4cf1","level":"verbose","message":"cron: sendExternalGraderStats job was not recently run","timestamp":"2019-08-08T08:00:00.015Z"}{"cronUuid":"860c50aa-559e-4d83-abb6-983e503d4cf1","level":"verbose","message":"cron: sendExternalGraderStats updated date","timestamp":"2019-08-08T08:00:00.020Z"}{"cronUuid":"860c50aa-559e-4d83-abb6-983e503d4cf1","level":"verbose","message":"cron: starting sendExternalGraderStats","timestamp":"2019-08-08T08:00:00.023Z"}{"cronUuid":"860c50aa-559e-4d83-abb6-983e503d4cf1","elapsedTimeMS":173,"level":"verbose","message":"cron: sendExternalGraderStats success","timestamp":"2019-08-08T08:00:00.198Z"}
{"cronUuid":"860c50aa-559e-4d83-abb6-983e503d4cf1","level":"verbose","message":"cron: sendExternalGraderStats released lock","timestamp":"2019-08-08T08:00:00.203Z"}
{"cronUuid":"860c50aa-559e-4d83-abb6-983e503d4cf1","level":"verbose","message":"cron: sendExternalGraderDeadLetters acquired lock","timestamp":"2019-08-08T08:00:00.210Z"}
{"cronUuid":"860c50aa-559e-4d83-abb6-983e503d4cf1","level":"verbose","message":"cron: sendExternalGraderDeadLetters job was not recently run","timestamp":"2019-08-08T08:00:00.214Z"}
{"cronUuid":"860c50aa-559e-4d83-abb6-983e503d4cf1","level":"verbose","message":"cron: sendExternalGraderDeadLetters updated date","timestamp":"2019-08-08T08:00:00.218Z"}
{"cronUuid":"860c50aa-559e-4d83-abb6-983e503d4cf1","level":"verbose","message":"cron: starting sendExternalGraderDeadLetters","timestamp":"2019-08-08T08:00:00.221Z"}{"cronUuid":"860c50aa-559e-4d83-abb6-983e503d4cf1","elapsedTimeMS":40304,"level":"verbose","message":"cron: sendExternalGraderDeadLetters success","timestamp":"2019-08-08T08:00:40.527Z"}{"cronUuid":"860c50aa-559e-4d83-abb6-983e503d4cf1","level":"verbose","message":"cron: sendExternalGraderDeadLetters released lock","timestamp":"2019-08-08T08:00:40.531Z"}{"cronUuid":"860c50aa-559e-4d83-abb6-983e503d4cf1","level":"verbose","message":"cron: calculateAssessmentQuestionStats acquired lock","timestamp":"2019-08-08T08:00:40.538Z"}{"cronUuid":"860c50aa-559e-4d83-abb6-983e503d4cf1","level":"verbose","message":"cron: calculateAssessmentQuestionStats job was not recently run","timestamp":"2019-08-08T08:00:40.543Z"}
{"cronUuid":"860c50aa-559e-4d83-abb6-983e503d4cf1","level":"verbose","message":"cron: calculateAssessmentQuestionStats updated date","timestamp":"2019-08-08T08:00:40.548Z"}
{"cronUuid":"860c50aa-559e-4d83-abb6-983e503d4cf1","level":"verbose","message":"cron: starting calculateAssessmentQuestionStats","timestamp":"2019-08-08T08:00:40.550Z"}
```

**Comment by mwest1066** [comment]
It looks like `calculateAssessmentQuestionStats` is just taking too long. Looking at the logs from last week we have this each day:

```
{"message":"cron: calculateAssessmentQuestionStats acquired lock","level":"verbose","timestamp":"2019-07-30T08:00:40.529Z"}
{"message":"cron: calculateAssessmentQuestionStats job was not recently run","level":"verbose","timestamp":"2019-07-30T08:00:40.534Z"}
{"message":"cron: calculateAssessmentQuestionStats updated date","level":"verbose","timestamp":"2019-07-30T08:00:40.538Z"}
{"message":"cron: starting calculateAssessmentQuestionStats","level":"verbose","timestamp":"2019-07-30T08:00:40.540Z"}
{"message":"cron: calculateAssessmentQuestionStats failure: Error: Client has encountered a connection error and is not queryable","stack":"Async Stacktrace:\n    at /PrairieLearn/cron/index.js:180:21\n    at /PrairieLearn/cron/index.js:211:29\n    at /PrairieLearn/lib/named-locks.js:53:17\n    at /PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:231:28\n    at Query.callback (/PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:140:21)\n\nError: Client has encountered a connection error and is not queryable\n    at /PrairieLearn/node_modules/pg/lib/client.js:464:25\n    at processTicksAndRejections (internal/process/task_queues.js:75:11)","data":"{\"sqlError\":{\"message\":\"Client has encountered a connection error and is not queryable\"},\"sql\":\"COMMIT\",\"sqlParams\":[]}","level":"error","timestamp":"2019-07-30T08:26:04.508Z"}
```

**Comment by mwest1066** [comment]
I’m not sure what `Error: Client has encountered a connection error and is not queryable` means, but it looks like we’ve turned some kind of soft error into a hard transaction timeout (something in the big deploy on the weekend caused this, but I’m not sure what). It looks like `calculateAssessmentQuestionStats` has not been successfully running for some time.

**Comment by mwest1066** [comment]
Note that it’s not a big problem that `calculateAssessmentQuestionStats` hasn’t been running — instructors can always click the “calculate stats” button to update the stats themselves. This cron job is just a nice-to-have thing to keep stats up to date automatically. Because it’s the second-to-last daily cron job, it does mean that it’s been blocking `calculateAssessmentMode` (also just for statistics updating).

**Comment by trombonekenny** [comment]
Reminder poke from @mfsilva22 in today's Growing PL meeting
