### ISSUE TITLE
File download error in base64 decode

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2069]
Reported by @bowmnath 

Error is `invalid symbol ":" while decoding base64 sequence`

Error is in `BLOCK assessment_instance_files` at https://github.com/PrairieLearn/PrairieLearn/blob/master/pages/instructorAssessmentDownloads/instructorAssessmentDownloads.sql#L121

Full error log:
```
{"msg":"invalid symbol \":\" while decoding base64 sequence","id":"K7KFH626UZYX","status":500,"stack":"Async Stacktrace:\n    at /PrairieLearn/pages/instructorAssessmentDownloads/instructorAssessmentDownloads.js:238:17\n    at /PrairieLearn/lib/paginate.js:49:17\n    at /PrairieLearn/lib/paginate.js:39:21\n    at handleError (/PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:418:13)\n\nerror: invalid symbol \":\" while decoding base64 sequence\n    at Connection.parseE (/PrairieLearn/node_modules/@prairielearn/prairielib/node_modules/pg/lib/connection.js:604:13)\n    at Connection.parseMessage (/PrairieLearn/node_modules/@prairielearn/prairielib/node_modules/pg/lib/connection.js:403:19)\n    at Socket.<anonymous> (/PrairieLearn/node_modules/@prairielearn/prairielib/node_modules/pg/lib/connection.js:123:22)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at addChunk (_stream_readable.js:309:12)\n    at readableAddChunk (_stream_readable.js:290:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)","data":"{\"sqlError\":{\"name\":\"error\",\"length\":110,\"severity\":\"ERROR\",\"code\":\"22023\",\"file\":\"encode.c\",\"line\":\"307\",\"routine\":\"pg_base64_decode\",\"message\":\"invalid symbol \\\":\\\" while decoding base64 sequence\"},\"sql\":\"-- BLOCK assessment_instance_files\\nWITH all_submissions_with_files AS (\\n    SELECT\\n        s.id AS submission_id,\\n        u.uid,\\n        ai.number AS assessment_instance_number,\\n        q.qid,\\n        v.number AS variant_number,\\n        v.params,\\n        s.date,\\n        s.submitted_answer,\\n        row_number() OVER (PARTITION BY v.id ORDER BY s.date) AS submission_number,\\n        (row_number() OVER (PARTITION BY v.id ORDER BY s.date DESC, s.id DESC)) = 1 AS final_submission_per_variant,\\n        (row_number() OVER (PARTITION BY v.id ORDER BY s.score DESC NULLS LAST, s.date DESC, s.id DESC)) = 1 AS best_submission_per_variant\\n    FROM\\n        assessments AS a\\n        JOIN assessment_instances AS ai ON (ai.assessment_id = a.id)\\n        JOIN users AS u ON (u.user_id = ai.user_id)\\n        JOIN instance_questions AS iq ON (iq.assessment_instance_id = ai.id)\\n        JOIN assessment_questions AS aq ON (aq.id = iq.assessment_question_id)\\n        JOIN questions AS q ON (q.id = aq.question_id)\\n        JOIN variants AS v ON (v.instance_question_id = iq.id)\\n        JOIN submissions AS s ON (s.variant_id = v.id)\\n    WHERE\\n        a.id = $assessment_id\\n        AND (\\n            (v.params ? 'fileName' AND s.submitted_answer ? 'fileData')\\n            OR (s.submitted_answer ? '_files')\\n        )\\n),\\nuse_submissions_with_files AS (\\n    SELECT *\\n    FROM all_submissions_with_files\\n    WHERE\\n        $include_all\\n        OR ($include_final AND final_submission_per_variant)\\n        OR ($include_best AND best_submission_per_variant)\\n),\\nall_files AS (\\n    SELECT\\n        uid,\\n        assessment_instance_number,\\n        qid,\\n        variant_number,\\n        date,\\n        submission_number,\\n        (CASE\\n            WHEN submitted_answer ? 'fileData' THEN params->>'fileName'\\n            WHEN submitted_answer ? '_files' THEN f.file->>'name'\\n        END) as filename,\\n        (CASE\\n            WHEN submitted_answer ? 'fileData' THEN submitted_answer->>'fileData'\\n            WHEN submitted_answer ? '_files' THEN f.file->>'contents'\\n        END) as contents\\n    FROM\\n        use_submissions_with_files AS s\\n        LEFT JOIN (\\n            SELECT\\n                submission_id AS id,\\n                jsonb_array_elements(submitted_answer->'_files') AS file\\n            FROM use_submissions_with_files\\n            WHERE submitted_answer ? '_files'\\n        ) f ON (f.id = submission_id)\\n)\\nSELECT\\n    (\\n        uid\\n        || '_' || assessment_instance_number\\n        || '_' || qid\\n        || '_' || variant_number\\n        || '_' || submission_number\\n        || '_' || filename\\n    ) AS filename,\\n    decode(contents, 'base64') AS contents\\nFROM\\n    all_files\\nWHERE\\n    filename IS NOT NULL\\n    AND contents IS NOT NULL\\nORDER BY\\n    uid, assessment_instance_number, qid, variant_number, date\\nLIMIT\\n    $limit\\nOFFSET\\n    $offset;\\n\",\"sqlParams\":{\"assessment_id\":1167445,\"limit\":100,\"include_all\":false,\"include_final\":false,\"include_best\":true,\"offset\":0}}","referrer":"https://prairielearn.engr.illinois.edu/pl/course_instance/51938/instructor/assessment/1167445/downloads","response_id":"7d7f2731-0531-423f-ae29-070a2db97d51","level":"error","message":"Error page","timestamp":"2020-02-10T14:50:47.291Z"}
```

**Comment by mwest1066** [comment]
The bad submission has `id = 24768371` and:
```
raw_submitted_answer = {"out_expr": "~Y+XY+Y~Z", "_file_upload_bcf0d4e909ed70dc513a63138a7c11ff69458556": "[{\"name\":\"karnaugh-map.pdf\",\"contents\":\"data:\"}]"}
```
