### ISSUE TITLE
Missing question id

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2091]
```
Feb 24 23:46:19 ip-10-0-0-204 node: /PrairieLearn/lib/question.js:873
Feb 24 23:46:19 ip-10-0-0-204 node: this._ensureVariantWithClient(client, question.id, instance_question_id, authn_user_id,
Feb 24 23:46:19 ip-10-0-0-204 node: ^
Feb 24 23:46:19 ip-10-0-0-204 node: TypeError: Cannot read property 'id' of undefined
Feb 24 23:46:19 ip-10-0-0-204 node: at /PrairieLearn/lib/question.js:873:140
Feb 24 23:46:19 ip-10-0-0-204 node: at /PrairieLearn/node_modules/async/dist/async.js:2953:28
Feb 24 23:46:19 ip-10-0-0-204 node: at replenish (/PrairieLearn/node_modules/async/dist/async.js:445:21)
Feb 24 23:46:19 ip-10-0-0-204 node: at /PrairieLearn/node_modules/async/dist/async.js:450:13
Feb 24 23:46:19 ip-10-0-0-204 node: at eachOfLimit$1 (/PrairieLearn/node_modules/async/dist/async.js:476:34)
Feb 24 23:46:19 ip-10-0-0-204 node: at awaitable(eachOfLimit$1) (/PrairieLearn/node_modules/async/dist/async.js:208:32)
Feb 24 23:46:19 ip-10-0-0-204 node: at eachOfSeries (/PrairieLearn/node_modules/async/dist/async.js:663:16)
Feb 24 23:46:19 ip-10-0-0-204 node: at awaitable(eachOfSeries) (/PrairieLearn/node_modules/async/dist/async.js:208:32)
Feb 24 23:46:19 ip-10-0-0-204 node: at /PrairieLearn/node_modules/async/dist/async.js:2952:9
Feb 24 23:46:19 ip-10-0-0-204 node: at awaitable() (/PrairieLearn/node_modules/async/dist/async.js:208:32)
Feb 24 23:46:19 ip-10-0-0-204 node: at Object.series (/PrairieLearn/node_modules/async/dist/async.js:3962:16)
Feb 24 23:46:19 ip-10-0-0-204 node: at /PrairieLearn/lib/question.js:868:19
```

**Comment by nwalters512** [comment]
We haven't seen this in Sentry at all; I'm going to assume this is no longer a problem.
