### ISSUE TITLE
Recurring idle-in-transaction timeout errors

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2396]
When running with multiple servers, sometimes one of them gets stuck in a loop printing out:

```
{"name":"error","length":122,"severity":"FATAL","code":"25P03","file":"postgres.c","line":"3080","routine":"ProcessInterrupts","level":"error","message":"idle client errorterminating connection due to idle-in-transaction timeout","stack":"error: terminating connection due to idle-in-transaction timeout\n    at Connection.parseE (/PrairieLearn/node_modules/pg/lib/connection.js:600:48)\n    at Connection.parseMessage (/PrairieLearn/node_modules/pg/lib/connection.js:399:19)\n    at Socket.<anonymous> (/PrairieLearn/node_modules/pg/lib/connection.js:115:22)\n    at Socket.emit (events.js:223:5)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at addChunk (_stream_readable.js:309:12)\n    at readableAddChunk (_stream_readable.js:290:11)\n    at Socket.Readable.push (_stream_readable.js:224:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)","timestamp":"2020-04-19T03:11:11.035Z"}
{"level":"error","message":"idle client errorConnection terminated unexpectedly","stack":"Error: Connection terminated unexpectedly\n    at Connection.<anonymous> (/PrairieLearn/node_modules/pg/lib/client.js:264:9)\n    at Object.onceWrapper (events.js:312:28)\n    at Connection.emit (events.js:223:5)\n    at Connection.EventEmitter.emit (domain.js:475:20)\n    at Socket.<anonymous> (/PrairieLearn/node_modules/pg/lib/connection.js:125:10)\n    at Socket.emit (events.js:228:7)\n    at Socket.EventEmitter.emit (domain.js:475:20)\n    at endReadableNT (_stream_readable.js:1185:12)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)","timestamp":"2020-04-19T03:11:11.035Z"}
```

After it starts doing this it prints these errors every couple of seconds, and is unable to service any requests.

**Comment by mwest1066** [comment]
Fixed by #2395 and #2403
