### ISSUE TITLE
Incorrect error handling in authCallbackLti causes server crash

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2660]
The error-handling is wrong at: https://github.com/PrairieLearn/PrairieLearn/blob/4a0a4a2226abcaa98946d08b0282019ba49b9fdd/pages/authCallbackLti/authCallbackLti.js#L65

If there is a cache error then we will correctly call `next()` with the error, but the `return` statement will only exit out of the immediately-enclosing anonymous function and we will continue to execute the code until https://github.com/PrairieLearn/PrairieLearn/blob/4a0a4a2226abcaa98946d08b0282019ba49b9fdd/pages/authCallbackLti/authCallbackLti.js#L113

At this point we will try and set a cookie, which will fail with the error message `Cannot set headers after they are sent to the client`. At this point it will throw an uncaught exception which will crash the server.

The root problem here is that we are calling an async function with a callback (the call to `cache.get()`) but we are not nesting later code but instead we are treating this as a synchronous call. In fact all of the later code should be nested inside the callback to `cache.get()`).

The full error message is:
```
Jul  1 17:13:01 ip-10-0-0-204 node: #033[31merror#033[39m: Error page {"msg":"EXECABORT Transaction discarded because of previous errors.","id":"6N3P41EHW8P9","status":500,"stack":"Async Stacktrace:\n    at /PrairieLearn/pages/authCallbackLti/authCallbackLti.js:65:17\n\nReplyError: EXECABORT Transaction discarded because of previous errors.\n    at parseError (/PrairieLearn/node_modules/redis-parser/lib/parser.js:179:12)\n    at parseType (/PrairieLearn/node_modules/redis-parser/lib/parser.js:302:14)","referrer":"https://www.coursera.org/learn/cs421/gradedLti/GNzuu/mp-4-parsing","response_id":"2e2f577a-8137-49b3-b681-a7ffc6cf6c7d"}
Jul  1 17:13:01 ip-10-0-0-204 node: _http_outgoing.js:518
Jul  1 17:13:01 ip-10-0-0-204 node: throw new ERR_HTTP_HEADERS_SENT('set');
Jul  1 17:13:01 ip-10-0-0-204 node: ^
Jul  1 17:13:01 ip-10-0-0-204 node: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
Jul  1 17:13:01 ip-10-0-0-204 node: at ServerResponse.setHeader (_http_outgoing.js:518:11)
Jul  1 17:13:01 ip-10-0-0-204 node: at ServerResponse.header (/PrairieLearn/node_modules/express/lib/response.js:771:10)
Jul  1 17:13:01 ip-10-0-0-204 node: at ServerResponse.append (/PrairieLearn/node_modules/express/lib/response.js:732:15)
Jul  1 17:13:01 ip-10-0-0-204 node: at ServerResponse.res.cookie (/PrairieLearn/node_modules/express/lib/response.js:857:8)
Jul  1 17:13:01 ip-10-0-0-204 node: at /PrairieLearn/pages/authCallbackLti/authCallbackLti.js:113:17
Jul  1 17:13:01 ip-10-0-0-204 node: at /PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:511:9
Jul  1 17:13:01 ip-10-0-0-204 node: at Query.<anonymous> (/PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:429:17)
Jul  1 17:13:01 ip-10-0-0-204 node: at Query.handleReadyForQuery (/PrairieLearn/node_modules/pg/lib/query.js:129:12)
Jul  1 17:13:01 ip-10-0-0-204 node: at Connection.<anonymous> (/PrairieLearn/node_modules/pg/lib/client.js:266:19)
Jul  1 17:13:01 ip-10-0-0-204 node: at Connection.emit (events.js:315:20)
Jul  1 17:13:01 ip-10-0-0-204 node: at Connection.EventEmitter.emit (domain.js:482:12)
Jul  1 17:13:01 ip-10-0-0-204 node: at /PrairieLearn/node_modules/pg/lib/connection.js:109:10
Jul  1 17:13:01 ip-10-0-0-204 node: at Parser.parse (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:42:17)
Jul  1 17:13:01 ip-10-0-0-204 node: at Socket.<anonymous> (/PrairieLearn/node_modules/pg-protocol/dist/index.js:8:42)
Jul  1 17:13:01 ip-10-0-0-204 node: at Socket.emit (events.js:315:20)
Jul  1 17:13:01 ip-10-0-0-204 node: at Socket.EventEmitter.emit (domain.js:482:12) {
Jul  1 17:13:01 ip-10-0-0-204 node: code: 'ERR_HTTP_HEADERS_SENT'
Jul  1 17:13:01 ip-10-0-0-204 node: }
Jul  1 17:13:01 ip-10-0-0-204 systemd: prairielearn2.service: main process exited, code=exited, status=1/FAILURE
```

**Comment by nwalters512** [comment]
We're no longer using callbacks, so this shouldn't be a problem anymore.
