### ISSUE TITLE
Server crash in _ensureVariantWithClient()

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2692]
I don't know whether it's `question` or `course_instance` that is `undefined` below (at least one of them is causing the `TypeError: Cannot read property 'id' of undefined` error).

```
Jul 08 18:29:17 ip-10-0-0-204.us-east-2.compute.internal node[10519]: /PrairieLearn/lib/question.js:881
Jul 08 18:29:17 ip-10-0-0-204.us-east-2.compute.internal node[10519]: this._ensureVariantWithClient(client, question.id, instance_question_id, authn_user_id, authn_user_id, course_instance.id, course, options, require_open, (err, ret_variant) => {
Jul 08 18:29:17 ip-10-0-0-204.us-east-2.compute.internal node[10519]: ^
Jul 08 18:29:17 ip-10-0-0-204.us-east-2.compute.internal node[10519]: TypeError: Cannot read property 'id' of undefined
Jul 08 18:29:17 ip-10-0-0-204.us-east-2.compute.internal node[10519]: at /PrairieLearn/lib/question.js:881:140
Jul 08 18:29:17 ip-10-0-0-204.us-east-2.compute.internal node[10519]: at /PrairieLearn/node_modules/async/dist/async.js:2948:28
Jul 08 18:29:17 ip-10-0-0-204.us-east-2.compute.internal node[10519]: at replenish (/PrairieLearn/node_modules/async/dist/async.js:440:21)
Jul 08 18:29:17 ip-10-0-0-204.us-east-2.compute.internal node[10519]: at /PrairieLearn/node_modules/async/dist/async.js:445:13
Jul 08 18:29:17 ip-10-0-0-204.us-east-2.compute.internal node[10519]: at eachOfLimit$1 (/PrairieLearn/node_modules/async/dist/async.js:471:34)
Jul 08 18:29:17 ip-10-0-0-204.us-east-2.compute.internal node[10519]: at awaitable (/PrairieLearn/node_modules/async/dist/async.js:208:32)
Jul 08 18:29:17 ip-10-0-0-204.us-east-2.compute.internal node[10519]: at eachOfSeries (/PrairieLearn/node_modules/async/dist/async.js:658:16)
Jul 08 18:29:17 ip-10-0-0-204.us-east-2.compute.internal node[10519]: at awaitable (/PrairieLearn/node_modules/async/dist/async.js:208:32)
Jul 08 18:29:17 ip-10-0-0-204.us-east-2.compute.internal node[10519]: at /PrairieLearn/node_modules/async/dist/async.js:2947:9
Jul 08 18:29:17 ip-10-0-0-204.us-east-2.compute.internal node[10519]: at awaitable (/PrairieLearn/node_modules/async/dist/async.js:208:32)
Jul 08 18:29:17 ip-10-0-0-204.us-east-2.compute.internal node[10519]: at Object.series (/PrairieLearn/node_modules/async/dist/async.js:3957:16)
Jul 08 18:29:17 ip-10-0-0-204.us-east-2.compute.internal node[10519]: at /PrairieLearn/lib/question.js:876:19
Jul 08 18:29:17 ip-10-0-0-204.us-east-2.compute.internal node[10519]: at /PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:335:17
Jul 08 18:29:17 ip-10-0-0-204.us-east-2.compute.internal node[10519]: at Query.callback (/PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:225:13)
Jul 08 18:29:17 ip-10-0-0-204.us-east-2.compute.internal node[10519]: at Query.handleReadyForQuery (/PrairieLearn/node_modules/pg/lib/query.js:129:12)
Jul 08 18:29:17 ip-10-0-0-204.us-east-2.compute.internal node[10519]: at Connection.<anonymous> (/PrairieLearn/node_modules/pg/lib/client.js:266:19)
```

**Comment by nicknytko** [comment]
This can be reproduced on a local instance by picking a question in a course (*not* course instance) and running tests on it.
