### ISSUE TITLE
fileData.toString() crash

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2693]
```
Jul 09 14:13:36 ip-10-0-0-204.us-east-2.compute.internal node[21323]: /PrairieLearn/question-servers/freeform.js:1074
Jul 09 14:13:36 ip-10-0-0-204.us-east-2.compute.internal node[21323]: const fileDataBase64 = fileData.toString('base64');
Jul 09 14:13:36 ip-10-0-0-204.us-east-2.compute.internal node[21323]: ^
Jul 09 14:13:36 ip-10-0-0-204.us-east-2.compute.internal node[21323]: TypeError: Cannot read property 'toString' of undefined
Jul 09 14:13:36 ip-10-0-0-204.us-east-2.compute.internal node[21323]: at /PrairieLearn/question-servers/freeform.js:1074:65
Jul 09 14:13:36 ip-10-0-0-204.us-east-2.compute.internal node[21323]: at Object.returnPythonCaller (/PrairieLearn/lib/workers.js:118:9)
Jul 09 14:13:36 ip-10-0-0-204.us-east-2.compute.internal node[21323]: at /PrairieLearn/question-servers/freeform.js:1071:37
Jul 09 14:13:36 ip-10-0-0-204.us-east-2.compute.internal node[21323]: at /PrairieLearn/question-servers/freeform.js:702:21
Jul 09 14:13:36 ip-10-0-0-204.us-east-2.compute.internal node[21323]: at /PrairieLearn/question-servers/freeform.js:641:24
Jul 09 14:13:36 ip-10-0-0-204.us-east-2.compute.internal node[21323]: at module.exports (/PrairieLearn/node_modules/async-stacktrace/ERR.js:52:7)
Jul 09 14:13:36 ip-10-0-0-204.us-east-2.compute.internal node[21323]: at /PrairieLearn/question-servers/freeform.js:282:21
Jul 09 14:13:36 ip-10-0-0-204.us-east-2.compute.internal node[21323]: at PythonCaller._callCallback (/PrairieLearn/lib/code-caller.js:367:9)
Jul 09 14:13:36 ip-10-0-0-204.us-east-2.compute.internal node[21323]: at PythonCaller._handleChildExit (/PrairieLearn/lib/code-caller.js:314:18)
Jul 09 14:13:36 ip-10-0-0-204.us-east-2.compute.internal node[21323]: at ChildProcess.emit (events.js:315:20)
Jul 09 14:13:36 ip-10-0-0-204.us-east-2.compute.internal node[21323]: at ChildProcess.EventEmitter.emit (domain.js:482:12)
Jul 09 14:13:36 ip-10-0-0-204.us-east-2.compute.internal node[21323]: at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
Jul 09 14:13:36 ip-10-0-0-204.us-east-2.compute.internal systemd[1]: prairielearn.service: main process exited, code=exited, status=1/FAILURE
```

**Comment by nicknytko** [comment]
Can repro locally by finding a question with a dynamic file (`data/customPlot`) and putting `sys.exit(0)` before the file data is returned.
