### ISSUE TITLE
Server crash in freeform fileData

### ISSUE THREAD

**Issue by trombonekenny** [PrairieLearn/PrairieLearn#2694]
```
Jul  9 14:12:23 ip-10-0-0-204 node: /PrairieLearn/question-servers/freeform.js:1074
Jul  9 14:12:23 ip-10-0-0-204 node: const fileDataBase64 = fileData.toString('base64');
Jul  9 14:12:23 ip-10-0-0-204 node: ^
Jul  9 14:12:23 ip-10-0-0-204 node: TypeError: Cannot read property 'toString' of undefined
Jul  9 14:12:23 ip-10-0-0-204 node: at /PrairieLearn/question-servers/freeform.js:1074:65
Jul  9 14:12:23 ip-10-0-0-204 node: at Object.returnPythonCaller (/PrairieLearn/lib/workers.js:118:9)
Jul  9 14:12:23 ip-10-0-0-204 node: at /PrairieLearn/question-servers/freeform.js:1071:37
Jul  9 14:12:23 ip-10-0-0-204 node: at /PrairieLearn/question-servers/freeform.js:702:21
Jul  9 14:12:23 ip-10-0-0-204 node: at /PrairieLearn/question-servers/freeform.js:641:24
Jul  9 14:12:23 ip-10-0-0-204 node: at module.exports (/PrairieLearn/node_modules/async-stacktrace/ERR.js:52:7)
Jul  9 14:12:23 ip-10-0-0-204 node: at /PrairieLearn/question-servers/freeform.js:282:21
Jul  9 14:12:23 ip-10-0-0-204 node: at PythonCaller._callCallback (/PrairieLearn/lib/code-caller.js:367:9)
Jul  9 14:12:23 ip-10-0-0-204 node: at PythonCaller._handleChildExit (/PrairieLearn/lib/code-caller.js:314:18)
Jul  9 14:12:23 ip-10-0-0-204 node: at ChildProcess.emit (events.js:315:20)
Jul  9 14:12:23 ip-10-0-0-204 node: at ChildProcess.EventEmitter.emit (domain.js:482:12)
Jul  9 14:12:23 ip-10-0-0-204 node: at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)

```

The server is getting tickled by these repeated errors this morning. Is some edge case not getting checked?

**Comment by trombonekenny** [comment]
Dupe of #2693
