### ISSUE TITLE
Max startup time exceeded for workspace_id

### ISSUE THREAD

**Issue by matthewfeickert** [PrairieLearn/PrairieLearn#2867]
I'm hitting a error when trying to run with a workspace locally for [`pl-phys2xx`](https://github.com/PrairieLearn/pl-phys2xx), after following the docs on https://prairielearn.readthedocs.io/en/latest/workspaces/

## Minimal failing example on Linux:

```
$ docker pull prairielearn/prairielearn:latest
$ docker pull physicsillinois/phys-214:fall-2020
$ git clone git@github.com:PrairieLearn/pl-phys2xx.git # this is private so assuming you have your ssh keys anyway
$ cd pl-phys2xx
$ git revert a1485b4 # This commit removed workspace code, so need to revert it to have it again
$ bash run_local.sh
# Open http://localhost:3000/pl in browser
# Click "Load from disk"
# Navigate to http://localhost:3000/pl/course_instance/1/instructor/question/2/preview (Question: Example workspace)
# Click "Open workspace"
```

results in the following error logs printed to screen from Docker

```
$ bash run_local.sh 
waiting for server to start.... done
server started

S3rver listening on 127.0.0.1:5000

> PrairieLearn@3.2.0 start /PrairieLearn
> node server.js

info: config.json not found, using default single-course configuration
info: Workspace S3 bucket: workspaces
info: Using local S3RVER configuration
info: Listening on port 8081
info: Successfully initialized workspace host
info: PrairieLearn server start
info: config.json not found, using default single-course configuration
info: [HPM] Proxy created: (pathname) => {
    return pathname.match('/pl/workspace/([0-9])+/container/');
}  -> invalid
info: Connecting to Redis at redis://localhost:6379/
info: External grader running locally
info: Using local S3RVER configuration
info: PrairieLearn server ready, press Control-C to quit
info: Go to http://localhost:3000/pl
info: Syncing /course/questions/Fall2020/labs/lab-01/workspace to workspaces/workspace-1
info: Set workspaces.state to 'stopped'
info: Set workspaces.state to 'launching'
info: controlContainer workspace_hosts query: [{"id":"1","instance_id":"devHost1","hostname":"localhost:8081","load_count":0}]
info: controlContainer workspace_host: {"id":"1","instance_id":"devHost1","hostname":"localhost:8081","load_count":0}
[workspace.js] synced example-prelab.ipynb to workspaces/workspace-1
info: Launching workspace_id=1
info: Pulling docker image: physicsillinois/phys-214:fall-2020
info: Docker pull output:  {"status":"Pulling from physicsillinois/phys-214","id":"fall-2020"}
info: Docker pull output:  {"status":"Digest: sha256:f3fb11cf956ddc7760c0656a0b3e1ca825eee2454af4374ef0905dce281f52b0"}
info: Docker pull output:  {"status":"Status: Image is up to date for physicsillinois/phys-214:fall-2020"}
info: Creating docker container for image=physicsillinois/phys-214:fall-2020
info: Exposed port: 8080
info: Env vars: WORKSPACE_BASE_URL=/pl/workspace/1/container/
info: User binding: 0:0
info: Port binding: 8080:1024
info: Volume mount: /home/feickert/Code/GitHub/Neubauer-Group/pl_ag_jobs/workspaces/workspace-76e47a9f-e197-4941-9b76-928463c48720:/home/jovyan
info: Container name: workspace-76e47a9f-e197-4941-9b76-928463c48720
info: Creating directory /home/feickert/Code/GitHub/Neubauer-Group/pl_ag_jobs/workspaces/workspace-76e47a9f-e197-4941-9b76-928463c48720
error: Error for workspace_id=1: Error: Max startup time exceeded for workspace_id=1
Error: Max startup time exceeded for workspace_id=1
    at Request._callback (/PrairieLearn/workspace_host/interface.js:286:30)
    at self.callback (/PrairieLearn/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.onRequestError (/PrairieLearn/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:315:20)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
_http_outgoing.js:518
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:518:11)
    at ServerResponse.header (/PrairieLearn/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/PrairieLearn/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/PrairieLearn/node_modules/express/lib/response.js:267:15)
    at ServerResponse.send (/PrairieLearn/node_modules/express/lib/response.js:158:21)
    at /PrairieLearn/workspace_host/interface.js:807:29
    at wrapper (/PrairieLearn/node_modules/async/dist/async.js:268:20)
    at next (/PrairieLearn/node_modules/async/dist/async.js:4582:24)
    at /PrairieLearn/node_modules/async/dist/async.js:321:20
    at Request._callback (/PrairieLearn/workspace_host/interface.js:286:21) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

where

```
$ cat run_local.sh 
#!/usr/bin/env bash

if [[ ! -d "$PWD/../pl_ag_jobs" ]]; then
  mkdir -p "$PWD/../pl_ag_jobs"
fi

docker run -it --rm -p 3000:3000 \
  -v "$PWD":/course \
  -v "$PWD/../pl_ag_jobs:/jobs" \
  -e HOST_JOBS_DIR="$PWD/../pl_ag_jobs" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --add-host=host.docker.internal:172.17.0.1 \
  prairielearn/prairielearn:latest
```

## Why do I think this is a bug and not user error?

PrairieLearn runs fine until the workspace is started, and if you run the following you're able to launch into the `physicsillinois/phys-214:fall-2020` Docker and can run the example fine too

```
# from top level of pl-phys2xx
$ docker run --rm -it -v $PWD/questions/Fall2020/labs/lab-01/workspace:/home/jovyan/example -w /home/jovyan/example -p 8080:8080 physicsillinois/phys-214:fall-2020
```

cc @msneubauer

**Comment by nicknytko** [comment]
@matthewfeickert I have a suspicion that this is a permissions bug that we've been running into when running on Docker on linux.  Can you:

1. Grab the container name for the stopped jupyter container:
```sh
# docker container ls -a
```
This should be named something like `workspace-xxxxxxxxxxxxxx`, where the x's are some long uuid.

2. Grab the logs for the container:
```sh
# docker logs workspace-xxxxxxxxxxxxx
```

**Comment by matthewfeickert** [comment]
```
$ docker container ls -a
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS                      PORTS                    NAMES
ad3ccf99242b        physicsillinois/phys-214:fall-2020   "tini -g -- start.sh…"   44 seconds ago      Exited (1) 42 seconds ago                            workspace-54668d93-59eb-41e8-b450-81eeb18b7454
d04accae3176        prairielearn/prairielearn:latest     "/bin/sh -c /Prairie…"   2 minutes ago       Up 2 minutes (healthy)      0.0.0.0:3000->3000/tcp   stupefied_bose
$ docker logs workspace-54668d93-59eb-41e8-b450-81eeb18b7454
Set username to: jovyan
usermod: no changes
Executing the command: jupyter lab
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-lab", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/conda/lib/python3.8/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/notebook/notebookapp.py", line 1766, in initialize
    self.init_configurables()
  File "/opt/conda/lib/python3.8/site-packages/notebook/notebookapp.py", line 1380, in init_configurables
    connection_dir=self.runtime_dir,
  File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/opt/conda/lib/python3.8/site-packages/jupyter_core/application.py", line 100, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/opt/conda/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local
```

**Comment by tdy** [comment]
@matthewfeickert can you try adding these two env vars to your dockerfile? This workaround works on my end, but it'd be great if you could confirm.

```dockerfile
ENV JUPYTER_RUNTIME_DIR /tmp/runtime
ENV JUPYTER_ALLOW_INSECURE_WRITES true
```

**Comment by matthewfeickert** [comment]
> ```dockerfile
> ENV JUPYTER_RUNTIME_DIR /tmp/runtime
> ENV JUPYTER_ALLOW_INSECURE_WRITES true
> ```

That works in terms of allowing the workspace to open, but I am now getting a

```
Error
Unexpected error while saving file: Untitled.ipynb [Errno 13] Permission denied: '/home/jovyan/.local'
```
followed by
```
Launcher Error
Cannot read property 'path' of undefined
```

when I try to open a notebook. This isn't happening when the image is deployed on the live server (the image also works there), so looks like I'll have to fix some permissions issues.

**Comment by mwest1066** [comment]
This appears to have been fixed long ago. I'll close this issue but please feel free to re-open (or make a new one) if a similar problem reoccurs.

**Comment by matthewfeickert** [comment]
Hi @mwest1066 and @nicknytko. Sorry to reopen this almost 2 years later, but the same thing is happening again (only locally, the deployed version on the PrairieLearn servers works) for @msneubauer's https://github.com/PrairieLearn/pl-phys398mla course.

The course uses the Docker image `physicsillinois/phys-398-mla:spring-2022` which has its Dockerfile public on GitHub (https://github.com/illinois-mla/phys-398-mla-image) and is deployed to both Docker Hub and GitHub Container Registry (plug for Issue #5285). The image is quite big (multiple machine learning dependencies will do that) but does load succesfully on the deployed PrairieLearn servers.

## Minimal failing example on Linux:

```console
$ docker pull prairielearn/prairielearn:latest
$ docker pull physicsillinois/phys-398-mla:spring-2022
$ docker images prairielearn/prairielearn:latest
REPOSITORY                  TAG       IMAGE ID       CREATED       SIZE
prairielearn/prairielearn   latest    a90c3605455a   6 hours ago   5.67GB
$ docker images physicsillinois/phys-398-mla:spring-2022
REPOSITORY                     TAG           IMAGE ID       CREATED      SIZE
physicsillinois/phys-398-mla   spring-2022   5636630097a6   5 days ago   7.25GB
$ git clone git@github.com:PrairieLearn/pl-phys398mla.git # this is private so assuming you have your ssh keys anyway
$ cd pl-phys398mla
$ bash run_local.sh
# Open http://localhost:3000/pl in browser
# Click "Load from disk"
# Navigate to http://localhost:3000/pl/course_instance/1/instructor/question/1/preview (Question: Example workspace)
# Click "Open workspace"
```

it will try to pull the image but after about 30 seconds will stop with the error

> Error starting cotnainer. Click "Reboot" to try again.

![PL_error](https://user-images.githubusercontent.com/5142394/151305882-706342b9-5dbb-423d-8054-251ea8b7bace.png)

Clicking "Reboot" will result in the same error (and produces the `Launching workspace-1-1 (useInitialZip=false)` line in stdout below)

The stdout from the script running the Docker container is

```console
$ bash run_local.sh 
Starting PrairieLearn...
info: config.json not found, using default configuration
info: Workspace host ready
info: config.json not found, using default configuration
info: PrairieLearn server ready, press Control-C to quit
info: Go to http://localhost:3000
info: Launching workspace-1-1 (useInitialZip=true)
info: Pulling docker image: physicsillinois/phys-398-mla:spring-2022
info: Launching workspace-1-1 (useInitialZip=false)
info: Pulling docker image: physicsillinois/phys-398-mla:spring-2022
```

and the contents of `run_local.sh` are

```bash
#!/usr/bin/env bash

function run_docker {
  # https://prairielearn.readthedocs.io/en/latest/workspaces/#running-locally-on-docker
  if [[ "$(uname -s)" = "Darwin" ]]; then
    # On MacOS
    docker run -it --rm -p 3000:3000 \
      -v "$PWD":/course \
      -v "$PWD/../pl_ag_jobs:/jobs" \
      -e HOST_JOBS_DIR="$PWD/../pl_ag_jobs" \
      -v /var/run/docker.sock:/var/run/docker.sock \
      prairielearn/prairielearn:latest
  else
    # On Linux
    docker run -it --rm -p 3000:3000 \
      -v "$PWD":/course \
      -v "$PWD/../pl_ag_jobs:/jobs" \
      -e HOST_JOBS_DIR="$PWD/../pl_ag_jobs" \
      -v /var/run/docker.sock:/var/run/docker.sock \
      --add-host=host.docker.internal:172.17.0.1 \
      prairielearn/prairielearn:latest
  fi
}

if [[ ! -d "$PWD/../pl_ag_jobs" ]]; then
  mkdir -p "$PWD/../pl_ag_jobs"
fi

run_docker
```

With things still running if I check the existing containers I see the workspace has already crashed, with run logs of the following:

```console
$ docker container ls -a
CONTAINER ID   IMAGE                                      COMMAND                  CREATED          STATUS                     PORTS                                       NAMES
19d480966458   physicsillinois/phys-398-mla:spring-2022   "tini -g -- start.sh…"   5 seconds ago    Exited (1) 4 seconds ago                                               workspace-df5fd275-dc62-42e7-a531-57d3edea24e9
f18ccff3b8b7   prairielearn/prairielearn:latest           "/bin/sh -c /Prairie…"   32 seconds ago   Up 32 seconds (healthy)    0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   infallible_hopper
$ docker logs workspace-df5fd275-dc62-42e7-a531-57d3edea24e9
Entered start.sh with args: jupyter lab
Running as jovyan: jupyter lab
[I 2022-01-27 07:03:07.558 ServerApp] jupyterlab | extension was successfully linked.
[W 2022-01-27 07:03:07.561 NotebookApp] 'base_url' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-01-27 07:03:07.561 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-01-27 07:03:07.561 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-01-27 07:03:07.561 NotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-01-27 07:03:07.561 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-01-27 07:03:07.561 NotebookApp] 'custom_display_url' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-01-27 07:03:07.561 NotebookApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-01-27 07:03:07.561 NotebookApp] 'allow_origin' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-01-27 07:03:07.570 ServerApp] [Errno 13] Permission denied: '/home/jovyan/.local'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/traitlets/traitlets.py", line 537, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-lab", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/jupyter_server/extension/application.py", line 567, in launch_instance
    serverapp = cls.initialize_server(argv=args)
  File "/opt/conda/lib/python3.9/site-packages/jupyter_server/extension/application.py", line 537, in initialize_server
    serverapp.initialize(
  File "/opt/conda/lib/python3.9/site-packages/traitlets/config/application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 2324, in initialize
    self.init_configurables()
  File "/opt/conda/lib/python3.9/site-packages/jupyter_server/serverapp.py", line 1743, in init_configurables
    connection_dir=self.runtime_dir,
  File "/opt/conda/lib/python3.9/site-packages/traitlets/traitlets.py", line 577, in __get__
    return self.get(obj, cls)
  File "/opt/conda/lib/python3.9/site-packages/traitlets/traitlets.py", line 540, in get
    default = obj.trait_defaults(self.name)
  File "/opt/conda/lib/python3.9/site-packages/traitlets/traitlets.py", line 1580, in trait_defaults
    return self._get_trait_default_generator(names[0])(self)
  File "/opt/conda/lib/python3.9/site-packages/jupyter_core/application.py", line 95, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/opt/conda/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 11, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/conda/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/conda/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local'
```

## Working in deployment on PrairieLearn servers

As I mentioned, things are working on PrairieLearn servers where the image is successfully synced

![docker_image](https://user-images.githubusercontent.com/5142394/151306905-5c6902b2-8070-4d68-989f-c9d9b8372564.png)

and once it spins up, works as expected.

![aws_working](https://user-images.githubusercontent.com/5142394/151307419-357cb2a1-8cbe-48ef-a463-3f2271a3cea1.png)


Thoughts? I'm not sure why I should get a `PermissionError` locally but not on the PL servers.

**Comment by msneubauer** [comment]
Has this issue been addressed? I see that it is listed a "Closed" but @matthewfeickert 's issue is the last comment

**Comment by msneubauer** [comment]
Here is what i see:
```
MacBook-Pro:pl-phys398mla msn$ source run_local.sh
Starting PrairieLearn...
info: config.json not found, using default configuration
info: Workspace host ready
info: config.json not found, using default configuration
info: PrairieLearn server ready, press Control-C to quit
info: Go to http://localhost:3000
make: *** [Makefile:10: start] Killed
```

I should point out that I just pulled the latest container but run on an Apple M1 (new laptop)

**Comment by mwest1066** [comment]
@msneubauer can you run the workspace container locally directly from docker (without any additional docker flags)?

**Comment by msneubauer** [comment]
@mwest1066 Here's what I did/see:
```
docker pull prairielearn/prairielearn:latest
docker run -it --rm -p 3000:3000 -v "$PWD":/course -v "$PWD/../pl_ag_jobs:/jobs" -e HOST_JOBS_DIR="$PWD/../pl_ag_jobs" -v /var/run/docker.sock:/var/run/docker.sock prairielearn/prairielearn:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Starting PrairieLearn...
info: config.json not found, using default configuration
info: Workspace host ready
info: config.json not found, using default configuration
info: PrairieLearn server ready, press Control-C to quit
info: Go to http://localhost:3000
make: *** [Makefile:10: start] Killed
make: *** Waiting for unfinished jobs....
```
