### ISSUE TITLE
Write-after-end error handling is incorrect

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#2982]
The fatal unhandled error was the `write after end`. But we also had a bunch of `Cannot set headers after they are sent to the client` before that (presumably unrelated, but shouldn't be happening).

```
Aug 30 23:11:24 ip-10-0-0-204.us-east-2.compute.internal node[96130]: error: Error while handling workspace request error: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
Aug 30 23:11:24 ip-10-0-0-204.us-east-2.compute.internal node[96722]: error: Error proxying workspace request: Error: connect ECONNREFUSED 10.0.0.251:20123
Aug 30 23:11:24 ip-10-0-0-204.us-east-2.compute.internal node[96722]: error: Error while handling workspace request error: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
Aug 30 23:11:29 ip-10-0-0-204.us-east-2.compute.internal node[96130]: error: Error proxying workspace request: Error: connect EHOSTUNREACH 10.0.0.114:8923
Aug 30 23:11:29 ip-10-0-0-204.us-east-2.compute.internal node[96130]: error: Error while handling workspace request error: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
Aug 30 23:11:46 ip-10-0-0-204.us-east-2.compute.internal node[96248]: info: ltiOutcomes.updateScore() ai_id=1679223 score=0.875 returned success
Aug 30 23:11:58 ip-10-0-0-204.us-east-2.compute.internal node[96130]: error: Error proxying workspace request: Error: connect ECONNREFUSED 10.0.0.251:7733
Aug 30 23:11:58 ip-10-0-0-204.us-east-2.compute.internal node[96130]: error: Error while handling workspace request error: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
Aug 30 23:12:05 ip-10-0-0-204.us-east-2.compute.internal node[96402]: info: Error page {"msg":"Access denied","id":"LYRD74PIC8ZS","status":403,"stack":"Error: Access denied\n    at Object.make (/PrairieLearn/node_modules/@prairielearn/prairielib/lib/error.js:5:19)\n    at /Prai
Aug 30 23:12:05 ip-10-0-0-204.us-east-2.compute.internal node[96722]: error: Error proxying workspace request: Error: connect ECONNREFUSED 10.0.0.243:25540
Aug 30 23:12:05 ip-10-0-0-204.us-east-2.compute.internal node[96722]: error: Error while handling workspace request error: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
Aug 30 23:12:06 ip-10-0-0-204.us-east-2.compute.internal node[96722]: error: Error proxying workspace request: Error: connect ECONNREFUSED 10.0.0.251:20123
Aug 30 23:12:06 ip-10-0-0-204.us-east-2.compute.internal node[96722]: error: Error while handling workspace request error: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
Aug 30 23:12:26 ip-10-0-0-204.us-east-2.compute.internal node[96722]: error: Error proxying workspace request: Error: connect ECONNREFUSED 10.0.0.243:25540
Aug 30 23:12:26 ip-10-0-0-204.us-east-2.compute.internal node[96722]: error: Error while handling workspace request error: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
Aug 30 23:12:36 ip-10-0-0-204.us-east-2.compute.internal node[96130]: error: Error proxying workspace request: Error: connect ECONNREFUSED 10.0.0.251:7733
Aug 30 23:12:36 ip-10-0-0-204.us-east-2.compute.internal node[96130]: error: Error while handling workspace request error: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
Aug 30 23:12:38 ip-10-0-0-204.us-east-2.compute.internal node[96402]: info: ltiOutcomes.updateScore() ai_id=1688686 score=0.5 returned success
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: events.js:292
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: throw er; // Unhandled 'error' event
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: ^
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: at writeAfterEnd (_stream_writable.js:266:14)
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: at Socket.Writable.write (_stream_writable.js:315:5)
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: at ClientRequest.<anonymous> (/PrairieLearn/node_modules/http-proxy/lib/http-proxy/passes/ws-incoming.js:115:16)
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: at ClientRequest.emit (events.js:315:20)
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: at ClientRequest.EventEmitter.emit (domain.js:483:12)
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: at Socket.socketOnData (_http_client.js:469:22)
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: at Socket.emit (events.js:315:20)
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: at Socket.EventEmitter.emit (domain.js:483:12)
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: at addChunk (_stream_readable.js:295:12)
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: at readableAddChunk (_stream_readable.js:271:9)
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: at Socket.Readable.push (_stream_readable.js:212:10)
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: Emitted 'error' event on Socket instance at:
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: at errorOrDestroy (internal/streams/destroy.js:108:12)
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: at writeAfterEnd (_stream_writable.js:268:3)
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: at Socket.Writable.write (_stream_writable.js:315:5)
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: [... lines matching original stack trace ...]
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: code: 'ERR_STREAM_WRITE_AFTER_END'
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal node[96402]: }
Aug 30 23:12:41 ip-10-0-0-204.us-east-2.compute.internal systemd[1]: prairielearn.service: main process exited, code=exited, status=1/FAILURE
```

**Comment by mwest1066** [comment]
Happened again.

**Comment by mwest1066** [comment]
And again

**Comment by mwest1066** [comment]
Still happening

**Comment by reteps** [comment]
Claude says this is mostly resolved, but still some cleanup needed:

```
  1. res.end() called even when response is already ended (line 167)

  if (!res.headersSent) {
    res.status(getStatusCode(err));
  }
  res.end('Error proxying workspace request');  // ← called unconditionally

  If the response stream is already finished (e.g., the proxy successfully piped a response then the connection dropped), calling res.end() will throw ERR_STREAM_WRITE_AFTER_END. This
  should be guarded with a res.writableEnded check.

  2. No try-catch around the error handler itself

  If res.end() or res.destroy() throws for any reason, the error propagates out of the error handler as an unhandled exception. The error handler should be wrapped in try-catch so it
  can't crash the process.

  3. WebSocket socket error event from http-proxy internals

  The original fatal crash (ERR_STREAM_WRITE_AFTER_END at ws-incoming.js:115) is a race condition inside http-proxy: after a WebSocket error, socket.end() is called, but then the response
   event fires on the ClientRequest and tries to socket.write(). The resulting error event on the socket is unhandled, crashing the process.

  This can be mitigated by attaching a no-op error listener to the socket during WebSocket proxy handling. The proxyReqWs event or a custom upgrade listener could be used for this.
```
