### ISSUE TITLE
Very large inputs will break rendering of pl-integer-input

### ISSUE THREAD

**Issue by nicknytko** [PrairieLearn/PrairieLearn#3080]
Reproduce by putting the value `112173586448650064316584391727166410732855297644839296413224534507665844338688` into an integer input.  (How students got this value, I have no idea...)

This happens because the entry in `submitted_values` gets truncated as `1.1217358644865006e+77` when converted to JSON, and then this is assumed to be an integer when rendered.

Stack trace:

```
Traceback (most recent call last):
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 167, in <module>
    worker_loop()
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 113, in worker_loop
    val = method(*args)
  File "/PrairieLearn/elements/pl-integer-input/pl-integer-input.py", line 115, in render
    html_params['a_sub'] = '{:d}'.format(a_sub)
ValueError: Unknown format code 'd' for object of type 'float'
Traceback (most recent call last):
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 179, in <module>
    raise Exception('worker process exited unexpectedly with status %d' % status)
Exception: worker process exited unexpectedly with status 256
```

**Comment by jonatanschroeder** [comment]
I suggest this should be closed in favour of #3708 .
