### ISSUE TITLE
Chunks error for courses with duplicate question UUIDs

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3136]
Courses with duplicate question UUIDs trigger the following error. The new partial-syncing code can handle such questions, so we should ideally handle them with the chunks code too.

```
error: ON CONFLICT DO UPDATE command cannot affect row a second time
Async Stacktrace:
    at /PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:509:13
    at handleError (/PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:418:13)
error: ON CONFLICT DO UPDATE command cannot affect row a second time
    at Parser.parseErrorMessage (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/PrairieLearn/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
{
    "sqlError": {
        "length": 1432,
        "name": "error",
        "severity": "ERROR",
        "code": "21000",
        "hint": "Ensure that no rows proposed for insertion within the same command have duplicate constrained values.",
        "where": "SQL statement \"INSERT INTO chunks (type, course_id, question_id, course_instance_id, assessment_id, uuid)\n    SELECT\n        (chunk->>'type')::enum_chunk_type,\n        in_course_id,\n        q.id,\n        ci.id,\n        a.id,\n        (chunk->>'uuid')::uuid\n    FROM unnest(generated_chunks) AS chunk(json)\n    LEFT JOIN questions AS q ON (q.uuid = (chunk->>'questionUuid')::uuid AND q.qid = (chunk->>'questionName') AND q.course_id = in_course_id)\n    LEFT JOIN course_instances AS ci ON (ci.uuid = (chunk->>'courseInstanceUuid')::uuid AND ci.short_name = (chunk->>'courseInstanceName') AND ci.course_id = in_course_id)\n    LEFT JOIN assessments AS a ON (a.uuid = (chunk->>'assessmentUuid')::uuid AND a.tid = (chunk->>'assessmentName') AND a.course_instance_id = ci.id)\n    ON CONFLICT (type, course_id, coalesce(question_id, -1), coalesce(course_instance_id, -1), coalesce(assessment_id, -1)) DO UPDATE\n    SET\n        type = EXCLUDED.type,\n        question_id = EXCLUDED.question_id,\n        course_instance_id = EXCLUDED.course_instance_id,\n        assessment_id = EXCLUDED.assessment_id,\n        uuid = EXCLUDED.uuid\"\nPL/pgSQL function chunks_insert(bigint,json[]) line 3 at SQL statement",
        "file": "nodeModifyTable.c",
        "line": "1413",
        "routine": "ExecOnConflictUpdate",
        "message": "ON CONFLICT DO UPDATE command cannot affect row a second time"
    },
    "sql": "SELECT * FROM chunks_insert($1,$2)",
    "sqlParams": [
        123,
        [
            {
                "type": "question",
                "questionName": "CITESwiki",
                "questionUuid": "a872526f-1f4d-4f6c-ac87-da4aee4896f6",
                "uuid": "72472457-2163-40a6-99b8-585232143ebd"
            },
            {
                "type": "question",
                "questionName": "CSPClasses",
                "questionUuid": "91e13781-b83c-4529-a229-eca3c898cedc",
                "uuid": "42ae9ebc-cc30-4521-ac1d-7899ac16a939"
            },
```

**Comment by mwest1066** [comment]
I think the problem here is that we are using UUIDs to JOIN the `questions` and other tables: https://github.com/PrairieLearn/PrairieLearn/blob/e12697ac9dbdd2b0e5f2756a08435115762c8d82/sprocs/chunks_insert.sql#L17

The new robust sync code does not guarantee that each question has a unique UUID because the instructor might have made two questions with the same UUID. The guarantees are:

* UUIDs are unique (within the narrowest enclosing scope, so within a course_id for questions) if they are non-NULL
* QIDs are non-NULL and unique when `deleted_at IS NULL`

Similar guarantees hold for course_instances (with short_name instead of qid, with a course_id) and assessments (with tid instead of qid, within a course_instance_id).

I think we therefore just need to change `sprocs/chunks_insert()` to JOIN on qid/tid/short_name and not on UUID.
