### ISSUE TITLE
Errors on workspace launch

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3147]
At the bottom is the error log from launching `jonatanschroeder/drawio` on the CA instance. The workspace is stuck displaying `Starting container` and never displays an error message. Some of the issues are:
* [ ] Why do we have a null byte (0x00) error from postgres?
* [ ] Why aren't we catching the exception?
* [ ] Why does the container get `EACCES: permission denied, mkdir '/.config'`?

This container runs fine if you run it manually. The workspace options are:
```
    "workspaceOptions": {
        "image": "jonatanschroeder/drawio",
        "port": 8080,
        "args": "--auth none",
        "home": "/home/coder",
        "gradedFiles": [
            "flowchart.drawio"
        ],
        "syncIgnore": [
            ".local/share/code-server/"
        ]
    },
```

The stack trace is:
```
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: (node:4258) UnhandledPromiseRejectionWarning: Async Stacktrace:
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: at /PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:509:13
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: at handleError (/PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:418:13)
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: error: invalid byte sequence for encoding "UTF8": 0x00
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: at Parser.parseErrorMessage (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:278:15)
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: at Parser.handlePacket (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:126:29)
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: at Parser.parse (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:39:38)
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: at Socket.<anonymous> (/PrairieLearn/node_modules/pg-protocol/dist/index.js:8:42)
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: at Socket.emit (events.js:315:20)
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: at Socket.EventEmitter.emit (domain.js:483:12)
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: at addChunk (_stream_readable.js:295:12)
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: at readableAddChunk (_stream_readable.js:271:9)
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: at Socket.Readable.push (_stream_readable.js:212:10)
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: (node:4258) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was n
ot handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: (node:4258) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: error: Error for workspace_id=49: Error: Max startup time exceeded for workspace_id=49 (launch uuid cb0b58a4-cddd-4953-8a78-d569b04caed2)
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: [1B blob data]
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: *whoami: cannot find name for user ID 1001
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: [1B blob data]
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: ,EACCES: permission denied, mkdir '/.config'
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: Error: Max startup time exceeded for workspace_id=49 (launch uuid cb0b58a4-cddd-4953-8a78-d569b04caed2)
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: [1B blob data]
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: *whoami: cannot find name for user ID 1001
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: [1B blob data]
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: ,EACCES: permission denied, mkdir '/.config'
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: at Object.callback (/PrairieLearn/workspace_host/interface.js:608:34)
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: at /PrairieLearn/node_modules/dockerode/lib/container.js:1006:12
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: at Modem.buildPayload (/PrairieLearn/node_modules/docker-modem/lib/modem.js:317:7)
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: at IncomingMessage.<anonymous> (/PrairieLearn/node_modules/docker-modem/lib/modem.js:275:14)
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: at IncomingMessage.emit (events.js:327:22)
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: at IncomingMessage.EventEmitter.emit (domain.js:483:12)
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: at endReadableNT (_stream_readable.js:1220:12)
Sep 18 03:48:56 ip-172-31-44-93.ca-central-1.compute.internal node[4258]: at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by mwest1066** [comment]
To reproduce on MacOS:
```
$ docker run -it --rm -u 1001:1001 jonatanschroeder/drawio
whoami: cannot find name for user ID 1001
EACCES: permission denied, mkdir '/.config'
```

However this works for `codercom/code-server `:
```
$ docker run -it --rm -u 1001:1001 codercom/code-server
whoami: cannot find name for user ID 1001
[2020-09-18T05:05:15.653Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2020-09-18T05:05:15.657Z] info  Using config file ~/.config/code-server/config.yaml
[2020-09-18T05:05:16.081Z] info  Using user-data-dir ~/.local/share/code-server
[2020-09-18T05:05:16.092Z] info  code-server 3.5.0 de41646fc402b968ca6d555fdf2da7de9554d28a
[2020-09-18T05:05:16.099Z] info  HTTP server listening on http://0.0.0.0:8080
[2020-09-18T05:05:16.099Z] info      - Using password from ~/.config/code-server/config.yaml
[2020-09-18T05:05:16.099Z] info      - To disable use `--auth none`
[2020-09-18T05:05:16.099Z] info    - Not serving HTTPS
```

**Comment by tdy** [comment]
Can also reproduce in PowerShell and WSL with `docker run -it --rm -u 1001:1001 .../...`

**Comment by echuber2** [comment]
Note the pitfalls that necessitate using fixuid to run code-server as a local app, which fixuid helps with, but also can have risks when running it on a server: https://boxboat.com/2017/07/25/fixuid-change-docker-container-uid-gid/

It's referring to a UID 1001 that doesn't exist when expected. The intention of fixuid is that it would be the UID/GID of your local user that's running the docker. Some changes to how the author's dockerfiles handle permissions could probably resolve this. However, the issue may be that fixuid isn't even running the second time. If I run the docker manually and remove the `-q` (quiet) option from fixuid in entrypoint.sh, this happens:

```
coder@8ebd58a40b29:~$ dumb-init fixuid /usr/bin/code-server "--bind-addr" "0.0.0.0:8080" "."
fixuid: fixuid should only ever be used on development systems. DO NOT USE IN PRODUCTION
fixuid: already ran on this system; will not attempt to change UID/GID
[2020-09-18T10:59:49.293Z] info  Using config file ~/.config/code-server/config.yaml
[2020-09-18T10:59:49.491Z] info  Using user-data-dir ~/.local/share/code-server
[2020-09-18T10:59:49.495Z] info  code-server 3.5.0 de41646fc402b968ca6d555fdf2da7de9554d28a
[2020-09-18T10:59:49.498Z] info  HTTP server listening on http://0.0.0.0:8080
[2020-09-18T10:59:49.498Z] info      - Using password from ~/.config/code-server/config.yaml
[2020-09-18T10:59:49.498Z] info      - To disable use `--auth none`
[2020-09-18T10:59:49.498Z] info    - Not serving HTTPS
```

And if I change the entrypoint to `bash` to see what's happening with user 1001, then:

```
$ sudo docker run -it --rm -p 3000:8080 -u 1001:1001 --entrypoint bash jonatanschroeder/drawio
I have no name!@fe0c0148f42c:/home/coder$ whoami
whoami: cannot find name for user ID 1001
I have no name!@fe0c0148f42c:/home/coder$ id
uid=1001 gid=1001 groups=1001
I have no name!@fe0c0148f42c:/home/coder$ echo test > test.txt
bash: test.txt: Permission denied
```

There's another issue because the vs extension is preinstalled to the root home directory, not coder's. Here's a fixed dockerfile based on the existing one:

```dockerfile

FROM jonatanschroeder/drawio

USER coder

USER root

RUN	mkdir -p /home/coder/.local/share/code-server/extensions/hediet.vscode-drawio-0.7.2 && \
	cp -a /root/.local/share/code-server/extensions/hediet.vscode-drawio-0.7.2/. \
		/home/coder/.local/share/code-server/extensions/hediet.vscode-drawio-0.7.2 && \
	chown -R coder:coder /home/coder/.local/share/code-server && \
	rm -f /run/fixuid.ran && \
	echo "" > /usr/bin/entrypoint.sh && \
	/usr/bin/env echo -e '#!/usr/bin/env sh \n' \
		'set -eu \n' \
		'if [ "${DOCKER_USER-}" ]; then \n' \
		'  echo "$DOCKER_USER ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers.d/nopasswd > /dev/null \n' \
		'  sudo usermod --login "$DOCKER_USER" \ \n' \
		'    --move-home --home "/home/$DOCKER_USER" \ \n' \
		'    coder \n' \
		'  sudo groupmod -n "$DOCKER_USER" coder \n' \
		'  sudo sed -i "/coder/d" /etc/sudoers.d/nopasswd \n' \
		'  sudo sed -i "s/coder/$DOCKER_USER/g" /etc/fixuid/config.yml \n' \
		'  export HOME="/home/$DOCKER_USER" \n' \
		'fi \n' \
		'# This is not set by default. \n' \
		'export USER="coder" \n' \
		'dumb-init fixuid -q /usr/bin/code-server "$@"' >> /usr/bin/entrypoint.sh

EXPOSE 8080
USER coder
WORKDIR /home/coder

ENTRYPOINT ["/usr/bin/env", "sh", "/usr/bin/entrypoint.sh", "--bind-addr", "0.0.0.0:8080", "."]
```

This one copies the existing pre-installed extension from root to the coder home directory. It also deletes `/run/fixuid.ran` to allow running fixuid the second time upon entry, but I don't know if this is what we should be doing in production anyway (as the fixuid documentation says not to). Instead we could manually control the needed user id as it should be on the server when the docker runs.

Also, note that fixuid makes the startup very slow, because it does a recursive chmod to change user to 1001 on a bunch of stuff. I think we can fix that in several ways (apart from not using fixuid).

**Comment by echuber2** [comment]
This version starts up a lot faster by minimizing the amount of work `fixuid` has to do:

```dockerfile

FROM jonatanschroeder/drawio

USER 0:0

RUN	mkdir -p /tmp/.local/share/code-server/extensions/hediet.vscode-drawio-0.7.2 && \
	cp -a /root/.local/share/code-server/extensions/hediet.vscode-drawio-0.7.2/. \
		/tmp/.local/share/code-server/extensions/hediet.vscode-drawio-0.7.2 && \
	chown -R root:root /root/.local && \
	chgrp -R users /tmp/.local && \
	rm -f /run/fixuid.ran && \
	echo "" > /usr/bin/entrypoint-helper.sh && chmod +x /usr/bin/entrypoint-helper.sh && \
	/usr/bin/env echo -e '#!/usr/bin/env sh \n' \
		'set -eu \n' \
		'eval $( fixuid -q ) \n' \
		'rm -rf /home/coder/.local/share/code-server/extensions/hediet.vscode-drawio-0.7.2 \n' \
		'mkdir -p /home/coder/.local/share/code-server/extensions/hediet.vscode-drawio-0.7.2 \n' \
		'cp -a --no-preserve=ownership /tmp/.local/share/code-server/extensions/hediet.vscode-drawio-0.7.2/. /home/coder/.local/share/code-server/extensions/hediet.vscode-drawio-0.7.2 \n' \
		'/usr/bin/code-server "$@"' >> /usr/bin/entrypoint-helper.sh && \
	echo "" > /usr/bin/entrypoint.sh && chmod +x /usr/bin/entrypoint.sh && \
	/usr/bin/env echo -e '#!/usr/bin/env sh \n' \
		'set -eu \n' \
		'if [ "${DOCKER_USER-}" ]; then \n' \
		'  echo "$DOCKER_USER ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers.d/nopasswd > /dev/null \n' \
		'  sudo usermod --login "$DOCKER_USER" \ \n' \
		'    --move-home --home "/home/$DOCKER_USER" \ \n' \
		'    coder \n' \
		'  sudo groupmod -n "$DOCKER_USER" coder \n' \
		'  sudo sed -i "/coder/d" /etc/sudoers.d/nopasswd \n' \
		'  sudo sed -i "s/coder/$DOCKER_USER/g" /etc/fixuid/config.yml \n' \
		'  export HOME="/home/$DOCKER_USER" \n' \
		'fi \n' \
		'# This is not set by default. \n' \
		'export USER="coder" \n' \
		'dumb-init /usr/bin/entrypoint-helper.sh "$@"' >> /usr/bin/entrypoint.sh

EXPOSE 8080
USER coder
WORKDIR /home/coder

ENTRYPOINT ["/usr/bin/env", "sh", "/usr/bin/entrypoint.sh", "--bind-addr", "0.0.0.0:8080", "."]
```

Test it with:

```
docker build -t jon .
docker run -it --rm -p 3000:8080 -u 1001:1002 jon --auth none
```

However, this is janky, so the dockerfile that's meant to build-in the drawio extension should ideally be rewritten itself. Also, we should get away from using `fixuid` if possible. Note the assumptions that `fixuid` makes:

>* build a Dockerfile with user/group dockeruser:dockergroup that has UID/GID 1000:1000
>* host is running as UID/GID 1001:1002, host mounted volume has permissions 1001:1002
>* run the docker container with argument -u 1001:1002 so that container is now running with same UID/GID as host
>* fixuid can run as an entrypoint or in a startup script and performs the following:
>   * changes dockeruser UID to 1001
>   * changes dockergroup GID to 1002
>   * changes all file permissions for old dockeruser:dockergroup to 1001:1002
>   * updates $HOME inside container to dockeruser $HOME
>* now container UID/GID matches host UID/GID and files created in the container on the host mount will be correct

(from [fixuid documentation](https://github.com/boxboat/fixuid/blob/master/README.md))

**Comment by mwest1066** [comment]
This seems to have been a permissions issue due to the fact we run as user 1001:1001 in production. I'm closing this issue now, but please re-open (or make a new issue) if this still needs attention.
