### ISSUE TITLE
Redundant unique constraint in questions table

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3162]
In `database/tables/questions.pg` we have two constraints:

```
questions_course_id_number_nondeleted_key: UNIQUE USING btree (course_id, uuid) WHERE deleted_at IS NULL
questions_course_id_uuid_key: UNIQUE USING btree (course_id, uuid)
```

The first one should just be deleted.

**Comment by pamelafox** [comment]
I am getting the first error after accidentally repeating a UUID:
"duplicate key value violates unique constraint "questions_course_id_number_nondeleted_key"

Is there a workaround? Can I manually muck with the database?

**Comment by mwest1066** [comment]
If you edit one of the questions to change the UUID it should fix itself. Does that work for you?

**Comment by pamelafox** [comment]
That didn't work no, even though I grepped the repo to make sure the UUID is only there once. Full dump--


error: duplicate key value violates unique constraint "questions_course_id_number_nondeleted_key"
Async Stacktrace:
    at /PrairieLearn/pages/instructorLoadFromDisk/instructorLoadFromDisk.js:55:33
    at /PrairieLearn/sync/syncFromDisk.js:131:17
    at /PrairieLearn/sync/syncFromDisk.js:111:25
    at /PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:532:13
    at /PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:509:13
    at handleError (/PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:418:13)

error: duplicate key value violates unique constraint "questions_course_id_number_nondeleted_key"
    at Parser.parseErrorMessage (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/PrairieLearn/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
{
    "sqlError": {
        "length": 1872,
        "name": "error",
        "severity": "ERROR",
        "code": "23505",
        "detail": "Key (course_id, uuid)=(1, c6f831a4-34b2-4402-bf9c-7f7f106784fd) already exists.",
        "where": "SQL statement \"WITH\n    matched_rows AS (\n        SELECT src.qid AS src_qid, src.uuid AS src_uuid, dest.id AS dest_id -- matched_rows cols have underscores\n        FROM disk_questions AS src LEFT JOIN questions AS dest ON (\n            dest.course_id = syncing_course_id\n            AND (src.uuid = dest.uuid\n                 OR ((src.uuid IS NULL OR dest.uuid IS NULL)\n                     AND src.qid = dest.qid AND dest.deleted_at IS NULL)))\n    ),\n    deactivate_unmatched_dest_rows AS (\n        UPDATE questions AS dest\n        SET deleted_at = now()\n        WHERE dest.id NOT IN (\n            SELECT dest_id FROM matched_rows WHERE dest_id IS NOT NULL\n        ) AND dest.deleted_at IS NULL AND dest.course_id = syncing_course_id\n    ),\n    update_matched_dest_rows AS (\n        UPDATE questions AS dest\n        SET qid = src_qid, uuid = src_uuid, deleted_at = NULL\n        FROM matched_rows\n        WHERE dest.id = dest_id AND dest.course_id = syncing_course_id\n    ),\n    insert_unmatched_src_rows AS (\n        INSERT INTO questions AS dest (course_id, qid, uuid, deleted_at)\n        SELECT syncing_course_id, src_qid, src_uuid, NULL\n        FROM matched_rows\n        WHERE dest_id IS NULL\n        RETURNING dest.qid AS src_qid, dest.id AS inserted_dest_id\n    )\n    -- Make a map from QID to ID to return to the caller\n    SELECT jsonb_object_agg(src_qid, COALESCE(dest_id, inserted_dest_id))\n                            FROM matched_rows LEFT JOIN insert_unmatched_src_rows USING (src_qid)\"\nPL/pgSQL function sync_questions(jsonb[],bigint) line 41 at SQL statement",
        "schema": "public",
        "table": "questions",
        "constraint": "questions_course_id_number_nondeleted_key",
        "file": "nbtinsert.c",
        "line": "534",
        "routine": "_bt_check_unique",
        "message": "duplicate key value violates unique constraint \"questions_course_id_number_nondeleted_key\""
    },
    "sql": "SELECT * FROM sync_questions($1,$2)",
    "sqlParams": [
        [
            "[\"elementMultipleChoice\",\"d57c08e9-f1a6-4b65-a698-f29bc8ce047a\",\"\",\"\",{\"type\":\"Freeform\",\"title\":\"From Python if/else to Scheme if\",\"partial_credit\":true,\"client_files\":[\"client.js\",\"question.html\",\"answer.html\"],\"topic\":\"Scheme-Special Forms\",\"grading_method\":\"Internal\",\"single_variant\":false,\"dependencies\":{}}]",
            "[\"wwpd-IfElse-OneArg/wwpd-IfElse-OneArg-HowBig\",\"d6f70f7e-0056-11ec-9a03-0242ac130003\",\"\",\"\",{\"type\":\"Freeform\",\"title\":\"WWPD If/Else (One argument)\",\"partial_credit\":true,\"client_files\":[\"client.js\",\"question.html\",\"answer.html\"],\"topic\":\"Python-Conditionals\",\"grading_method\":\"Internal\",\"single_variant\":false,\"dependencies\":{}}]",
            "[\"wwpd-IfElse-TwoArgs/wwpd-IfElse-TwoArgs-xkcd\",\"c6f831a4-34b2-4402-bf9c-7f7f106784fd\",\"\",\"\",{\"type\":\"Freeform\",\"title\":\"WWPD If/Else (Two Arguments)\",\"partial_credit\":true,\"client_files\":[\"client.js\",\"question.html\",\"answer.html\"],\"topic\":\"Python-Conditionals\",\"grading_method\":\"Internal\",\"single_variant\":false,\"dependencies\":{}}]"
        ],
        "1"
    ]
}

**Comment by mwest1066** [comment]
Is this on your local computer, or on a production server? If it's local, can you stop and start PrairieLearn again?

**Comment by pamelafox** [comment]
Duhr, thanks! Restarting the docker image cleared it.

**Comment by mwest1066** [comment]
> Duhr, thanks! Restarting the docker image cleared it.

Great! Sorry for the inconvenience!
