### ISSUE TITLE
SQL error when trying to create new group name

### ISSUE THREAD

**Issue by nicknytko** [PrairieLearn/PrairieLearn#3221]
https://prairielearn.slack.com/files/UGGPHFKFB/F01BT0Y06S0/bandicam_2020-09-28_23-53-45-911.mp4?origin_team=T0PHEMPRV&origin_channel=C0XBTPZMZ

![image](https://user-images.githubusercontent.com/1790491/94611237-11e46580-0267-11eb-93c3-29953c8ed695.png)

```
{
  msg: 'more than one row returned by a subquery used as an expression',
  id: 'LTW9E2LUSYFI',
  status: 500,
  stack: 'Async Stacktrace:\n' +
    '    at /PrairieLearn/pages/studentAssessmentHomework/studentAssessmentHomework.js:157:29\n' +
    '    at handleError (/PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:418:13)\n' +
    '\n' +
    'error: more than one row returned by a subquery used as an expression\n' +
    '    at Parser.parseErrorMessage (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:278:15)\n' +
    '    at Parser.handlePacket (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:126:29)\n' +
    '    at Parser.parse (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:39:38)\n' +
    '    at Socket.<anonymous> (/PrairieLearn/node_modules/pg-protocol/dist/index.js:8:42)\n' +
    '    at Socket.emit (events.js:315:20)\n' +
    '    at Socket.EventEmitter.emit (domain.js:483:12)\n' +
    '    at addChunk (_stream_readable.js:295:12)\n' +
    '    at readableAddChunk (_stream_readable.js:271:9)\n' +
    '    at Socket.Readable.push (_stream_readable.js:212:10)\n' +
    '    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)',
  data: `{"sqlError":{"length":129,"name":"error","severity":"ERROR","code":"21000","file":"nodeSubplan.c","line":"1136","routine":"ExecSetParamPlan","message":"more than one row returned by a subquery used as an expression"},"sql":"-- BLOCK join_justcreated_group\\nWITH log AS (\\n    INSERT INTO group_users\\n        (group_id, user_id)\\n    VALUES\\n        (\\n            (SELECT id FROM groups WHERE name = $group_name AND deleted_at IS NULL),\\n            $user_id\\n        )\\n    RETURNING group_id\\n)\\nINSERT INTO group_logs\\n    (authn_user_id, user_id, group_id, action)\\nSELECT $user_id, $user_id, group_id, 'join'\\nFROM log;\\n","sqlParams":{"assessment_id":2306762,"user_id":919510,"group_name":"team5"}}`,
  referrer: 'https://prairielearn.engr.illinois.edu/pl/course_instance/118734/assessment/2306762/',
  response_id: '9bf664d4-d63e-4f08-8a6e-e01d711e804f',
  level: 'error',
  message: 'Error page',
  timestamp: '2020-09-29T04:54:09.744Z'
}
```

**Comment by andrewstec** [comment]
There is a chance that deletion logic is not working properly, as none of these groups are marked as deleted_at: t, but I recall the instructor trying to delete some groups for this particular user.

![image](https://user-images.githubusercontent.com/7872295/94714192-a9e25d80-0300-11eb-95be-9c4a28f769cf.png)

Not entirely sure, but I hope this sheds some light on the situation.
