### ISSUE TITLE
Assessment IDs without set or number

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3250]
Multiple courses reported the follow error on sync. Note that `assessment_id = 2307073` is not associated with the course that was being synced.

```
error: Assertion failure: Assessment IDs without set or number: 2307073
Async Stacktrace:
    at /PrairieLearn/sync/syncFromDisk.js:103:25
    at /PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:532:13
    at /PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:509:13
    at handleError (/PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:418:13)

error: Assertion failure: Assessment IDs without set or number: 2307073
    at Parser.parseErrorMessage (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/PrairieLearn/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
{
    "sqlError": {
        "length": 203,
        "name": "error",
        "severity": "ERROR",
        "code": "P0001",
        "where": "PL/pgSQL function sync_assessments(jsonb[],bigint,bigint) line 421 at RAISE",
        "file": "pl_exec.c",
        "line": "3778",
        "routine": "exec_stmt_raise",
        "message": "Assertion failure: Assessment IDs without set or number: 2307073"
    },
    "sql": "SELECT * FROM sync_assessments($1,$2,$3)",
    "sqlParams": [
        [],
        80,
        128349
    ]
}
```

The assessment, course instance, and course are:

```
prairielearn=> select * from assessments where id = 2307073;
-[ RECORD 1 ]-----------+-------------------------------------
id                      | 2307073
tid                     | PE1draft1
course_instance_id      | 128398
type                    | Exam
number                  | 1
title                   | Practice 01
config                  |
multiple_instance       | t
shuffle_questions       | f
max_points              |
assessment_set_id       |
deleted_at              |
obj                     |
text                    |
uuid                    | bbbfd148-f3f8-41b9-a612-314e9514f72f
order_by                | 1
auto_close              | t
constant_question_value | f
allow_issue_reporting   | t
mode                    | Public
stats_last_updated      |
allow_real_time_grading | t
require_honor_code      | t
group_work              | f
sync_job_sequence_id    |
sync_errors             |
sync_warnings           |

prairielearn=> select * from course_instances where id = 128398;
-[ RECORD 1 ]--------+-------------------------------------
id                   | 128398
course_id            | 195
short_name           | New_1
long_name            | New (1)
deleted_at           | 2020-10-01 16:23:23.490594+00
uuid                 | 0d7f99c8-0bcb-46be-b02d-517ac3069113
display_timezone     | America/Chicago
ps_linked            | t
sync_job_sequence_id |
sync_errors          |
sync_warnings        |

prairielearn=> select * from pl_courses where id = 195;
-[ RECORD 1 ]--------+-------------------------------------------
id                   | 195
short_name           | CHBE 221
title                | Principles of CHE
path                 | /data1/courses/pl-chbe221
grading_queue        | chbe221
repository           | git@github.com:PrairieLearn/pl-chbe221.git
deleted_at           |
display_timezone     | America/Chicago
options              | {"useNewQuestionRenderer": false}
commit_hash          | 80eb1914392e6989b1d276a8456100404448f5cd
institution_id       | 3
example_course       | f
sync_job_sequence_id |
sync_errors          |
sync_warnings        |
```

**Comment by mwest1066** [comment]
I fixed this particular bad assessment with
```
update assessments set deleted_at = now() where id = 2307073;
```

**Comment by nwalters512** [comment]
@mwest1066 have you seen this issue occur since it was first reported?

**Comment by mwest1066** [comment]
> @mwest1066 have you seen this issue occur since it was first reported?

I don't think so. Happy to close this one.
