### ISSUE TITLE
External grader crash due to repeated callback calls

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3332]
See below for the stack trace. The offending line is: https://github.com/PrairieLearn/PrairieLearn/blob/fcea0e0ffab194ddcdcfd609b159104aedc6472d/grader_host/index.js#L260

```
node: #033[32minfo#033[39m: Received job!
node: #033[32minfo#033[39m: received 697115 from queue
node: #033[32minfo#033[39m: Logging job 697115 to S3: prairielearn.ca.grading/job_697115
node: /PrairieGrader/node_modules/async/dist/async.js:318
node: if (fn === null) throw new Error("Callback was already called.");
node: ^
node: Error: Callback was already called.
node: at /PrairieGrader/node_modules/async/dist/async.js:318:36
node: at /PrairieGrader/node_modules/async/dist/async.js:2953:17
node: at module.exports (/PrairieGrader/node_modules/async-stacktrace/ERR.js:52:7)
node: at /PrairieGrader/index.js:260:28
node: at /PrairieGrader/node_modules/dockerode/lib/docker.js:116:7
node: at Modem.buildPayload (/PrairieGrader/node_modules/docker-modem/lib/modem.js:297:19)
node: at ClientRequest.<anonymous> (/PrairieGrader/node_modules/docker-modem/lib/modem.js:282:10)
node: at ClientRequest.emit (events.js:315:20)
node: at ClientRequest.EventEmitter.emit (domain.js:483:12)
node: at Socket.socketErrorListener (_http_client.js:426:9)
systemd: prairiegrader.service: main process exited, code=exited, status=1/FAILURE
systemd: Unit prairiegrader.service entered failed state.
systemd: prairiegrader.service failed.
```

**Comment by nwalters512** [comment]
The external grader no longer uses callbacks, so this is no longer an issue.
