### ISSUE TITLE
clientFilesQuestion.js did not provide path argument

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3349]
Stack trace:

```
node: /PrairieLearn/node_modules/express/lib/response.js:411
node: throw new TypeError('path argument is required to res.sendFile');
node: ^
node: TypeError: path argument is required to res.sendFile
node: at ServerResponse.sendFile (/PrairieLearn/node_modules/express/lib/response.js:411:11)
node: at Object.<anonymous> (/PrairieLearn/pages/clientFilesQuestion/clientFilesQuestion.js:24:13)
node: at cb (util.js:207:31)
node: at processTicksAndRejections (internal/process/task_queues.js:84:21)
systemd: prairielearn4.service: main process exited, code=exited, status=1/FAILURE
```

**Comment by mwest1066** [comment]
This is being triggered by requests like:
```
{"timestamp":"2020-11-20T13:19:14.618Z","ip":"REDACTED","forwardedIP":"REDACTED","authn_user_id": REDACTED,"authn_user_uid":"REDACTED","method":"GET","path":"/pl/course_instance/121505/instructor/question/9050873/clientFilesQuestion/","params":{},"body":{},"response_id":"63458543-54f4-446d-992b-e9757afe803b","level":"verbose","message":"request"}
```
