### ISSUE TITLE
externalGraderLoad failure: InvalidParameterCombination

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3359]
Error occurred in `cronUuid: f2bef631-0fca-4668-b4b6-ce00046a11ed`. Stack trace:

```
Async Stacktrace:
    at /PrairieLearn/cron/index.js:212:21
    at /PrairieLearn/cron/index.js:244:29
    at /PrairieLearn/cron/index.js:286:29
    at /PrairieLearn/cron/index.js:306:17
    at /PrairieLearn/cron/externalGraderLoad.js:16:17
    at Response.<anonymous> (/PrairieLearn/cron/externalGraderLoad.js:347:17)

InvalidParameterCombination: At least one of the parameters must be specified.
At least one of the parameters must be specified.
    at Request.extractError (/PrairieLearn/node_modules/aws-sdk/lib/protocol/query.js:50:29)
    at Request.callListeners (/PrairieLearn/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/PrairieLearn/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/PrairieLearn/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/PrairieLearn/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/PrairieLearn/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /PrairieLearn/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/PrairieLearn/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/PrairieLearn/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/PrairieLearn/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/PrairieLearn/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/PrairieLearn/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/PrairieLearn/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/PrairieLearn/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /PrairieLearn/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/PrairieLearn/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/PrairieLearn/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/PrairieLearn/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/PrairieLearn/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/PrairieLearn/node_modules/aws-sdk/lib/event_listeners.js:313:13)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
```

Full log dump:

```
Oct 19 01:41:22 ip-10-0-0-204.us-east-2.compute.internal node[113514]: error: cron: externalGraderLoad failure: InvalidParameterCombination: At least one of the parameters must be specified.
Oct 19 01:41:22 ip-10-0-0-204.us-east-2.compute.internal node[113514]: At least one of the parameters must be specified. At least one of the parameters must be specified.
Oct 19 01:41:22 ip-10-0-0-204.us-east-2.compute.internal node[113514]: At least one of the parameters must be specified. {"stack":"Async Stacktrace:\n    at /PrairieLearn/cron/index.js:212:21\n    at /PrairieLearn/cron/index.js:244:29\n    at /PrairieLearn/cron/index.js:286:29\n    at /PrairieLearn/cron/index.js:306:17\n    at /PrairieLearn/cron/externalGraderLoad.js:16:17\n    at Response.<anonymous> (/PrairieLearn/cron/externalGraderLoad.js:347:17)\n\nInvalidParameterCombination: At least one of the parameters must be specified.\nAt least one of the parameters must be specified.\n    at Request.extractError (/PrairieLearn/node_modules/aws-sdk/lib/protocol/query.js:50:29)\n    at Request.callListeners (/PrairieLearn/node_modules/aws-sdk/lib/sequential_executor.js:106:20)\n    at Request.emit (/PrairieLearn/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/PrairieLearn/node_modules/aws-sdk/lib/request.js:688:14)\n    at Request.transition (/PrairieLearn/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/PrairieLearn/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /PrairieLearn/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/PrairieLearn/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/PrairieLearn/node_modules/aws-sdk/lib/request.js:690:12)\n    at Request.callListeners (/PrairieLearn/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n    at Request.emit (/PrairieLearn/node_modules/aws-sdk/lib/sequential_executor.js:78:10)\n    at Request.emit (/PrairieLearn/node_modules/aws-sdk/lib/request.js:688:14)\n    at Request.transition (/PrairieLearn/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/PrairieLearn/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /PrairieLearn/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/PrairieLearn/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/PrairieLearn/node_modules/aws-sdk/lib/request.js:690:12)\n    at Request.callListeners (/PrairieLearn/node_modules/aws-sdk/lib/sequential_executor.js:116:18)\n    at callNextListener (/PrairieLearn/node_modules/aws-sdk/lib/sequential_executor.js:96:12)\n    at IncomingMessage.onEnd (/PrairieLearn/node_modules/aws-sdk/lib/event_listeners.js:313:13)\n    at IncomingMessage.emit (events.js:326:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:483:12)","cronUuid":"f2bef631-0fca-4668-b4b6-ce00046a11ed"}
```

**Comment by mwest1066** [comment]
This was caused by invalid data in `CurrentUsers`, which comes from: https://github.com/PrairieLearn/PrairieLearn/blob/199df154c27feb1bd5b8d236e90cbecddfdacf89/sprocs/grader_loads_current.sql#L120

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/875833/96405027-f2739500-11a1-11eb-9dac-57739738e189.png">

**Comment by mwest1066** [comment]
The load reporting outage was from 2020-10-18T03:04:00-05:00 to 2020-10-18T03:25:00-05:00 and then again from 2020-10-18T03:30:00-05:00 to 2020-10-18T20:40:00-05:00.

**Comment by mwest1066** [comment]
Chunk servers were restarted at:
2020-10-18T08:07:06Z
2020-10-18T08:24:08Z
2020-10-18T08:32:07Z
2020-10-18T08:37:06Z
2020-10-18T08:39:07Z
2020-10-18T08:42:07Z
2020-10-18T08:48:07Z
2020-10-18T08:50:07Z

This is consistent with the above outage times.

What happened is that the chunk servers were automatically restarted for log rotation. However, they were still running version d1bcd46c943a011fbb184c1419de848fed0967bd of PL, which didn't contain the updated version of `sprocs/grader_loads_current()` from #3323 (at this time the main servers were running fcea0e0ffab194ddcdcfd609b159104aedc6472d). On restart they overwrite the sproc with the old version, which didn't have `desired_instances_current` or `desired_instances_history` return values. This then caused the errors in both load reporting and grader autoscaling.
