### ISSUE TITLE
Exited python caller causes pipe error

### ISSUE THREAD

**Issue by nicknytko** [PrairieLearn/PrairieLearn#3847]
Have seen behavior where if a python runner crashes:
```
error: Expected PythonCaller states [Symbol(CREATED),Symbol(WAITING)] but actually have state Symbol(EXITED) {"childIsNull":true,"callbackIsNull":true,"timeoutIDIsNull":true,"outputStdout":"","outputStderr":"","outputBoth":"","outputData":"{\"present\": true, \"val\": \"<div id=\\\"file-preview-20ccf2fe-122c-4cd4-ba57-bb7c5096d61c\\\">\\n  <div class=\\\"file-upload-status...
```
The node server will also crash with a pipe error:
```
Feb 18 19:20:26 ip-10-0-0-162.us-east-2.compute.internal node[11594]: throw er; // Unhandled 'error' event
Feb 18 19:20:26 ip-10-0-0-162.us-east-2.compute.internal node[11594]: ^
Feb 18 19:20:26 ip-10-0-0-162.us-east-2.compute.internal node[11594]: Error: write EPIPE
Feb 18 19:20:26 ip-10-0-0-162.us-east-2.compute.internal node[11594]: at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
Feb 18 19:20:26 ip-10-0-0-162.us-east-2.compute.internal node[11594]: Emitted 'error' event on Socket instance at:
Feb 18 19:20:26 ip-10-0-0-162.us-east-2.compute.internal node[11594]: at emitErrorNT (internal/streams/destroy.js:106:8)
Feb 18 19:20:26 ip-10-0-0-162.us-east-2.compute.internal node[11594]: at emitErrorCloseNT (internal/streams/destroy.js:74:3)
Feb 18 19:20:26 ip-10-0-0-162.us-east-2.compute.internal node[11594]: at processTicksAndRejections (internal/process/task_queues.js:80:21) {
Feb 18 19:20:26 ip-10-0-0-162.us-east-2.compute.internal node[11594]: errno: -32,
Feb 18 19:20:26 ip-10-0-0-162.us-east-2.compute.internal node[11594]: code: 'EPIPE',
Feb 18 19:20:26 ip-10-0-0-162.us-east-2.compute.internal node[11594]: syscall: 'write'
Feb 18 19:20:26 ip-10-0-0-162.us-east-2.compute.internal node[11594]: }
```
It seems like we're not gracefully handling the python process dying on us?

**Comment by eliotwrobson** [comment]
@nwalters512 does it still do this?

**Comment by nwalters512** [comment]
I haven't observed this recently; I think we can close this.
