### ISSUE TITLE
Staging chunk deploys occasionally miss the first grading job

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#3881]
I can't reproduce this completely reliably but it happens quite frequently.

Steps to (sometimes) reproduce:

1. Deploy a new chunk server image and refresh all instances. Keep existing grader and workspace host instances.
2. In student view (using the new chunk servers), launch a workspace (e.g., VS Code, but I don't think it matters), answer the question, and submit for (external) grading.
3. The grader instance gets the job from SQS but can't find the `grading_jobs` row in the DB. This is retried twice before we send the job to the dead letter queue. The grader host logs are:
```
Feb 28 15:48:06 ip-10-0-0-34.us-east-2.compute.internal node[4329]: info: Received job!
Feb 28 15:48:06 ip-10-0-0-34.us-east-2.compute.internal node[4329]: error: receive error: Incorrect rowCount: 0 {"data":{"sql":"-- BLOCK check_job_cancelation\nSELECT\n    (grading_request_canceled_at IS NOT NULL) AS canceled\nFROM grading_jobs\nWHERE id = $grading_job_id;\n","sqlParams":{"grading_job_id":91}},"stack":"Async Stacktrace:\n    at /PrairieGrader/index.js:106:23\n    at /PrairieGrader/lib/receiveFromQueue.js:126:13\n    at /PrairieGrader/lib/receiveFromQueue.js:95:21\n\nError: Incorrect rowCount: 0\n    at Object.makeWithData (/PrairieGrader/node_modules/@prairielearn/prairielib/lib/error.js:12:19)\n    at /PrairieGrader/node_modules/@prairielearn/prairielib/lib/sql-db.js:455:35\n    at Query.<anonymous> (/PrairieGrader/node_modules/@prairielearn/prairielib/lib/sql-db.js:429:17)\n    at Query.handleReadyForQuery (/PrairieGrader/node_modules/pg/lib/query.js:122:12)\n    at Client._handleReadyForQuery (/PrairieGrader/node_modules/pg/lib/client.js:281:19)\n    at Connection.emit (events.js:315:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /PrairieGrader/node_modules/pg/lib/connection.js:109:12\n    at Parser.parse (/PrairieGrader/node_modules/pg-protocol/dist/parser.js:40:17)\n    at Socket.<anonymous> (/PrairieGrader/node_modules/pg-protocol/dist/index.js:8:42)"}
Feb 28 15:48:06 ip-10-0-0-34.us-east-2.compute.internal node[4329]: info: Completed full request cycle
Feb 28 15:48:06 ip-10-0-0-34.us-east-2.compute.internal node[4329]: info: Waiting for next job...
Feb 28 15:48:36 ip-10-0-0-34.us-east-2.compute.internal node[4329]: info: Received job!
Feb 28 15:48:36 ip-10-0-0-34.us-east-2.compute.internal node[4329]: error: receive error: Incorrect rowCount: 0 {"data":{"sql":"-- BLOCK check_job_cancelation\nSELECT\n    (grading_request_canceled_at IS NOT NULL) AS canceled\nFROM grading_jobs\nWHERE id = $grading_job_id;\n","sqlParams":{"grading_job_id":91}},"stack":"Async Stacktrace:\n    at /PrairieGrader/index.js:106:23\n    at /PrairieGrader/lib/receiveFromQueue.js:126:13\n    at /PrairieGrader/lib/receiveFromQueue.js:95:21\n\nError: Incorrect rowCount: 0\n    at Object.makeWithData (/PrairieGrader/node_modules/@prairielearn/prairielib/lib/error.js:12:19)\n    at /PrairieGrader/node_modules/@prairielearn/prairielib/lib/sql-db.js:455:35\n    at Query.<anonymous> (/PrairieGrader/node_modules/@prairielearn/prairielib/lib/sql-db.js:429:17)\n    at Query.handleReadyForQuery (/PrairieGrader/node_modules/pg/lib/query.js:122:12)\n    at Client._handleReadyForQuery (/PrairieGrader/node_modules/pg/lib/client.js:281:19)\n    at Connection.emit (events.js:315:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /PrairieGrader/node_modules/pg/lib/connection.js:109:12\n    at Parser.parse (/PrairieGrader/node_modules/pg-protocol/dist/parser.js:40:17)\n    at Socket.<anonymous> (/PrairieGrader/node_modules/pg-protocol/dist/index.js:8:42)"}
Feb 28 15:48:36 ip-10-0-0-34.us-east-2.compute.internal node[4329]: info: Completed full request cycle
Feb 28 15:48:36 ip-10-0-0-34.us-east-2.compute.internal node[4329]: info: Waiting for next job...
Feb 28 15:49:06 ip-10-0-0-34.us-east-2.compute.internal node[4329]: info: Received job!
Feb 28 15:49:06 ip-10-0-0-34.us-east-2.compute.internal node[4329]: error: receive error: Incorrect rowCount: 0 {"data":{"sql":"-- BLOCK check_job_cancelation\nSELECT\n    (grading_request_canceled_at IS NOT NULL) AS canceled\nFROM grading_jobs\nWHERE id = $grading_job_id;\n","sqlParams":{"grading_job_id":91}},"stack":"Async Stacktrace:\n    at /PrairieGrader/index.js:106:23\n    at /PrairieGrader/lib/receiveFromQueue.js:126:13\n    at /PrairieGrader/lib/receiveFromQueue.js:95:21\n\nError: Incorrect rowCount: 0\n    at Object.makeWithData (/PrairieGrader/node_modules/@prairielearn/prairielib/lib/error.js:12:19)\n    at /PrairieGrader/node_modules/@prairielearn/prairielib/lib/sql-db.js:455:35\n    at Query.<anonymous> (/PrairieGrader/node_modules/@prairielearn/prairielib/lib/sql-db.js:429:17)\n    at Query.handleReadyForQuery (/PrairieGrader/node_modules/pg/lib/query.js:122:12)\n    at Client._handleReadyForQuery (/PrairieGrader/node_modules/pg/lib/client.js:281:19)\n    at Connection.emit (events.js:315:20)\n    at Connection.EventEmitter.emit (domain.js:483:12)\n    at /PrairieGrader/node_modules/pg/lib/connection.js:109:12\n    at Parser.parse (/PrairieGrader/node_modules/pg-protocol/dist/parser.js:40:17)\n    at Socket.<anonymous> (/PrairieGrader/node_modules/pg-protocol/dist/index.js:8:42)"}
Feb 28 15:49:06 ip-10-0-0-34.us-east-2.compute.internal node[4329]: info: Completed full request cycle
Feb 28 15:49:06 ip-10-0-0-34.us-east-2.compute.internal node[4329]: info: Waiting for next job...
```
4. The `grading_jobs` row appears to have been there before the first grading attempt, and well before the retries. The record is:
```
=> select * from grading_jobs where id = 91;
-[ RECORD 1 ]---------------+------------------------------
id                          | 91
date                        | 2021-02-28 15:48:06.269377+00
submission_id               | 93
grading_method              | External
grading_requested_at        | 2021-02-28 15:48:06.269377+00
grading_request_canceled_at |
grading_request_canceled_by |
graded_at                   |
graded_by                   |
score                       |
correct                     |
feedback                    |
auth_user_id                | 1
grading_submitted_at        | 2021-02-28 15:48:06.556+00
grading_started_at          |
grading_finished_at         |
partial_scores              |
v2_score                    |
grading_received_at         |
s3_bucket                   | prairielearn.staging.grading
s3_root_key                 | job_91
output                      |
gradable                    |
```
5. The chunk server logs agree that the queue submission happened after the DB row was created:
```
{"message":"Successfully set up /jobs/job_91","level":"verbose","timestamp":"2021-02-28T15:48:06.390Z"}
{"grading_job_id":91,"queueName":"grading_jobs_staging","QueueUrl":"https://REDACTED","MessageBody":"{\"jobId\":91,\"image\":\"prairielearn/grader-python\",\"entrypoint\":\"/python_autograder/run.sh\",\"s3Bucket\":\"REDACTED\",\"s3RootKey\":\"job_91\",\"webhookUrl\":null,\"csrfToken\":\"REDACTED\",\"timeout\":20,\"enableNetworking\":false}","level":"verbose","message":"Queued external grading job","timestamp":"2021-02-28T15:48:06.556Z"}
```
7. In the code we seem to clearly commit the transaction that creates the `grading_jobs` row: https://github.com/PrairieLearn/PrairieLearn/blob/d65d09050494d13f2d6937341c2eaddf7e7a17f4/lib/question.js#L646 before we submit the grading jobs: https://github.com/PrairieLearn/PrairieLearn/blob/d65d09050494d13f2d6937341c2eaddf7e7a17f4/lib/question.js#L651 so I don't understand how the grader SQL query can fail to find the job in the DB.

**Comment by nwalters512** [comment]
@mwest1066 have you noticed this happening recently? I haven't seen many jobs ending up in the DLQ at all lately.

**Comment by mwest1066** [comment]
I haven't seen this in a long time. I'm happy to close for now.
