### ISSUE TITLE
pl-file-upload: answers-name attribute gives errors

### ISSUE THREAD

**Issue by cbm755** [PrairieLearn/PrairieLearn#4352]
I have this:
```html
  <pl-file-upload file-names="cat.pdf" answers-name="foo"></pl-file-upload>
</pl-question-panel>

<pl-submission-panel>
  <pl-file-preview></pl-file-preview>
</pl-submission-panel>
```
I get this:
```
Traceback (most recent call last):
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 175, in <module>
    worker_loop()
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 121, in worker_loop
    val = method(*args)
  File "/PrairieLearn/elements/pl-file-upload/pl-file-upload.py", line 34, in prepare
    pl.check_attribs(element, required_attribs, optional_attribs)
  File "/PrairieLearn/question-servers/freeformPythonLib/prairielearn.py", line 166, in check_attribs
    raise Exception('Unknown attribute "%s"' % name)
Exception: Unknown attribute "answers-name"
Traceback (most recent call last):
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 187, in <module>
    raise Exception('worker process exited unexpectedly with status %d' % status)
Exception: worker process exited unexpectedly with status 256
```
But the docs said:

Attribute | Type | Default | description
-- | -- | -- | --
answers-name | string | _file | Variable name to store data in. For externally graded questions, you should rely on the default.

Am I doing something wrong?

**Comment by firasm** [comment]
Looks like the `answers-name` is not actually used anywhere or required by the [`file-upload`](https://github.com/PrairieLearn/PrairieLearn/blob/master/elements/pl-file-upload/pl-file-upload.py) element.

Also, it looks like [sample question in the XC101 course](https://ca.prairielearn.org/pl/course/1/question/5/preview) does not require `answers-name` either:

```
<pl-file-upload file-names="fib.py"></pl-file-upload>
```

Probably a PR to fix this in the docs is needed?
