### ISSUE TITLE
PostgreSQL issues launching workspaces since recent update (unknown param type)

### ISSUE THREAD

**Issue by echuber2** [PrairieLearn/PrairieLearn#4477]
Since https://github.com/PrairieLearn/PrairieLearn/pull/4412/ was merged, it seems I and some others can't launch workspaces locally with Docker. (Also mentioned in pl-help on Slack on July 10.)

After poking around a little bit, I think the issue is _not_ that the unique client string for the server instance has a parsing issue with characters (`:` etc.) as I thought it might have been. Also, the functions do seem to be getting defined. It seems the issue is with the passed parameter type not being resolved for some reason, such as the `unknown` in `error: function workspaces_state_update(unknown, unknown, unknown) does not exist`.

Here's an example error log:

```
  prairielearn:workspace Setting workspaces.state='stopped', workspaces.message='Initialization complete' +12ms
  prairielearn:workspace Setting workspaces.state='launching', workspaces.message='Assigning workspace host' +24ms
  prairielearn:workspace assignHost(): workspace_id=1, workspace_host_id=1 +24ms
  prairielearn:workspace Setting workspaces.message to 'Sending launch command to host' +0ms
info: Launching workspace-1-1 (useInitialZip=true)
  prairielearn:interface init: configuring workspace +0ms
  prairielearn:workspace Setting workspaces.message to 'Checking image' +0ms
info: Not pulling docker image
  prairielearn:workspace Setting workspaces.message to 'Creating container' +1ms
(node:58) UnhandledPromiseRejectionWarning: Async Stacktrace:
    at /PrairieLearn/prairielib/lib/sql-db.js:507:13
    at /PrairieLearn/prairielib/lib/sql-db.js:427:17
    at Query.callback (/PrairieLearn/prairielib/lib/sql-db.js:240:17)

error: function workspaces_message_update(unknown, unknown) does not exist
    at Parser.parseErrorMessage (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/PrairieLearn/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:375:28)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:58) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:58) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
  prairielearn:interface Creating docker container for image=[IMAGE NAME HERE] +36ms
  prairielearn:interface Exposed port: 8080 +0ms
  prairielearn:interface Env vars: WORKSPACE_BASE_URL=/pl/workspace/1/container/ +0ms
  prairielearn:interface User binding: 1001:1001 +0ms
  prairielearn:interface Port binding: 8080:15349 +0ms
  prairielearn:interface Volume mount: /home/[...]/pl_ag_jobs/workspaces/workspace-1-1/current:/home/coder/question +0ms
  prairielearn:interface Container name: workspace-6c85646c-9505-4364-a287-b84fd5437b6c +0ms
(node:58) UnhandledPromiseRejectionWarning: Async Stacktrace:
    at /PrairieLearn/prairielib/lib/sql-db.js:507:13
    at /PrairieLearn/prairielib/lib/sql-db.js:427:17
    at Query.callback (/PrairieLearn/prairielib/lib/sql-db.js:240:17)

error: function workspaces_message_update(unknown, unknown) does not exist
    at Parser.parseErrorMessage (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/PrairieLearn/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:375:28)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(node:58) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
  prairielearn:interface Creating directory /jobs/workspaces/workspace-1-1/current +3ms
  prairielearn:workspace Setting workspaces.message to 'Starting container' +147ms
(node:58) UnhandledPromiseRejectionWarning: Async Stacktrace:
    at /PrairieLearn/prairielib/lib/sql-db.js:507:13
    at /PrairieLearn/prairielib/lib/sql-db.js:427:17
    at Query.callback (/PrairieLearn/prairielib/lib/sql-db.js:240:17)

error: function workspaces_message_update(unknown, unknown) does not exist
    at Parser.parseErrorMessage (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/PrairieLearn/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:375:28)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(node:58) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
  prairielearn:interface init: container initialized for workspace_id=1 +2s
  prairielearn:workspace Setting workspaces.state='running', workspaces.message='null' +2s
(node:58) UnhandledPromiseRejectionWarning: Async Stacktrace:
    at /PrairieLearn/prairielib/lib/sql-db.js:507:13
    at /PrairieLearn/prairielib/lib/sql-db.js:427:17
    at Query.callback (/PrairieLearn/prairielib/lib/sql-db.js:240:17)

error: function workspaces_state_update(unknown, unknown, unknown) does not exist
    at Parser.parseErrorMessage (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/PrairieLearn/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:375:28)
    at Socket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(node:58) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

**Comment by mwest1066** [comment]
Oh right, I know exactly what this problem is. This is caused by #4412 and it's my fault. I'll get it fixed later today. Thanks for the bug report!
