### ISSUE TITLE
Difficulty of seeing error messages while testing elements

### ISSUE THREAD

**Issue by SethPoulsen** [PrairieLearn/PrairieLearn#4619]
I recently worked on getting automated testing running for `pl-order-blocks` and there were a few pain points I wanted to document so that we can improve the documentation and test debugging experience in the future.

- When running element tests through the web UI, it says something like "See Errors page for more information." i think it meant to be referring to the "Issues" page, but I'm not sure that's useful either because at least in my case, the "Issues page didn't say anything useful at all, it just said something like "question test failed"
- the tests shows actual and expected output, but its not always clear which fields actually need to match in order for the tests to pass. The actual checking is being done here: https://github.com/PrairieLearn/PrairieLearn/blob/master/lib/question.js#L831-L856. Maybe we should document better somewhere, or give better error messages so its more clear which fields need to match.

edit: I've learned that you _can_ actually get useful information about where your code crashed, exactly which field comparison failed, etc. if you test through the web UI, you just have to dig more. Finding the actual error message requires going to the issues page, and then clicking on the link to the 'instructor view' for the question with the issue. It is very un-intuitive to have to click multiple web pages away to see the error from running the test. Could we have these error messages shown on the page where you actually run the tests instead?

**Comment by SethPoulsen** [comment]
It would also be nice to get the detailed out put in the terminal. Right now all I get for a failing test in the terminal is 
```
 27 passing (18s)
  1 failing

  1) Auto-test questions in exampleCourse
       auto-testing question demo/proofBlocks
         the test job sequence
           should be successful:

      AssertionError: expected 'Error' to equal 'Success'
      + expected - actual

      -Error
      +Success
      
      at Context.<anonymous> (tests/helperQuestion.js:667:28)
      at processImmediate (internal/timers.js:464:21)
```
