### ISSUE TITLE
Can't run individual tests in Docker container when following documentation steps

### ISSUE THREAD

**Issue by astrosticks** [PrairieLearn/PrairieLearn#4620]
I can't seem to be able to run individual tests according to the steps in the [PL tests documentation](https://prairielearn.readthedocs.io/en/latest/dev-guide/#unit-tests-and-integration-tests).

I am running the master branch with the latest docker image.

<details>
<summary>Attempt no.1</summary>

`david@RY7C02:~/pl/prairielearn$ docker run -it --rm -v $PWD:/PrairieLearn -w /PrairieLearn prairielearn/prairielearn bash`

```
bash-4.2# node_modules/.bin/mocha tests/testAccess.js 


  Access control
    1) "before all" hook: set up testing server in "Access control"
    2) "after all" hook: shut down testing server in "Access control"


  0 passing (11ms)
  2 failing

  1) Access control
       "before all" hook: set up testing server in "Access control":
     Async Stacktrace:
    at /PrairieLearn/tests/helperServer.js:133:21                                                                            
    at /PrairieLearn/tests/helperServer.js:50:29                                                                             
    at /PrairieLearn/tests/helperDb.js:317:17                                                                                
    at /PrairieLearn/tests/helperDb.js:287:13                                                                                
    at /PrairieLearn/tests/helperDb.js:279:13                                                                                
    at Client._connectionCallback (tests/helperDb.js:258:21)                                                                 

Error: connect ECONNREFUSED 127.0.0.1:5432                                                                                   
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)                                                        

  2) Access control
       "after all" hook: shut down testing server in "Access control":
     Async Stacktrace:
    at /PrairieLearn/tests/helperServer.js:206:17
    at /PrairieLearn/tests/helperServer.js:167:25

Error: cannot stop an undefined server
      at Object.module.exports.stopServer (server.js:1020:34)
      at /PrairieLearn/tests/helperServer.js:166:24
      at /PrairieLearn/node_modules/async/dist/async.js:2948:28
      at replenish (node_modules/async/dist/async.js:440:21)
      at /PrairieLearn/node_modules/async/dist/async.js:445:13
      at eachOfLimit$1 (node_modules/async/dist/async.js:471:34)
      at awaitable (node_modules/async/dist/async.js:208:32)
      at eachOfSeries (node_modules/async/dist/async.js:658:16)
      at awaitable (node_modules/async/dist/async.js:208:32)
      at /PrairieLearn/node_modules/async/dist/async.js:2947:9
      at awaitable (node_modules/async/dist/async.js:208:32)
      at Object.series (node_modules/async/dist/async.js:3957:16)
      at Context.after (tests/helperServer.js:144:15)
      at processImmediate (internal/timers.js:464:21)



/PrairieLearn/node_modules/mocha/lib/runner.js:962
    throw err;
    ^

Error: Callback was already called.
    at /PrairieLearn/node_modules/async/dist/async.js:318:36
    at /PrairieLearn/node_modules/async/dist/async.js:2953:17
    at module.exports (/PrairieLearn/node_modules/async-stacktrace/ERR.js:52:7)
    at /PrairieLearn/tests/helperServer.js:50:29
    at module.exports (/PrairieLearn/node_modules/async-stacktrace/ERR.js:52:7)
    at /PrairieLearn/tests/helperDb.js:317:17
    at module.exports (/PrairieLearn/node_modules/async-stacktrace/ERR.js:52:7)
    at /PrairieLearn/tests/helperDb.js:298:21
    at module.exports (/PrairieLearn/node_modules/async-stacktrace/ERR.js:52:7)
    at /PrairieLearn/tests/helperDb.js:125:13
    at /PrairieLearn/node_modules/async/dist/async.js:2955:19
    at wrapper (/PrairieLearn/node_modules/async/dist/async.js:268:20)
    at iterateeCallback (/PrairieLearn/node_modules/async/dist/async.js:413:21)
    at /PrairieLearn/node_modules/async/dist/async.js:321:20
    at /PrairieLearn/node_modules/async/dist/async.js:2953:17
    at module.exports (/PrairieLearn/node_modules/async-stacktrace/ERR.js:52:7)
    at Client._connectionCallback (/PrairieLearn/tests/helperDb.js:89:21)
    at Client._handleErrorWhileConnecting (/PrairieLearn/node_modules/pg/lib/client.js:305:19)
    at Client._handleErrorEvent (/PrairieLearn/node_modules/pg/lib/client.js:315:19)
    at Connection.emit (events.js:375:28)
    at Connection.emit (domain.js:470:12)
    at Socket.reportStreamError (/PrairieLearn/node_modules/pg/lib/connection.js:53:12)
    at Socket.emit (events.js:375:28)
    at Socket.emit (domain.js:470:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

</details>

<details>

<summary>Attempt no.2: starting postgres before running test</summary>

`david@RY7C02:~/pl/prairielearn$ docker run -it --rm -v $PWD:/PrairieLearn -w /PrairieLearn prairielearn/prairielearn bash`

```
bash-4.2# docker/start_postgres.sh 
bash-4.2# node_modules/.bin/mocha tests/testAccess.js 


  Access control
    1) "before all" hook: set up testing server in "Access control"
    2) "before all" hook: set up testing server in "Access control"
    3) "after all" hook: shut down testing server in "Access control"


  0 passing (7s)
  3 failing

  1) Access control
       "before all" hook: set up testing server in "Access control":
     Uncaught Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
  Error: connect ECONNREFUSED 127.0.0.1:6379
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)

  2) Access control
       "before all" hook: set up testing server in "Access control":
     Error: done() called multiple times in hook <Access control "before all" hook: set up testing server in "Access control"> of file /PrairieLearn/tests/testAccess.js
      at /PrairieLearn/tests/helperServer.js:134:17
      at /PrairieLearn/node_modules/async/dist/async.js:2955:19
      at wrapper (node_modules/async/dist/async.js:268:20)
      at replenish (node_modules/async/dist/async.js:435:29)
      at iterateeCallback (node_modules/async/dist/async.js:424:21)
      at /PrairieLearn/node_modules/async/dist/async.js:321:20
      at /PrairieLearn/node_modules/async/dist/async.js:2953:17
      at /PrairieLearn/tests/helperServer.js:128:25
      at /PrairieLearn/question-servers/freeform.js:39:20
      at /PrairieLearn/question-servers/freeform.js:130:20
      at wrapper (node_modules/async/dist/async.js:268:20)
      at next (node_modules/async/dist/async.js:4582:24)
      at /PrairieLearn/node_modules/async/dist/async.js:321:20
      at /PrairieLearn/question-servers/freeform.js:125:28
      at wrapper (node_modules/async/dist/async.js:268:20)
      at iteratorCallback (node_modules/async/dist/async.js:495:17)
      at /PrairieLearn/node_modules/async/dist/async.js:321:20
      at /PrairieLearn/question-servers/freeform.js:120:29
      at Object.module.exports.validateJSON (lib/json-load.js:55:9)
      at /PrairieLearn/question-servers/freeform.js:102:36
      at /PrairieLearn/node_modules/universalify/index.js:22:54

  3) Access control
       "after all" hook: shut down testing server in "Access control":
     Uncaught AbortError: Stream connection ended and command aborted.
      at RedisClient.flush_and_error (node_modules/redis/index.js:297:23)
      at RedisClient.connection_gone (node_modules/redis/index.js:532:14)
      at Socket.<anonymous> (node_modules/redis/index.js:226:14)
      at Socket.emit (domain.js:470:12)
      at TCP.<anonymous> (net.js:675:12)
```

</details>

**Comment by mwest1066** [comment]
You'll need to run `make start-support` before running individual tests.

**Comment by mwest1066** [comment]
Before #4614 is merged, you'll actually need to run:
```
docker/start_postgres.sh
docker/start_redis.sh
docker/start_s3rver.sh
```
and then run individual tests.

**Comment by astrosticks** [comment]
Ok, I'll check back in here when the merge is done
