### ISSUE TITLE
pl-order-blocks crashes when indentation="false"

### ISSUE THREAD

**Issue by nealterrell** [PrairieLearn/PrairieLearn#4666]
I get this error on any pl-order-blocks element with indentation="false", either by omitting the attribute or explicitly setting to false.

```
Traceback (most recent call last):
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 182, in <module>
    worker_loop()
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 128, in worker_loop
    val = method(*args)
  File "/PrairieLearn/elements/pl-order-blocks/pl-order-blocks.py", line 334, in parse
    indent = int(answer['indent'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
Traceback (most recent call last):
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 194, in <module>
    raise Exception('worker process exited unexpectedly with status %d' % status)
Exception: worker process exited unexpectedly with status 256
```

**Comment by SethPoulsen** [comment]
Can you please give the full details of the question you are using? 

I use indentation="false" all the time with the `dag` grader and it works fine, and I know someone else was just using it with `ranking` grader the other day, also with no problem

Thanks!

**Comment by nealterrell** [comment]
I am using `external` grading. Here is the HTML:

```
<pl-order-blocks answers-name="blocks" grading-method="external" indentation="true">
    <pl-answer>import math</pl-answer>
    <pl-answer>r = float(input())</pl-answer>
    <pl-answer>PI = math.pi</pl-answer>
    <pl-answer>C = 2 * PI * r</pl-answer>
</pl-order-blocks>
```

The only role of server.py is to set up `names_for_user` for the Python autograder.

The error above occurs when clicking Save & Grade on the question page. 

here is the Associated Data from the error message:

```json
{
    "course": {
        "id": 1,
        "path": "/course",
        "title": "Introduction to Programming and Problem Solving",
        "branch": "master",
        "options": {
            "useNewQuestionRenderer": true
        },
        "deleted_at": null,
        "repository": null,
        "short_name": "CECS 174",
        "commit_hash": null,
        "sync_errors": null,
        "grading_queue": "cecs174",
        "sync_warnings": "",
        "example_course": false,
        "institution_id": 1,
        "display_timezone": "America/Chicago",
        "sync_job_sequence_id": null,
        "manual_grading_visible": false
    },
    "variant": {
        "id": "36",
        "date": "2021-08-17T16:01:37.515Z",
        "open": true,
        "qiid": null,
        "broken": false,
        "number": null,
        "params": {
            "blocks": [
                {
                    "tag": null,
                    "uuid": "55aa147f-45d0-4a91-8e2c-0ea3092c6b2f",
                    "group": null,
                    "index": 2,
                    "indent": null,
                    "depends": [],
                    "ranking": -1,
                    "inner_html": "PI = math.pi"
                },
                {
                    "tag": null,
                    "uuid": "4ec73bc3-0aa0-4aa9-9402-13572c3604d1",
                    "group": null,
                    "index": 3,
                    "indent": null,
                    "depends": [],
                    "ranking": -1,
                    "inner_html": "C = 2 * PI * r"
                },
                {
                    "tag": null,
                    "uuid": "6bc42a01-ab62-4eb3-aacb-79dace1cf08a",
                    "group": null,
                    "index": 1,
                    "indent": null,
                    "depends": [],
                    "ranking": -1,
                    "inner_html": "r = float(input())"
                },
                {
                    "tag": null,
                    "uuid": "8d02f16f-682e-4f79-81e0-c49cbe6cd0b5",
                    "group": null,
                    "index": 0,
                    "indent": null,
                    "depends": [],
                    "ranking": -1,
                    "inner_html": "import math"
                }
            ],
            "names_for_user": [],
            "names_from_user": [
                {
                    "name": "C",
                    "type": "float",
                    "description": "The computed circumference of the circle"
                }
            ]
        },
        "options": {
            "question_path": "/course/questions/python/variables/math-blocks",
            "course_extensions_path": "/course/elementExtensions",
            "client_files_course_path": "/course/clientFilesCourse",
            "server_files_course_path": "/course/serverFilesCourse",
            "client_files_question_path": "/course/questions/python/variables/math-blocks/clientFilesQuestion"
        },
        "user_id": "1",
        "duration": {},
        "group_id": null,
        "num_tries": 0,
        "question_id": "51",
        "true_answer": {
            "blocks": [
                {
                    "tag": null,
                    "uuid": "8d02f16f-682e-4f79-81e0-c49cbe6cd0b5",
                    "group": null,
                    "index": 0,
                    "indent": null,
                    "depends": [],
                    "ranking": -1,
                    "inner_html": "import math"
                },
                {
                    "tag": null,
                    "uuid": "6bc42a01-ab62-4eb3-aacb-79dace1cf08a",
                    "group": null,
                    "index": 1,
                    "indent": null,
                    "depends": [],
                    "ranking": -1,
                    "inner_html": "r = float(input())"
                },
                {
                    "tag": null,
                    "uuid": "55aa147f-45d0-4a91-8e2c-0ea3092c6b2f",
                    "group": null,
                    "index": 2,
                    "indent": null,
                    "depends": [],
                    "ranking": -1,
                    "inner_html": "PI = math.pi"
                },
                {
                    "tag": null,
                    "uuid": "4ec73bc3-0aa0-4aa9-9402-13572c3604d1",
                    "group": null,
                    "index": 3,
                    "indent": null,
                    "depends": [],
                    "ranking": -1,
                    "inner_html": "C = 2 * PI * r"
                }
            ]
        },
        "variant_seed": "c5iyra",
        "workspace_id": null,
        "authn_user_id": "1",
        "first_duration": null,
        "course_instance_id": null,
        "instance_question_id": null
    },
    "question": {
        "id": 51,
        "qid": "python/variables/math-blocks",
        "type": "Freeform",
        "uuid": "342f7935-f331-4e7f-8bb1-0d1537d9870f",
        "title": "Build a math program",
        "number": 292,
        "options": null,
        "topic_id": 3,
        "course_id": 1,
        "directory": "python/variables/math-blocks",
        "deleted_at": null,
        "sync_errors": null,
        "client_files": [
            "client.js",
            "question.html",
            "answer.html"
        ],
        "dependencies": {},
        "sync_warnings": "",
        "grading_method": "External",
        "partial_credit": true,
        "single_variant": false,
        "workspace_args": null,
        "workspace_home": null,
        "workspace_port": null,
        "workspace_image": null,
        "template_directory": null,
        "sync_job_sequence_id": null,
        "workspace_sync_ignore": null,
        "workspace_url_rewrite": null,
        "external_grading_files": null,
        "external_grading_image": "prairielearn/grader-python",
        "workspace_graded_files": null,
        "external_grading_enabled": true,
        "external_grading_timeout": null,
        "external_grading_entrypoint": "/python_autograder/run.sh",
        "workspace_enable_networking": null,
        "external_grading_enable_networking": null
    },
    "submission": {
        "gradable": true,
        "variant_id": "36",
        "auth_user_id": 1,
        "submitted_answer": {
            "blocks-input": "[{\"inner_html\":\"import math\",\"indent\":null,\"uuid\":\"8d02f16f-682e-4f79-81e0-c49cbe6cd0b5\"}]"
        },
        "raw_submitted_answer": {
            "blocks-input": "[{\"inner_html\":\"import math\",\"indent\":null,\"uuid\":\"8d02f16f-682e-4f79-81e0-c49cbe6cd0b5\"}]"
        }
    }
}
```

**Comment by nealterrell** [comment]
Changing line 334 in pl-order-blocks.py to 

```python
indent = int(answer['indent'] or 0)
```

fixes my issue, but I haven't run any other tests. This takes the `"indent"` from the `blocks` data and overrides it with a 0 when it would otherwise be `null`.

**Comment by SethPoulsen** [comment]
Thanks for the help with this. 

Is it ok if I incorporate your example question from above into the automated test suite?
