### ISSUE TITLE
nonblocking-csv-stringify RangeError: Invalid string length

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#4818]
Fetching `/pl/course_instance/128793/instructor/assessment/2312613/downloads/CS_411_Fa21_SQL_HW1_all_submissions.csv` results in:
```
node[27870]: /PrairieLearn/lib/nonblocking-csv-stringify.js:44
node[27870]: return callback(null, chunks.join(''));
node[27870]: ^
node[27870]: RangeError: Invalid string length
node[27870]: at Array.join (<anonymous>)
node[27870]: at Stringifier.<anonymous> (/PrairieLearn/lib/nonblocking-csv-stringify.js:44:38)
node[27870]: at Stringifier.emit (events.js:315:20)
node[27870]: at Stringifier.EventEmitter.emit (domain.js:467:12)
node[27870]: at endReadableNT (internal/streams/readable.js:1327:12)
node[27870]: at processTicksAndRejections (internal/process/task_queues.js:80:21)
systemd[1]: prairielearn.service: main process exited, code=exited, status=1/FAILURE
```

**Comment by nwalters512** [comment]
As of #7284, all CSV generation is done via streaming instead of constructing an entire string in memory, which should have fixed this. We haven't seen any issues with CSV generation failing since that change was deployed.
