### ISSUE TITLE
Rich text editor encoding/decoding error

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#4841]
I have an automatically reported error for a `rich-text` editor question so I thought I'd report it since it seems to be about decoding.

After decoding the contents, I was able to reproduce the error by entering the following string:

```
I didn’t understand vectors quite well
```

The error is related to the `’` character, which may have been copy/pasted from Word etc...

## Traceback

```
Traceback (most recent call last):
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 182, in <module>
    worker_loop()
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 128, in worker_loop
    val = method(*args)
  File "/data1/courses/pl-ubc-phys111/questions/fake/Week03 Most Confusing Concepts/server.py", line 35, in grade
    response =  message_bytes.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 9: ordinal not in range(128)
Traceback (most recent call last):
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 194, in <module>
    raise Exception('worker process exited unexpectedly with status %d' % status)
Exception: worker process exited unexpectedly with status 256
```

## Associated Data

<details>

```
{
    "course": {
        "id": 27,
        "path": "/data1/courses/pl-ubc-phys111",
        "title": "Introductory Physics for the Physical Sciences I",
        "branch": "master",
        "options": {
            "useNewQuestionRenderer": true
        },
        "deleted_at": null,
        "repository": "git@learning.github.ubc.ca:PrairieLearn/pl-ubc-phys111.git",
        "short_name": "Physics 111",
        "commit_hash": "d1799987ad89969e0929be7dc043dbc42d36f5cb",
        "sync_errors": null,
        "grading_queue": "physics111",
        "sync_warnings": "",
        "example_course": false,
        "institution_id": 4,
        "display_timezone": "America/Vancouver",
        "sync_job_sequence_id": null,
        "manual_grading_visible": false
    },
    "variant": {
        "id": "2914362",
        "date": "2021-09-22T23:01:53.642Z",
        "open": true,
        "qiid": null,
        "broken": false,
        "number": 1,
        "params": {
            "vars": {
                "title": "Chapter X - Confusing concepts"
            },
            "part1_ans": [
                {
                    "key": "a",
                    "html": " Instantaneous Velocity and Speed  "
                },
                {
                    "key": "b",
                    "html": " Motion with Constant Acceleration  "
                },
                {
                    "key": "c",
                    "html": " Finding Velocity and Displacement from Acceleration "
                },
                {
                    "key": "d",
                    "html": " Free Fall  "
                },
                {
                    "key": "e",
                    "html": " Average and Instantaneous Acceleration "
                },
                {
                    "key": "f",
                    "html": " Position, Displacement, and Average Velocity  "
                }
            ],
            "_required_file_names": [
                "answer.html"
            ]
        },
        "options": {
            "question_path": "/data1/courses/pl-ubc-phys111/questions/fake/Week03 Most Confusing Concepts",
            "course_extensions_path": "/data1/courses/pl-ubc-phys111/elementExtensions",
            "client_files_course_path": "/data1/courses/pl-ubc-phys111/clientFilesCourse",
            "server_files_course_path": "/data1/courses/pl-ubc-phys111/serverFilesCourse",
            "client_files_question_path": "/data1/courses/pl-ubc-phys111/questions/fake/Week03 Most Confusing Concepts/clientFilesQuestion"
        },
        "user_id": "332488",
        "duration": {
            "minutes": 2,
            "seconds": 46,
            "milliseconds": 78.103
        },
        "group_id": null,
        "num_tries": 0,
        "question_id": "231271",
        "true_answer": {
            "part1_ans": [
                {
                    "key": "c",
                    "html": " Finding Velocity and Displacement from Acceleration "
                },
                {
                    "key": "d",
                    "html": " Free Fall  "
                }
            ]
        },
        "variant_seed": "1xqxs65",
        "workspace_id": null,
        "authn_user_id": "332488",
        "first_duration": {
            "minutes": 2,
            "seconds": 46,
            "milliseconds": 78.103
        },
        "course_instance_id": "2344",
        "instance_question_id": "9573128"
    },
    "question": {
        "id": 231271,
        "qid": "fake/Week03 Most Confusing Concepts",
        "type": "Freeform",
        "uuid": "d6be54aa-d629-4e06-a266-22929252bf0a",
        "title": "Week 3 Most Confusing Concepts",
        "number": 1003,
        "options": null,
        "topic_id": 391833,
        "course_id": 27,
        "directory": "fake/Week03 Most Confusing Concepts",
        "deleted_at": null,
        "sync_errors": null,
        "client_files": [
            "client.js",
            "question.html",
            "answer.html"
        ],
        "dependencies": {},
        "sync_warnings": "",
        "grading_method": "Internal",
        "partial_credit": true,
        "single_variant": false,
        "workspace_args": null,
        "workspace_home": null,
        "workspace_port": null,
        "workspace_image": null,
        "template_directory": null,
        "sync_job_sequence_id": null,
        "workspace_sync_ignore": null,
        "workspace_url_rewrite": null,
        "external_grading_files": null,
        "external_grading_image": null,
        "workspace_graded_files": null,
        "external_grading_enabled": null,
        "external_grading_timeout": null,
        "external_grading_entrypoint": null,
        "workspace_enable_networking": null,
        "external_grading_enable_networking": null
    },
    "submission": {
        "id": "3740492",
        "sid": null,
        "date": "2021-09-23T09:47:20.891Z",
        "mode": "Public",
        "score": null,
        "broken": false,
        "credit": 100,
        "params": {
            "vars": {
                "title": "Chapter X - Confusing concepts"
            },
            "part1_ans": [
                {
                    "key": "a",
                    "html": " Instantaneous Velocity and Speed  "
                },
                {
                    "key": "b",
                    "html": " Motion with Constant Acceleration  "
                },
                {
                    "key": "c",
                    "html": " Finding Velocity and Displacement from Acceleration "
                },
                {
                    "key": "d",
                    "html": " Free Fall  "
                },
                {
                    "key": "e",
                    "html": " Average and Instantaneous Acceleration "
                },
                {
                    "key": "f",
                    "html": " Position, Displacement, and Average Velocity  "
                }
            ],
            "_required_file_names": [
                "answer.html"
            ]
        },
        "correct": null,
        "duration": {
            "seconds": 29,
            "milliseconds": 512.557
        },
        "feedback": null,
        "gradable": true,
        "v2_score": null,
        "graded_at": null,
        "regradable": false,
        "variant_id": "2914362",
        "true_answer": {
            "part1_ans": [
                {
                    "key": "c",
                    "html": " Finding Velocity and Displacement from Acceleration "
                },
                {
                    "key": "d",
                    "html": " Free Fall  "
                }
            ]
        },
        "auth_user_id": "332488",
        "format_errors": {},
        "grading_method": null,
        "override_score": null,
        "partial_scores": null,
        "submitted_answer": {
            "_files": [
                {
                    "name": "answer.html",
                    "contents": "PHA+SSBkaWRu4oCZdCB1bmRlcnN0YW5kIHZlY3RvcnMgcXVpdGUgd2VsbDwvcD4="
                }
            ],
            "part1_ans": [
                "b",
                "e"
            ],
            "_rich_text_editor_48804503159bdd12842c1e5d78e93cd32687b00c": "PHA+SSBkaWRu4oCZdCB1bmRlcnN0YW5kIHZlY3RvcnMgcXVpdGUgd2VsbDwvcD4="
        },
        "grading_requested_at": null,
        "raw_submitted_answer": {
            "part1_ans": [
                "b",
                "e"
            ],
            "_rich_text_editor_48804503159bdd12842c1e5d78e93cd32687b00c": "PHA+SSBkaWRu4oCZdCB1bmRlcnN0YW5kIHZlY3RvcnMgcXVpdGUgd2VsbDwvcD4="
        }
    }
}
```

</details>

**Comment by firasm** [comment]
I think #4835 fixed this, and with PL version `f3942c535` deployed, this is now handled.
