### ISSUE TITLE
UnboundLocalError: local variable 'feedback'

### ISSUE THREAD

**Issue by cbm755** [PrairieLearn/PrairieLearn#4854]
I think this is related somehow to #4821.

@jonatanschroeder is helping me locally, but I thought I'd get it up on the issue tracker....

```
Traceback (most recent call last):
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 182, in <module>
    worker_loop()
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 128, in worker_loop
    val = method(*args)
  File "/PrairieLearn/elements/pl-multiple-choice/pl-multiple-choice.py", line 352, in grade
    data['partial_scores'][name] = {'score': score, 'weight': weight, 'feedback': feedback}
UnboundLocalError: local variable 'feedback' referenced before assignment
Traceback (most recent call last):
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 194, in <module>
    raise Exception('worker process exited unexpectedly with status %d' % status)
Exception: worker process exited unexpectedly with status 256
```

So far 3 out of 690 people have hit this but deadline it not until next week.  I have some reason to think its people that accessed it first before the Sept 17th fixes, b/c my own account is one of the accounts that sees it.   I think the "new variant" workaround recovers from this but its a little hard to tell and a little awkward to do b/c the question has 3 attempts and many blanks and MC to fill-in...

**Comment by jonatanschroeder** [comment]
@mwest1066 this is a different bug than the one fixed in #4821. I'm trying to figure out the problem, hopefully should be able to send a PR later.

**Comment by jonatanschroeder** [comment]
Ok, found the problem, will fix after I sing Happy Birthday to my daughter. The problem happens if the key is none of the options. This question in particular overwrites parse to make this not a format error.

**Comment by cbm755** [comment]
For the record my parse function looks like:
```python
def parse(data):
    """Modify parsing to mark blank multiple choice wrong instead of invalid.

    https://learning.github.ubc.ca/PrairieLearn/pl-ubc-math253/issues/63
    https://github.com/PrairieLearn/PrairieLearn/issues/4246
    """
    try:
        del data['format_errors']['line_limit_how_many']
    except KeyError:
        pass
    try:
        del data['format_errors']['conclusion']
    except KeyError:
        pass
```
where `line_limit_how_many` and `conclusion` are my MC questions.  Once I/we figure out a workaround, I will update here.

**Comment by cbm755** [comment]
From reading your fix, I think I just need to make `somedict['feedback'] = None`

I think it is something like
```
# data['params']['line_limit_how_many']   <--  this is some kind of list of dicts
for d in in data['params']['line_limit_how_many']:
   d['feedback'] = None
```
But that didn't work.  I also tried:
```
    for d in data['partial_scores']['line_limit_how_many']:
        d['feedback'] = None
```
And just `KeyError: 'partial_scores'`.

I think my workaround will be to remove my original blank-is-wrong-hack.

**Comment by jonatanschroeder** [comment]
If you want to hack until this is pushed/deployed, you can copy the `elements/pl-multiple-choice` directory from the fix PR and copy to the `elements` folder in your course.

**Comment by cbm755** [comment]
For anyone else trying this: I copied `elements/pl-multiple-choice` from the central PrairieLearn git main branch to:

* `elements/pl-multiple-choice` in the root of my course repo.

FYI: things I tried that didn't work (I'm not sure why I thought they might).
* `questions/my_broken_question/elements/pl-multiple-choice` 
* `courseInstances/Autumn2021/elements/pl-multiple-choice` 

So this a pretty scary workaround: haven't decided whether to push and risk breaking things for 680 students, or keep replying to forum posts for those that hit this bug!

**Comment by cbm755** [comment]
Well I pulled the trigger...  err.... *pushed* the trigger.  Nothing has exploded yet!  Thanks @jonatanschroeder for the quick fix and @mwest1066 for the merge!
