### ISSUE TITLE
Allow for workspace image to be hosted on container registries other than Docker Hub (e.g. GitHub Container Registry)

### ISSUE THREAD

**Issue by matthewfeickert** [PrairieLearn/PrairieLearn#5285]
:wave: Hi. I'm opening up this Issue to continue some discussion with @nwalters512 from the PL Slack.

At the moment, the PL docs for the workspaces mention that in the `info.json` schema the Docker image should be hosted on Docker Hub

https://github.com/PrairieLearn/PrairieLearn/blob/e5ae2c3eae0532acdbfe59b373331f26ef1b057e/docs/workspaces/index.md#L60

I've tried in an example to see if it would be possible to use an alternative container registry (such as [GitHub Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) (`ghcr`)) to host images used for PL, but that seems to not work at the moment as when I tried to launch a workspace I got an error and when I tried to sync the image on PL I got the error

```
Pulling ghcr.io/phys-214-quantum-physics/phys-2xx-image:latest
Error: Error syncing ghcr.io/phys-214-quantum-physics/phys-2xx-image:latest: (HTTP code 404) unexpected - pull access denied for phys-214-quantum-physics/phys-2xx-image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied 
Async Stacktrace:
    at /PrairieLearn/lib/dockerUtil.js:200:13

Error: (HTTP code 404) unexpected - pull access denied for phys-214-quantum-physics/phys-2xx-image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied 
    at /PrairieLearn/node_modules/docker-modem/lib/modem.js:301:17
    at IncomingMessage.<anonymous> (/PrairieLearn/node_modules/docker-modem/lib/modem.js:328:9)
    at /PrairieLearn/node_modules/@opentelemetry/context-async-hooks/build/src/AbstractAsyncHooksContextManager.js:49:55
    at AsyncLocalStorage.run (async_hooks.js:305:14)
    at AsyncLocalStorageContextManager.with (/PrairieLearn/node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)
    at IncomingMessage.contextWrapper (/PrairieLearn/node_modules/@opentelemetry/context-async-hooks/build/src/AbstractAsyncHooksContextManager.js:49:32)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:467:12)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
{
    "_previousMessages": [
        "(HTTP code 404) unexpected - pull access denied for phys-214-quantum-physics/phys-2xx-image, repository does not exist or may require 'docker login': denied: requested access to the resource is denied "
    ]
}
```

The image in question here (`ghcr.io/phys-214-quantum-physics/phys-2xx-image`) [is public](https://github.com/PHYS-214-Quantum-Physics/PHYS-2XX-image/pkgs/container/phys-2xx-image), so anyone should be able to pull its `latest` tag with

```console
docker pull ghcr.io/phys-214-quantum-physics/phys-2xx-image:latest
```

If possible, it would be nice to support other container registries beyond Docker Hub, like ghcr, especially as Docker Hub changed their policy on the number of [access tokens](https://docs.docker.com/docker-hub/access-tokens/) that free accounts can have in their end of 2021 pricing changes: Now personal accounts only get **1** (previous existing ones are rolled over, which is good for me as I have 11).

cc @msneubauer

**Comment by jonatanschroeder** [comment]
Related: #4005

**Comment by natepark01** [comment]
Second this. Our course already has a CI that is seamless within our Github org and repos, and this would be super helpful.

**Comment by nwalters512** [comment]
I did a little digging here. AWS ECR (which we use as an image cache to avoid rate-limiting on public registries) supports image names that contain both dots and multiple slashes. So in theory, we can push and pull fully-qualified image names from other registries to/from AWS ECR. 

In fact, getting syncing working might be as simple as swapping out `getRepository()` for `getRegistryRepo()` in `apps/prairielearn/src/pages/shared/syncHelpers.ts`. We'd also have to update `workspace-host` and `grader-host` to be aware of this too.

We may want to re-scope Docker Hub images to always use an explicit `docker.io` registry. And if we do that, we'd also have to rewrite all existing images with that explicit registry, so that might be more trouble than it's worth.
