### ISSUE TITLE
v2 questions report "path" error

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#5293]
(reported by @glherman)

Since we deployed 90049a27c, some v2 questions in production have been reporting `The "path" argument must be of type string. Received null`.

To reproduce, go to CS 233 Spring 2022, change to student view, select assessment W2.03PRE, and click on the question "Full Adder Specification".

The stack trace is:
```
Async Stacktrace:
    at /PrairieLearn/pages/studentInstanceQuestionHomework/studentInstanceQuestionHomework.js:175:9
    at /PrairieLearn/lib/question.js:1970:13
    at /PrairieLearn/lib/question.js:1829:21
    at /PrairieLearn/lib/question.js:426:17
    at /PrairieLearn/lib/question.js:417:21
    at /PrairieLearn/lib/question.js:340:17
    at /PrairieLearn/lib/question.js:252:13
    at /PrairieLearn/lib/question.js:117:13
    at /PrairieLearn/question-servers/calculation.js:102:11
    at Object.<anonymous> (/PrairieLearn/question-servers/calculation.js:34:13)

TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be of type string. Received null
    at new NodeError (internal/errors.js:322:7)
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1148:7)
    at Object.module.exports.coursePathForChunk (/PrairieLearn/lib/chunks.js:210:19)
    at /PrairieLearn/lib/chunks.js:975:38
    at Array.map (<anonymous>)
    at Object.module.exports.ensureChunksForCourseAsync (/PrairieLearn/lib/chunks.js:971:19)
```

It looks like the error is being thrown at: https://github.com/PrairieLearn/PrairieLearn/blob/90049a27c302c011358b78a1636c3fd11d470124/lib/chunks.js#L210 which is called from: https://github.com/PrairieLearn/PrairieLearn/blob/90049a27c302c011358b78a1636c3fd11d470124/lib/chunks.js#L975

The [NodeJS docs for `path.join()`](https://nodejs.org/api/path.html#pathjoinpaths) indicate that exactly this error message will be reported if any of the arguments are not strings, so this is consistent. This means either `coursePath` or `chunkMetadata.questionName` is `null` for v2 questions, but I can't see why this would be the case.

I was unable to reproduce this error in staging -- the question referenced above worked fine in student view in staging.

**Comment by nwalters512** [comment]
I found out which instance was serving my requests by searching for the error code in the CloudWatch logs. I connected to it and added the following above the failing `path.join`:

```
logger.info(`${coursePath} ${chunkMetadata.questionName} ${JSON.stringify(chunkMetadata)}`);
```

This produced the following log:
```
 /chunks/course-76/course null {"type":"question","questionName":null}
```

So, `questionName` is indeed null. Will keep digging.

**Comment by nwalters512** [comment]
Here's the result of the `select_metadata_for_chunks` query:

```json
[
{
    "id": "4318",
    "uuid": "e252fcb8-ebf7-4443-b1f5-161b2e2325c6",
    "type": "question",
    "course_id": "76",
    "course_instance_id": null,
    "assessment_id": null,
    "question_id": "1784510",
    "question_name": "fulladder",
    "assessment_name": null,
    "course_instance_name": null
}
,
{
    "id": "4323",
    "uuid": "072314b0-b505-4b83-bfc7-1c015f28715f",
    "type": "question",
    "course_id": "76",
    "course_instance_id": null,
    "assessment_id": null,
    "question_id": "1784512",
    "question_name": "halfadder",
    "assessment_name": null,
    "course_instance_name": null
}
,
{
    "id": "4246",
    "uuid": "e908fe1a-3598-4aa9-ac64-086fa66617c3",
    "type": "clientFilesCourse",
    "course_id": "76",
    "course_instance_id": null,
    "assessment_id": null,
    "question_id": null,
    "question_name": null,
    "assessment_name": null,
    "course_instance_name": null
}
,
{
    "id": "4453",
    "uuid": "f808a1a0-7680-445b-b09b-8271faf51be4",
    "type": "serverFilesCourse",
    "course_id": "76",
    "course_instance_id": null,
    "assessment_id": null,
    "question_id": null,
    "question_name": null,
    "assessment_name": null,
    "course_instance_name": null
}
,
{
    "id": null,
    "uuid": null,
    "type": "question",
    "course_id": null,
    "course_instance_id": null,
    "assessment_id": null,
    "question_id": null,
    "question_name": null,
    "assessment_name": null,
    "course_instance_name": null
}
]
```

That last chunks is extremely suspicious.

Here's the `chunks` that's passed to the query as `chunks_arr`:

```json
[
{
    "type": "question",
    "questionId": "1784510"
}
,
{
    "type": "clientFilesCourse"
}
,
{
    "type": "serverFilesCourse"
}
,
{
    "type": "question",
    "questionId": "1784512"
}
,
{
    "type": "question",
    "questionId": "23131"
}
]
```

**Comment by nwalters512** [comment]
That last question is the problem:

```
prairielearn=> SELECT id, qid, course_id, deleted_at FROM questions WHERE id = 23131;
  id   |    qid    | course_id |          deleted_at
-------+-----------+-----------+------------------------------
 23131 | halfadder |        76 | 2018-08-14 15:54:20.18088+00
```

The `select_template_question_ids` query is not correctly excluding deleted questions. I'll put up a fix for this.
