### ISSUE TITLE
`prairielearn/grader-python` is missing `prairielearn` library

### ISSUE THREAD

**Issue by coatless** [PrairieLearn/PrairieLearn#5313]
`prairielearn/grader-python` is missing `prairielearn` library.

```
info: container> Traceback (most recent call last):
info: container>   File "/grade/run/pl_main.py", line 41, in <module>
info: container>     from filenames.test import Test as test_case
info: container>   File "/grade/run/filenames/test.py", line 6, in <module>
info: container>     import prairielearn as pl
info: container> ModuleNotFoundError: No module named 'prairielearn'
```

This is useful to have on the grader to access `pl.from_json(self.data['params']['mydata']`.

**Comment by eliotwrobson** [comment]
Reopened because this is still an issue (and is planned for the autograder rewrite).
