### ISSUE TITLE
ZeroDivisionError in dag grader on pl-order-blocks questions

### ISSUE THREAD

**Issue by ffund** [PrairieLearn/PrairieLearn#5478]
For example, this question:
```
<pl-order-blocks answers-name="order-numbers" grading-method="ranking">
  <pl-answer correct="false" ranking="1">1</pl-answer>
  <pl-answer correct="false" ranking="2">2</pl-answer>
  <pl-answer correct="false" ranking="3">3</pl-answer>
  <pl-answer correct="true"  ranking="4">Hello</pl-answer>
</pl-order-blocks>
```

raises this error when I submit for grading:

```
Traceback (most recent call last):
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 182, in <module>
    worker_loop()
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 128, in worker_loop
    val = method(*args)
  File "/PrairieLearn/elements/pl-order-blocks/pl-order-blocks.py", line 451, in grade
    final_score = max(0, float(true_answer_length - edit_distance) / true_answer_length)
ZeroDivisionError: float division by zero
Traceback (most recent call last):
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 194, in <module>
    raise Exception('worker process exited unexpectedly with status %d' % status)
Exception: worker process exited unexpectedly with status 256
```

**Comment by ffund** [comment]
@SethPoulsen  For reference - the same error is also raised if there are multiple correct blocks, but all at the same ranking level. (I think the fix covers this case, too.)

**Comment by SethPoulsen** [comment]
Yes, that makes sense. It will fix that case too.
