### ISSUE TITLE
Redis connection failure results in double-set headers

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#5537]
If the Redis cluster dies then we fail to handle the error gracefully:
```
Mar 25 00:20:49 node[23255]: error: Error page {"id":"7VBIT563O6DB","msg":"Redis connection lost and command aborted. It might have been processed."
Mar 25 00:20:49 node[23255]: _http_outgoing.js:561
Mar 25 00:20:49 node[23255]: throw new ERR_HTTP_HEADERS_SENT('set');
Mar 25 00:20:49 node[23255]: ^
Mar 25 00:20:49 node[23255]: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
Mar 25 00:20:49 node[23255]: at new NodeError (internal/errors.js:322:7)
Mar 25 00:20:49 node[23255]: at ServerResponse.setHeader (_http_outgoing.js:561:11)
Mar 25 00:20:49 node[23255]: at ServerResponse.header (/PrairieLearn/node_modules/express/lib/response.js:776:10)
Mar 25 00:20:49 node[23255]: at ServerResponse.append (/PrairieLearn/node_modules/express/lib/response.js:737:15)
Mar 25 00:20:49 node[23255]: at ServerResponse.res.cookie (/PrairieLearn/node_modules/express/lib/response.js:862:8)
Mar 25 00:20:49 node[23255]: at PostgresPool.<anonymous> (/PrairieLearn/pages/authCallbackLti/authCallbackLti.js:131:13)
Mar 25 00:20:49 node[23255]: at cb (util.js:290:31)
Mar 25 00:20:49 node[23255]: at processTicksAndRejections (internal/process/task_queues.js:82:21) {
Mar 25 00:20:49 node[23255]: code: 'ERR_HTTP_HEADERS_SENT'
Mar 25 00:20:49 node[23255]: }
Mar 25 00:20:49 systemd[1]: prairielearn.service: main process exited, code=exited, status=1/FAILURE
```

**Comment by reteps** [comment]
Closed via #9384
