### ISSUE TITLE
RedisAdapter does not handle errors

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#5538]
```
Mar 25 00:32:14 node[15202]: events.js:377
Mar 25 00:32:14 node[15202]: throw er; // Unhandled 'error' event
Mar 25 00:32:14 node[15202]: ^
Mar 25 00:32:14 node[15202]: Error: read ECONNRESET
Mar 25 00:32:14 node[15202]: at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
Mar 25 00:32:14 node[15202]: at TCP.callbackTrampoline (internal/async_hooks.js:130:17)
Mar 25 00:32:14 node[15202]: Emitted 'error' event on RedisAdapter instance at:
Mar 25 00:32:14 node[15202]: at RedisClient.onError (/PrairieLearn-canary/node_modules/socket.io-redis/dist/index.js:65:22)
Mar 25 00:32:14 node[15202]: at /PrairieLearn-canary/node_modules/@opentelemetry/context-async-hooks/build/src/AbstractAsyncHooksContextManager.js:49:55
Mar 25 00:32:14 node[15202]: at AsyncLocalStorage.run (async_hooks.js:303:14)
Mar 25 00:32:14 node[15202]: at AsyncLocalStorageContextManager.with (/PrairieLearn-canary/node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)
Mar 25 00:32:14 node[15202]: at RedisClient.contextWrapper (/PrairieLearn-canary/node_modules/@opentelemetry/context-async-hooks/build/src/AbstractAsyncHooksContextManager.js:49:32)
Mar 25 00:32:14 node[15202]: at RedisClient.emit (events.js:412:35)
Mar 25 00:32:14 node[15202]: at RedisClient.emit (domain.js:475:12)
Mar 25 00:32:14 node[15202]: at RedisClient.on_error (/PrairieLearn-canary/node_modules/redis/index.js:342:14)
Mar 25 00:32:14 node[15202]: at Socket.<anonymous> (/PrairieLearn-canary/node_modules/redis/index.js:223:14)
Mar 25 00:32:14 node[15202]: at /PrairieLearn-canary/node_modules/@opentelemetry/context-async-hooks/build/src/AbstractAsyncHooksContextManager.js:49:55
Mar 25 00:32:14 node[15202]: at AsyncLocalStorage.run (async_hooks.js:303:14)
Mar 25 00:32:14 node[15202]: at AsyncLocalStorageContextManager.with (/PrairieLearn-canary/node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)
Mar 25 00:32:14 node[15202]: at Socket.contextWrapper (/PrairieLearn-canary/node_modules/@opentelemetry/context-async-hooks/build/src/AbstractAsyncHooksContextManager.js:49:32)
Mar 25 00:32:14 node[15202]: at Socket.emit (events.js:400:28)
Mar 25 00:32:14 node[15202]: at Socket.emit (domain.js:475:12)
Mar 25 00:32:14 node[15202]: at emitErrorNT (internal/streams/destroy.js:106:8)
Mar 25 00:32:14 node[15202]: at emitErrorCloseNT (internal/streams/destroy.js:74:3)
Mar 25 00:32:14 node[15202]: at processTicksAndRejections (internal/process/task_queues.js:82:21) {
Mar 25 00:32:14 node[15202]: errno: -104,
Mar 25 00:32:14 node[15202]: code: 'ECONNRESET',
Mar 25 00:32:14 node[15202]: syscall: 'read'
Mar 25 00:32:14 node[15202]: }
Mar 25 00:32:14 systemd[1]: prairielearn.service: main process exited, code=exited, status=1/FAILURE
```

**Comment by nwalters512** [comment]
As of #8630, we not explicitly handle error events.
