### ISSUE TITLE
Crash due to null `points_list`

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#6169]
```
lib/question.js:1486
locals.variantAttemptsLeft = instance_question.points_list.length;
^
TypeError: Cannot read properties of null (reading 'length')
at Object._buildLocals (lib/question.js:1486:70)
at async.series.params.variant_id (lib/question.js:1623:44)
at node_modules/async/dist/async.js:3674:28
at replenish (node_modules/async/dist/async.js:446:21)
at iterateeCallback (node_modules/async/dist/async.js:430:21)
at node_modules/async/dist/async.js:327:20
at node_modules/async/dist/async.js:3679:17
at lib/question.js:1594:17
at PostgresPool.<anonymous> (lib/question.js:307:18)
at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by jonatanschroeder** [comment]
Did #6171 resolve this? Should it be closed?

**Comment by nwalters512** [comment]
Yes! GitHub just didn't autoclose because I misformatted my comment.
