### ISSUE TITLE
Error in instructorAssessment

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#631]
```
Apr 14 07:15:09 ip-10-0-0-204 node: 2017-04-14T07:15:09.135Z - #033[32minfo#033[39m: Error page msg=Incorrect rowCount: 0, id=NIR2PLIN4H8P,
 status=undefined, stack=Async Stacktrace:
Apr 14 07:15:09 ip-10-0-0-204 node: at /PrairieLearn/pages/studentInstanceQuestionHomework/studentInstanceQuestionHomework.js:200:17
Apr 14 07:15:09 ip-10-0-0-204 node: at /PrairieLearn/pages/studentInstanceQuestionHomework/studentInstanceQuestionHomework.js:64:13
Apr 14 07:15:09 ip-10-0-0-204 node: at /PrairieLearn/assessments/homework.js:265:21
Apr 14 07:15:09 ip-10-0-0-204 node: at /PrairieLearn/lib/sqldb.js:158:17
Apr 14 07:15:09 ip-10-0-0-204 node: at /PrairieLearn/assessments/homework.js:146:25
Apr 14 07:15:09 ip-10-0-0-204 node: Error: Incorrect rowCount: 0
Apr 14 07:15:09 ip-10-0-0-204 node: at Object.makeWithData (/PrairieLearn/lib/error.js:12:19)
Apr 14 07:15:09 ip-10-0-0-204 node: at /PrairieLearn/lib/sqldb.js:95:39
Apr 14 07:15:09 ip-10-0-0-204 node: at Query.<anonymous> (/PrairieLearn/lib/sqldb.js:85:17)
Apr 14 07:15:09 ip-10-0-0-204 node: at Query.handleReadyForQuery (/PrairieLearn/node_modules/pg/lib/query.js:124:10)
Apr 14 07:15:09 ip-10-0-0-204 node: at Connection.<anonymous> (/PrairieLearn/node_modules/pg/lib/client.js:172:19)
Apr 14 07:15:09 ip-10-0-0-204 node: at emitOne (events.js:101:20)
Apr 14 07:15:09 ip-10-0-0-204 node: at Connection.emit (events.js:191:7)
Apr 14 07:15:09 ip-10-0-0-204 node: at Socket.<anonymous> (/PrairieLearn/node_modules/pg/lib/connection.js:136:12)
Apr 14 07:15:09 ip-10-0-0-204 node: at emitOne (events.js:96:13)
Apr 14 07:15:09 ip-10-0-0-204 node: at Socket.emit (events.js:191:7), data={"sql":"--BLOCK lock_with_variant_id\nSELECT\n    to_jsonb(v.*) AS variant,\n    ai.id AS assessment_instance_id\nFROM\n    variants AS v\n    JOIN instance_questions AS iq ON (iq.id = v.instance_question_id)\n    JOIN assessment_instances AS ai ON (ai.id = iq.assessment_instance_id)\nWHERE\n    v.id = $variant_id\n    AND iq.id = $instance_question_id -- ensure the variant matches the instance_question\n    AND v.available -- ensure the variant is still available\nFOR UPDATE OF ai;\n","params":{"variant_id":"1654973","instance_question_id":4157943},"result":{"command":"SELECT","rowCount":0,"oid":null,"rows":[],"fields":[{"name":"variant","tableID":0,"columnID":0,"dataTypeID":3802,"dataTypeSize":-1,"dataTypeModifier":-1,"format":"text"},{"name":"assessment_instance_id","tableID":16486,"columnID":1,"dataTypeID":20,"dataTypeSize":8,"dataTypeModifier":-1,"format":"text"}],"_parsers":[null,null],"rowAsArray":false},"rollback":"success"}, referrer=https://prairielearn.engr.illinois.edu/pl/course_instance/530/instance_question/4157943/, response_id=SE2PYNBLVTED
Apr 14 07:15:17 ip-10-0-0-204 node: /PrairieLearn/pages/instructorAssessment/instructorAssessment.js:546
Apr 14 07:15:17 ip-10-0-0-204 node: msg = 'ERROR updating ' + assessment_instance_label + ' for ' + user_uid;
Apr 14 07:15:17 ip-10-0-0-204 node: ^
Apr 14 07:15:17 ip-10-0-0-204 node: ReferenceError: assessment_instance_label is not defined
Apr 14 07:15:17 ip-10-0-0-204 node: at /PrairieLearn/pages/instructorAssessment/instructorAssessment.js:546:59
Apr 14 07:15:17 ip-10-0-0-204 node: at module.exports (/PrairieLearn/node_modules/async-stacktrace/ERR.js:52:7)
Apr 14 07:15:17 ip-10-0-0-204 node: at /PrairieLearn/lib/sqldb.js:230:17
Apr 14 07:15:17 ip-10-0-0-204 node: at module.exports (/PrairieLearn/node_modules/async-stacktrace/ERR.js:52:7)
Apr 14 07:15:17 ip-10-0-0-204 node: at /PrairieLearn/lib/sqldb.js:223:17
Apr 14 07:15:17 ip-10-0-0-204 node: at module.exports (/PrairieLearn/node_modules/async-stacktrace/ERR.js:52:7)
Apr 14 07:15:17 ip-10-0-0-204 node: at handleError (/PrairieLearn/lib/sqldb.js:181:17)
Apr 14 07:15:17 ip-10-0-0-204 node: at Query.<anonymous> (/PrairieLearn/lib/sqldb.js:189:25)
Apr 14 07:15:17 ip-10-0-0-204 node: at Query.handleError (/PrairieLearn/node_modules/pg/lib/query.js:141:17)
Apr 14 07:15:17 ip-10-0-0-204 node: at Connection.<anonymous> (/PrairieLearn/node_modules/pg/lib/client.js:180:26)
Apr 14 07:15:17 ip-10-0-0-204 systemd: prairielearn.service: main process exited, code=exited, status=1/FAILURE
```

**Comment by mwest1066** [comment]
This is a bug in the error-handling code that was triggered by #630.
