### ISSUE TITLE
lstat chunks error

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#6450]
While investigating https://sentry.io/organizations/prairielearn-inc/issues/3647099844/ I noticed that the same chunk server had a similar fatal crash shortly afterwards. We seem to be missing a error handler somewhere (and I'm not sure why these `lstat` calls are failing in the first place).

The two separate issues are:

Sentry error:
```
Oct 05 14:03:58 error: Error rendering panels for submission ENOENT: no such file or directory, lstat '/chunks/course-76/__chunks/downloads/ba487f7d-59c3-4646-957f-8417aabfed41.tar.gz' {"code"
Oct 05 14:03:58 This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected
Oct 05 14:03:58 Async Stacktrace:
Oct 05 14:03:58 at /PrairieLearn/lib/externalGradingSocket.js:65:13
Oct 05 14:03:58 at /PrairieLearn/lib/externalGradingSocket.js:118:11
Oct 05 14:03:58 at /PrairieLearn/lib/question.js:2033:15
Oct 05 14:03:58 at /PrairieLearn/lib/question.js:1880:21
Oct 05 14:03:58 at /PrairieLearn/lib/question.js:1351:15
Oct 05 14:03:58 Error: ENOENT: no such file or directory, lstat '/chunks/course-76/__chunks/downloads/ba487f7d-59c3-4646-957f-8417aabfed41.tar.gz'
```

Fatal error (not sent to Sentry):
```
Oct 05 14:09:05 Async Stacktrace:
Oct 05 14:09:05 at /PrairieLearn/pages/studentInstanceQuestionExam/studentInstanceQuestionExam.js:211:9
Oct 05 14:09:05 at /PrairieLearn/lib/question.js:1749:13
Oct 05 14:09:05 at /PrairieLearn/lib/question.js:1592:21
Oct 05 14:09:05 at /PrairieLearn/lib/question.js:320:17
Oct 05 14:09:05 at /PrairieLearn/lib/question.js:234:13
Oct 05 14:09:05 at /PrairieLearn/lib/question.js:102:13
Oct 05 14:09:05 Error: ENOENT: no such file or directory, lstat '/chunks/course-332/__chunks/downloads/c97d233e-0ac7-4da6-9f12-d247d6399dc3.tar.gz'
Oct 05 14:09:05 error: Error page {"id":"UMB37BSEX5YC","msg":"ENOENT: no such file or directory, lstat '/chunks/course-332/__chunks/downloads/c97d233e-0ac7-4da6-9f12-d247d6399dc3.tar.gz'","ref
Oct 05 14:09:05 prairielearn.service: main process exited, code=exited, status=1/FAILURE
```

**Comment by reteps** [comment]
Claude claims both bugs are resolved, via a series of PRs that improved robustness. See #10981 #9396 #9895 #10970
