### ISSUE TITLE
Bug report: message for duplicate UUID is an error

### ISSUE THREAD

**Issue by firasm** [PrairieLearn/PrairieLearn#6539]
In the past when I duplicate a question locally and it has a duplicate UUID, PL just gently warns me about it at every sync.

This time I had a duplicate UUID I got an error message when I tried to sync"

[Here's a link to the error message](https://ca.prairielearn.com/pl/course_instance/2478/instructor/jobSequence/66849) and the useful part (`"detail": "Key (course_id, uuid)=(54, 0e8097aa-b554-4908-9eac-d46a78d6c249) already exists.",`):

```
Trying lock coursedir:/data1/courses/pl-ubc-data301
Acquired lock coursedir:/data1/courses/pl-ubc-data301
Loading info.json files from course repository
Syncing info to database
error: duplicate key value violates unique constraint "questions_course_id_number_nondeleted_key"
Async Stacktrace:
    at Object.<anonymous> (/srv/sysconf/ca/main/revisions/0641f0eac6082dd4521d9d818d3bf6fffaf7d053/sync/syncFromDisk.js:136:15)

error: duplicate key value violates unique constraint "questions_course_id_number_nondeleted_key"
    at Parser.parseErrorMessage (/srv/sysconf/ca/main/revisions/0641f0eac6082dd4521d9d818d3bf6fffaf7d053/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/srv/sysconf/ca/main/revisions/0641f0eac6082dd4521d9d818d3bf6fffaf7d053/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/srv/sysconf/ca/main/revisions/0641f0eac6082dd4521d9d818d3bf6fffaf7d053/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/srv/sysconf/ca/main/revisions/0641f0eac6082dd4521d9d818d3bf6fffaf7d053/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
{
    "sqlError": {
        "length": 1873,
        "name": "error",
        "severity": "ERROR",
        "code": "23505",
        "detail": "Key (course_id, uuid)=(54, 0e8097aa-b554-4908-9eac-d46a78d6c249) already exists.",
        "where": "SQL statement \"WITH\n    matched_rows AS (\n        SELECT src.qid AS src_qid, src.uuid AS src_uuid, dest.id AS dest_id -- matched_rows cols have underscores\n        FROM disk_questions AS src LEFT JOIN questions AS dest ON (\n            dest.course_id = syncing_course_id\n            AND (src.uuid = dest.uuid\n                 OR ((src.uuid IS NULL OR dest.uuid IS NULL)\n                     AND src.qid = dest.qid AND dest.deleted_at IS NULL)))\n    ),\n    deactivate_unmatched_dest_rows AS (\n        UPDATE questions AS dest\n        SET deleted_at = now()\n        WHERE dest.id NOT IN (\n            SELECT dest_id FROM matched_rows WHERE dest_id IS NOT NULL\n        ) AND dest.deleted_at IS NULL AND dest.course_id = syncing_course_id\n    ),\n    update_matched_dest_rows AS (\n        UPDATE questions AS dest\n        SET qid = src_qid, uuid = src_uuid, deleted_at = NULL\n        FROM matched_rows\n        WHERE dest.id = dest_id AND dest.course_id = syncing_course_id\n    ),\n    insert_unmatched_src_rows AS (\n        INSERT INTO questions AS dest (course_id, qid, uuid, deleted_at)\n        SELECT syncing_course_id, src_qid, src_uuid, NULL\n        FROM matched_rows\n        WHERE dest_id IS NULL\n        RETURNING dest.qid AS src_qid, dest.id AS inserted_dest_id\n    )\n    -- Make a map from QID to ID to return to the caller\n    SELECT jsonb_object_agg(src_qid, COALESCE(dest_id, inserted_dest_id))\n                            FROM matched_rows LEFT JOIN insert_unmatched_src_rows USING (src_qid)\"\nPL/pgSQL function sync_questions(jsonb[],bigint) line 41 at SQL statement",
        "schema": "public",
        "table": "questions",
        "constraint": "questions_course_id_number_nondeleted_key",
        "file": "nbtinsert.c",
        "line": "534",
        "routine": "_bt_check_unique",
        "message": "duplicate key value violates unique constraint \"questions_course_id_number_nondeleted_key\""
    },
    "sql": "SELECT * FROM \"sync_questions\"($1,$2);",
    "sqlParams": [
        [
            "[\"firas_templates/check_string\",\"73134876-bae2-4405-8d03-efbd6afc8f4b\",\"\",\"\",{\"type\":\"Freeform\",\"title\":\"Check String answer\",\"partial_credit\":true,\"client_files\":[\"client.js\",\"question.html\",\"answer.html\"],\"topic\":\"Gallery\",\"grading_method\":\"Internal\",\"single_variant\":true,\"show_correct_answer\":false,\"external_grading_environment\":{},\"dependencies\":{},\"workspace_environment\":{}}]",

# ...[and the rest of my questions printed out - clipped out to save space]

        ],
        54
    ]
}
```

I found the duplicate UUID, fixed it, and then pushed it back up and the sync then worked.

**Comment by nwalters512** [comment]
A breadcrumb: the sync immediately preceding the one that failed included a duplicate UUID warning (https://ca.prairielearn.com/pl/course/54/jobSequence/66846, syncing commit https://github.com/PrairieLearnUBC/pl-ubc-data301/commit/8010bc2e75838a570b90f190951c385cc9ae6358):

<img width="999" alt="Screenshot 2022-10-27 at 13 06 49" src="https://user-images.githubusercontent.com/1476544/198387749-af5c7d99-b68e-4ee8-bdb5-8755c9b662bb.png">

When https://github.com/PrairieLearnUBC/pl-ubc-data301/commit/6c350e43ac485e4c6f469b8ebb7f8959113a08bb was synced, that's when we saw the error. I'll try to reproduce locally by syncing those commits in that order.

**Comment by nwalters512** [comment]
Unfortunately syncing those two commits in that order locally did not reproduce the bug.

**Comment by nwalters512** [comment]
I was able to reproduce by walking slightly farther back! By first syncing https://github.com/PrairieLearnUBC/pl-ubc-data301/commit/314d30edf7405427d6a89695f21d447965400c16 and then syncing the two commits in the order listed above, I can reproduce the error 🙌

**Comment by nwalters512** [comment]
Well, this is a doozy. It takes a very precise sequence of steps to trigger this condition:

1. Create a question `A` with UUID `1`
1. Sync
1. Delete question `A`
1. Create question `B` with UUID `1`
1. Create question `C` with UUID `1`
1. Sync
1. Change UUID of `B` to `2`
1. Sync

After step 6, the DB is in an interesting configuration:

- We have a row `A` with `uuid = 1 AND deleted_at IS NOT NULL`
- We have a row `B` and `C` with `uuid IS NULL AND deleted_at IS NULL`

As soon as we "fix" the UUID, we're left with a problem: which is the "real" question with ID 1, `A` or `C`? I think the answer should be `C`, because it exists on disk, but our current syncing code can't handle that. I'll need to think through how we can make it do so.

**Comment by firasm** [comment]
It's almost comical how absurd those steps sound out of context 😂😂. Anyway, nice work!! Glad this is fixed so other users are saved from themselves.
