### ISSUE TITLE
Forgetting to return data in v3 questions crashes server

### ISSUE THREAD

**Issue by jakebailey** [PrairieLearn/PrairieLearn#830]
I forgot to return `data` from my `server.py`'s grade function, which caused PL to crash completely with the error:
```
/PrairieLearn/question-servers/freeform.js:866
                if (_.size(data.format_errors) > 0) data.gradable = false;
                               ^

TypeError: Cannot read property 'format_errors' of null
    at module.exports.processQuestion (/PrairieLearn/question-servers/freeform.js:866:32)
    at module.exports.processQuestionServer (/PrairieLearn/question-servers/freeform.js:512:21)
    at execPythonServer (/PrairieLearn/question-servers/freeform.js:491:24)
    at pc.call (/PrairieLearn/question-servers/freeform.js:219:17)
    at PythonCaller._callCallback (/PrairieLearn/lib/code-caller.js:291:9)
    at PythonCaller._callIsFinished (/PrairieLearn/lib/code-caller.js:312:22)
    at PythonCaller._handleStdio3Data (/PrairieLearn/lib/code-caller.js:221:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:561:20)
```

(Arguably, we wanted calling these functions to modify `data` and not return it, though from reading `freeform.js`, it's not clear to me how it's better than returning and reading the output, or possible at all.)

**Comment by mwest1066** [comment]
Dup of #770
