### ISSUE TITLE
Example question `element/graph` is not working in production

### ISSUE THREAD

**Issue by jonatanschroeder** [PrairieLearn/PrairieLearn#8631]
https://us.prairielearn.com/pl/course/108/question/3118036/preview

Raises an issue:
```
Traceback (most recent call last):
  File "/PrairieLearn/apps/prairielearn/python/zygote.py", line 359, in <module>
    worker_loop()
  File "/PrairieLearn/apps/prairielearn/python/zygote.py", line 261, in worker_loop
    val = method(*args)
  File "/PrairieLearn/apps/prairielearn/elements/pl-graph/pl-graph.py", line 180, in render
    graphviz_data = matrix_backends[input_type](element, data)
  File "/course/elementExtensions/pl-graph/edge-inc-matrix/edge-inc-matrix.py", line 18, in graphviz_from_inc_matrix
    mat = np.array(pl.from_json(data["params"][input_param]))
KeyError: None
Traceback (most recent call last):
  File "/PrairieLearn/apps/prairielearn/python/zygote.py", line 401, in <module>
    raise Exception(
Exception: worker process exited unexpectedly with status 256
```

**Comment by eliotwrobson** [comment]
This appears to be related to element extensions, which have weird implementation semantics. Did something change that might affect that?

**Comment by jonatanschroeder** [comment]
I'm not seeing the error locally, only in production. I'm wondering if it may have something to do with chunks or some other configuration that only happens in production?

**Comment by nwalters512** [comment]
I can confirm that this question works again after I synced the changes from #8646.
