### ISSUE TITLE
Python using ascii instead of utf-8

### ISSUE THREAD

**Issue by mliljenberg** [PrairieLearn/PrairieLearn#906]
When i left a comment in a mustache file containing a swedish letter (å,ä,ö) i got the following error when trying to compile: 

```
Traceback (most recent call last):
  File "/PrairieLearn/lib/python-caller-trampoline.py", line 59, in <module>
    val = method(*args)
  File "/PrairieLearn/elements/pl_draw_click/pl_draw_click.py", line 56, in render
    html = chevron.render(f, html_params).strip()
  File "/usr/lib/python3.6/site-packages/chevron/renderer.py", line 167, in render
    for tag, key in tokens:
  File "/usr/lib/python3.6/site-packages/chevron/tokenizer.py", line 165, in tokenize
    template = template.read()
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
```

**Comment by nwalters512** [comment]
We should always be opening files explicitly with utf-8 encoding so that this is consistent between platforms.
