### ISSUE TITLE
fibonacciEditor fails to grade if submitted code has a syntax error

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#933]
If you enter code with a syntax error for `exampleCourse/questions/fibonacciEditor` then it will never return from grading, because behind the scenes we get:

```
2017-12-02T16:20:30.164Z - error: processGradingResult: error message=invalid grading.score, stack=Async Stacktrace:
    at async.series (/Users/mwest/git/PrairieLearn/lib/assessment.js:356:17)

Error: invalid grading.score
    at Object.makeWithData (/Users/mwest/git/PrairieLearn/lib/error.js:12:19)
    at async.series (/Users/mwest/git/PrairieLearn/lib/assessment.js:334:43)
    at /Users/mwest/git/PrairieLearn/node_modules/async/dist/async.js:3686:9
    at replenish (/Users/mwest/git/PrairieLearn/node_modules/async/dist/async.js:881:17)
    at /Users/mwest/git/PrairieLearn/node_modules/async/dist/async.js:885:9
    at eachOfLimit (/Users/mwest/git/PrairieLearn/node_modules/async/dist/async.js:912:22)
    at /Users/mwest/git/PrairieLearn/node_modules/async/dist/async.js:917:16
    at _parallel (/Users/mwest/git/PrairieLearn/node_modules/async/dist/async.js:3685:5)
    at Object.series (/Users/mwest/git/PrairieLearn/node_modules/async/dist/async.js:4525:3)
    at Object.processGradingResult (/Users/mwest/git/PrairieLearn/lib/assessment.js:328:15)
    at EventEmitter.gradeRequest.on (/Users/mwest/git/PrairieLearn/lib/externalGrader.js:104:35)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at async.waterfall (/Users/mwest/git/PrairieLearn/lib/externalGraderLocal.js:202:25)
    at /Users/mwest/git/PrairieLearn/node_modules/async/dist/async.js:359:16
    at nextTask (/Users/mwest/git/PrairieLearn/node_modules/async/dist/async.js:5057:29), data={"content":{"gradingId":1,"grading":{"receivedTime":"2017-12-02T16:20:23.523Z","startTime":"2017-12-02T16:20:29.369Z","endTime":"2017-12-02T16:20:30.125Z","feedback":{"received_time":"2017-12-02T16:20:23.523Z","start_time":"2017-12-02T16:20:29.369Z","end_time":"2017-12-02T16:20:30.125Z","succeeded":true,"job_id":1,"results":{"output":"Compile error!","succeeded":false}}}}}
```

There are two issues here, I think:
1. This question should return valid grading data even when there was a syntax error.
2. PL should report back to the student that grading failed somehow, rather than just spinning forever in "grading..."

**Comment by nwalters512** [comment]
Current plan is to solve this implicitly as part of a complete rewrite of the example python grader. Using `unittest` should prevent any errors from remaining uncaught, and should serve as a good way for instructors to assert over student code. I'll write a custom test reporter to capture output in the format we want it and add decorators to support points/timeouts/etc.
