### ISSUE TITLE
Error logging error from DB query cancellation

### ISSUE THREAD

**Issue by mwest1066** [PrairieLearn/PrairieLearn#990]
We apparently need to be more careful about what we are passing to winston for logging:

```
Jan 22 19:24:05 ip-10-0-0-204.us-east-2.compute.internal node[566]: 2018-01-22T19:24:05.006Z - info: Error page msg=canceling statement due to user request, id=TWWQQPL570G2, status=undefined, stack=Async Stacktrace:
Jan 22 19:24:05 ip-10-0-0-204.us-east-2.compute.internal node[566]: at assessment.makeAssessmentInstance (/PrairieLearn/pages/studentAssessmentExam/studentAssessmentExam.js:43:17)
Jan 22 19:24:05 ip-10-0-0-204.us-east-2.compute.internal node[566]: at sqldb.endTransaction (/PrairieLearn/lib/assessment.js:147:25)
Jan 22 19:24:05 ip-10-0-0-204.us-east-2.compute.internal node[566]: at /PrairieLearn/lib/sqldb.js:199:17
Jan 22 19:24:05 ip-10-0-0-204.us-east-2.compute.internal node[566]: at sqldb.callWithClientOneRow (/PrairieLearn/lib/assessment.js:76:29)
Jan 22 19:24:05 ip-10-0-0-204.us-east-2.compute.internal node[566]: at /PrairieLearn/lib/sqldb.js:329:17
Jan 22 19:24:05 ip-10-0-0-204.us-east-2.compute.internal node[566]: at Query.<anonymous> (/PrairieLearn/lib/sqldb.js:114:21)
Jan 22 19:24:05 ip-10-0-0-204.us-east-2.compute.internal node[566]: error: canceling statement due to user request
Jan 22 19:24:05 ip-10-0-0-204.us-east-2.compute.internal node[566]: at Connection.parseE (/PrairieLearn/node_modules/pg/lib/connection.js:546:11)
Jan 22 19:24:05 ip-10-0-0-204.us-east-2.compute.internal node[566]: at Connection.parseMessage (/PrairieLearn/node_modules/pg/lib/connection.js:371:19)
Jan 22 19:24:05 ip-10-0-0-204.us-east-2.compute.internal node[566]: at Socket.<anonymous> (/PrairieLearn/node_modules/pg/lib/connection.js:114:22)
Jan 22 19:24:05 ip-10-0-0-204.us-east-2.compute.internal node[566]: at emitOne (events.js:116:13)
Jan 22 19:24:05 ip-10-0-0-204.us-east-2.compute.internal node[566]: at Socket.emit (events.js:211:7)
Jan 22 19:24:05 ip-10-0-0-204.us-east-2.compute.internal node[566]: at addChunk (_stream_readable.js:263:12)
Jan 22 19:24:05 ip-10-0-0-204.us-east-2.compute.internal node[566]: at readableAddChunk (_stream_readable.js:250:11)
Jan 22 19:24:05 ip-10-0-0-204.us-east-2.compute.internal node[566]: at Socket.Readable.push (_stream_readable.js:208:10)
Jan 22 19:24:05 ip-10-0-0-204.us-east-2.compute.internal node[566]: at TCP.onread (net.js:594:20), data={“sqlError”:{“name”:“error”,“length”:638,“severity”:“ERROR”,“code”:“57014",“where”:“while inserting index tuple (6541,7) in relation \“assessment_instances_assessment_id_user
Jan 22 19:24:49 ip-10-0-0-204.us-east-2.compute.internal sshd[24819]: Received disconnect from 115.238.245.2 port 58203:11:  [preauth]
Jan 22 19:24:49 ip-10-0-0-204.us-east-2.compute.internal sshd[24819]: Disconnected from 115.238.245.2 port 58203 [preauth]
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: 2018-01-22T19:25:20.661Z - error: idle client error error: terminating connection due to administrator command
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: at Connection.parseE (/PrairieLearn/node_modules/pg/lib/connection.js:546:11)
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: at Connection.parseMessage (/PrairieLearn/node_modules/pg/lib/connection.js:371:19)
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: at Socket.<anonymous> (/PrairieLearn/node_modules/pg/lib/connection.js:114:22)
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: at emitOne (events.js:116:13)
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: at Socket.emit (events.js:211:7)
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: at addChunk (_stream_readable.js:263:12)
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: at readableAddChunk (_stream_readable.js:250:11)
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: at Socket.Readable.push (_stream_readable.js:208:10)
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: at TCP.onread (net.js:594:20)
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: /PrairieLearn/node_modules/winston/lib/winston/common.js:210
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: return JSON.stringify(output, function (key, value) {
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: ^
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: TypeError: Converting circular structure to JSON
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: at JSON.stringify (<anonymous>)
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: at Object.exports.log (/PrairieLearn/node_modules/winston/lib/winston/common.js:210:17)
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: at exports.File.File.log (/PrairieLearn/node_modules/winston/lib/winston/transports/file.js:147:23)
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: at transportLog (/PrairieLearn/node_modules/winston/lib/winston/logger.js:234:15)
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: at /PrairieLearn/node_modules/winston/node_modules/async/lib/async.js:157:13
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: at _each (/PrairieLearn/node_modules/winston/node_modules/async/lib/async.js:57:9)
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: at Object.async.each (/PrairieLearn/node_modules/winston/node_modules/async/lib/async.js:156:9)
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: at exports.Logger.Logger.log (/PrairieLearn/node_modules/winston/lib/winston/logger.js:246:9)
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: at exports.Logger.target.(anonymous function) [as error] (/PrairieLearn/node_modules/winston/lib/winston/common.js:54:18)
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal node[566]: at idleErrorHandler (/PrairieLearn/server.js:395:24)
Jan 22 19:25:20 ip-10-0-0-204.us-east-2.compute.internal systemd[1]: prairielearn.service: main process exited, code=exited, status=1/FAILURE
```

**Comment by mwest1066** [comment]
We did a big Winston fix-up some time ago.
